### ISSUE TITLE
Убрать на главной странице фильтр (дропдаун) "Страна"

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1024]
### Описание задачи
Убрать на главной странице фильтр (дропдаун) "Страна"

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Фильтр (дропдаун) "Город" доступен для выбора всегда
- [ ] Остаётся фильтр (дропдаун) "Город"
- [ ] В фильтре (дропдауне) "Город" показываются города, удовлетворяющие одновременно двум условиям:
    - [ ] В городе проходит мероприятие в будущем
    - [ ] Город находится в Сербии или Черногории  

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
