### ISSUE TITLE
Убрать из тега "meta" упоминания Кыргызстан

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1025]
### Описание задачи
Убрать из тега "meta" упоминания Кыргызстан

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] В теге "meta" отсутствует упоминание Кыргызстана

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
