### ISSUE TITLE
Поменять набор тегов

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1028]
### Описание задачи
Поменять набор тегов
 
### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Набор тегов должен состоять из нижеперечисленного.
- [x] Английский вариант:
- ‘Concerts and show',
- 'Festivals',
- 'Exhibitions',
- 'Theatre',
- ‘Lectures and masterclasses', 
- 'Parties', 
- 'Business and networking',
- ‘Tourism and excursions',
- 'Board games and quizzes’,
- 'Tastings',
- 'Restaurants'
- ‘Fairs and city events',
- 'Sport',
- ‘For children',
- '18+',
- [x] Русский вариант
- 'Концерты и шоу’,
- ‘Фестивали',
- ‘Выставки',
- ‘Театр',
- 'Лекции и мастер-классы’,
- ‘Вечеринки',
- 'Бизнес и Нетворкинг’,
- 'Туры и Экскурсии’,
- 'Настольные игры и Квизы’,
- ‘Дегустации',
- 'Рестораны',
- 'Ярмарки и городские мероприятия’,
- ‘Спорт',
- 'Для детей’,
- ‘18+',

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено. При английском переводе, тег "18+" отображается как "for adults"
скрин бага 
[https://drive.google.com/file/d/1OYxu6iVq1lbcoi-bX4VJHyl9nRdrd8GE/view?usp=sharing](url)

**Comment by AlexeyPQA** [comment]
проверено
