### ISSUE TITLE
 (Теги в хедере) Я как пользователь хочу выбирать тип мероприятия которые находятся в шапке сайта в виде облака тегов, так как я сразу вижу все категории и могу их отсортировать

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1029]
### Описание задачи
Ценность: Предоставление возможности выбора категорий мероприятий через облако тегов улучшит пользовательский опыт, сделает навигацию по сайту более интуитивно понятной и доступной. Это может привести к увеличению вовлеченности пользователей и повышению их активности на сайте, так как выбор интересующих мероприятий становится быстрее и проще.

Отображать фильтр по тегам на главной странице в виде облака тегов
[Референс](https://belgrad-consult.com/afisha-belgrada)
Полный список тегов в задаче #1028 

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ]  Отображаются только те теги, которые существуют в будущих ивентах
- [ ]  Учесть небольшое количество тегов (2-3)
- [ ]  Учесть большое количество тэгов (15)
- [ ]  Учесть различные разрешения экранов
- [ ] Тэг "все" не нужен, если не выбран ни один тэг - то отображаются все ивенты.
- [ ] Все выбранные для мероприятий категории/теги мероприятий должны быть доступны в шапке сайта в виде облака тегов-кнопок. 
- [ ] Пользователь может одним нажатием выбрать интересующую категорию без необходимости использования выпадающего списка.
- [ ] Выбор категории приводит к фильтрации мероприятий по выбранному тегу без перезагрузки страницы.
- [ ] Облако тегов должно быть визуально привлекательным и не загромождать интерфейс.
- [ ] Дизайн облака тегов должен быть адаптивным, чтобы корректно отображаться на различных устройствах.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
https://docs.google.com/spreadsheets/d/1_q4VJT0x9oYbaoBDqpg03jxNdrT-0I61F0OuEVJPRvo/edit?usp=sharing

Проверено, но выглядит не очень привлекательно из-за "лестницы" из тегов, особенно на мобильной версии браузеров
