### ISSUE TITLE
(Лого-Флаг) Я как пользователь из Сербии и Черногории хочу быстро определять в какой стране функционирует этот сайт посредством флагов в логотипе

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1030]
### Описание задачи

Технические заметки:

Возможно, потребуется разработка нескольких вариантов дизайна для выбора оптимального решения.
Необходимо обеспечить, чтобы новый дизайн логотипа был адаптирован под различные форматы использования, включая маркетинговые материалы и социальные сети.
Провести тестирование нового логотипа на предмет его влияния на узнаваемость бренда.

Ценность:
Явное выделение региона Балкан путем интеграции соответствующих элементов в логотип сайта может укрепить лояльность местной аудитории и привлечь новых пользователей, заинтересованных в содержании, связанном с этим регионом. Это также может способствовать более высокому уровню вовлеченности и интерактивности со стороны пользователей, идентифицирующих себя с регионом Балкан.

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Возможные варианты
- Надпись Сербия
- Флаг Сербии + Надпись Сербия 
- Флаг Сербии
- Надпись Сербия и Черногория
- Флаг Сербии + Надпись Сербия + Флаг Черногории + Надпись Черногория
- Флаг Сербии + Флаг Черногории
- Отображение должно быть легко заменимо
- [ ] Флаг или символика региона Балкан должны быть интегрированы в дизайн текущего логотипа сайта, не нарушая его узнаваемость.
- [ ] Добавление элементов должно быть выполнено таким образом, чтобы оно гармонично сочеталось с общей визуальной концепцией сайта.
- [ ] Логотип с добавленными элементами должен корректно отображаться на всех типах устройств и размерах экранов.
- [ ] Изменение логотипа не должно негативно сказаться на времени загрузки страниц сайта.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by il12** [comment]
Примерный вариант


![Image](https://github.com/openworld-community/ows-events/assets/19169013/ec141f50-2c34-4968-b521-695bfa9746b2)

**Comment by il12** [comment]
![Image](https://github.com/openworld-community/ows-events/assets/19169013/eefbe3a1-6156-4528-96f2-20bf89f4c0d7)

**Comment by i-salimzhanov** [comment]
![Image](https://github.com/openworld-community/ows-events/assets/146735283/fb40ce94-39b3-466a-bc20-03459074f1f0)
![Image](https://github.com/openworld-community/ows-events/assets/146735283/df7cc56a-6c9a-4fd0-97ab-070b2162052f)

Утверджённый вариант региональной айдентики.
