### ISSUE TITLE
Календарь. Как пользователь, я хочу иметь возможность выбирать временной промежуток в календаре, чтобы видеть события только за определенный период времени, одном окне.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1039]
### Критерии приемки

- [ ] Как пользователь, я должен иметь возможность открыть календарь в одном окне без необходимости перехода на другие страницы или окна.
- [ ] Как пользователь, я должен иметь возможность использовать интерактивные элементы управления для месяцев, такие как переключение стрелочками в окне (кликом мыши), а так же  клавишей Tab
- [ ] Как пользователь, я должен иметь возможность использовать интерактивные элементы управления для дней, такие как визуальные кнопки даты в окне (кликом мыши), а так же  клавишей Tab
- [ ] Как пользователь, я ожидаю, что события будут автоматически обновляться, отображая только события, которые происходят в выбранном временном промежутке, без перезагрузки страницы или перехода на другие вкладки.
- [ ] Как пользователь, я хочу иметь возможность выбрать временной промежуток, а не только конкретную дату.
- [ ] Как пользователь, я хочу, чтобы интерфейс выбора временного промежутка был интуитивно понятным и простым в использовании, чтобы я мог быстро определить нужный период времени.
   - можно выбрать одну дату
   - можно выбрать промежуток дат

Прим. разработчика :
1) для выбора одной даты нужно закрыть календарь кликом вне выпадающего списка
2) при выборе двух дат список закрывается автоматические и значения применяются
3) система фильтрации работает как и раньше: при одной дате диапазон как бы "число Х - бесконечность", если нужны ивенты в конкретный день, то надо выбрать диапазон из одинаковых дат. Для двух разных дат все работает как ожидается

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено, есть ошибки по отображению ивентов при выборе даты через кнопку "Сегодня" и кнопку "Завтра". Так же не выбирается дата при помощи клавиатуры (клавишей "Таб" переключение между датами и месяцами работает, а при нажатии на клавишу "Ентер" для выбора интересуещей даты - выходит из календаря).
https://docs.google.com/spreadsheets/d/1_q4VJT0x9oYbaoBDqpg03jxNdrT-0I61F0OuEVJPRvo/edit?usp=sharing

**Comment by AlexeyPQA** [comment]
проверено
