### ISSUE TITLE
Поправить доступность кнопок

### ISSUE THREAD

**Issue by orby-tech** [openworld-community/ows-events#104]
**Is your feature request related to a problem? Please describe.**
Я увидел только одну такую, но нужно это исправить

Без этого некоторые люди не смогут добавлять эвенты

![image](https://github.com/openworld-community/ows-events/assets/59844758/716de83e-b6e1-4ed5-802c-090d06406975)

**Comment by andrIvash** [comment]
https://github.com/openworld-community/ows-events/pull/109

**Comment by orby-tech** [comment]
Отлично!
