### ISSUE TITLE
Парсер переделано: Поменять тег "Конференции" для переделано на тег "Бизнес и нетворкинг"

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1045]
### Описание задачи
Поменять тег "Конференции" для переделано на тег "Бизнес и нетворкинг" при парсинге

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Спаршенные конференции переделано обладают тегом "Бизнес и нетворкинг"

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
