### ISSUE TITLE
(Вкладка Сотрудничество) Я как пользователь или рекламодатель хочу видеть страницу сотрудничества с Афиша переделано

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1065]
### Описание задачи
Как создатель мероприятий или рекламодатель, я хочу видеть страницу сотрудничества на сайте Афиша, доступную через кнопку "Сотрудничество", чтобы я мог понимать, как и на каких условиях возможно взаимодействие с сервисом.
Убедиться, что страница оптимизирована для различных устройств и браузеров.
Предусмотреть возможность добавления новых видов сотрудничества без значительной переработки страницы.

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] Доступность информации: Кнопка "Сотрудничество" должна быть легко заметна и доступна с любой страницы сайта.
- [x] Информативность: На странице сотрудничества должны быть четко изложены условия взаимодействия, включая, но не ограничиваясь, типами сотрудничества, необходимыми шагами для начала сотрудничества, контактной информацией для связи и ответами на часто задаваемые вопросы.
- [ ] Интерактивность: Предоставление формы обратной связи или контактов для непосредственного обращения, чтобы потенциальные партнеры могли легко начать диалог.
- [ ] Обратная связь: Наличие подтверждения о получении запроса на сотрудничество или автоматического сообщения с информацией о сроках рассмотрения заявки и дальнейших шагах.

Макет десктоп:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=4263-23705&mode=design&t=1A8PsRrEIYubd157-4
Макет планшет:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=4461-21366&mode=design&t=1A8PsRrEIYubd157-4
Макет Мобильная:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=4308-21277&mode=design&t=1A8PsRrEIYubd157-4
### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
на мобильной версии сайта, на айфон xs, в браузерах Сафари, Хром, Фаирфокс, картинки на странице расстянуты

https://drive.google.com/file/d/1vkCUBbyRZJwS9gTfGPez0YzaBekWRthC/view?usp=sharing

**Comment by Elizaveta-S** [comment]
Баги
1. Размеры текстов во всех заголовках не соответствует макетам, на всех версиях  
2. Заголовки находятся слева а не посередине, на таблете ФР https://take.ms/vRrHb, ОР https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=4461-21366&t=D39LjXB7iJGb2tLm-0 
3. Сначала заголовок потом текст, в макете наоборот (я бы оставила так как реализовано), на мобилке ФР https://take.ms/kzvC1, ОР https://take.ms/cb9EN

**Comment by Elizaveta-S** [comment]
1. Размеры заголовков не исправлены
2. Заголовок "Почему стоит выбрать нас" находятся слева а не посередине, на таблете ФР https://take.ms/kbzELA, ОР https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=4461-21366&t=D39LjXB7iJGb2tLm-0
