### ISSUE TITLE
(Заблокировать таймзону для ивентов) Я как создатель ивента хочу видеть только Страну и город при создании события, возможность изменения таймзоны меня сбивает.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1067]
### Предпосылки
Для сербии не нужны таймзоны. Юзеру видеть их незачем. То что для города ещё и поменять можно Это несколько странно

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] При создании оффлайн-ивента, таймзона по умолчанию ставится на сербскую (Europe/Belgrade +02:00)
- [ ] При создании оффлайн-ивента, поле выбора таймзоны неизменяемо (disabled)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
при редиректе на страницу создания ивента, в поле тайм-зона отображается слово "СЕТ", которое в последствии меняется на часовой пояс Белграда, после того, как включишь чек-бокс "Онлайн"

https://drive.google.com/file/d/1NFXdRBCOA4fkUk5d1O8nC31gEgTEikNP/view?usp=sharing

**Comment by AlexeyPQA** [comment]
Проверено на демо окружении.
