### ISSUE TITLE
Добавить кнопки "Редактировать" и "Удалить",  на странице "Мои мероприятия" внутри личного кабинета

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1068]
[](url)### Описание задачи

Desktop
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=5021-20979&t=dTAwHOdi9G9cHCr9-4
Tablet
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=5053-21240&t=dTAwHOdi9G9cHCr9-4
Mobile 
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=5053-20616&t=dTAwHOdi9G9cHCr9-4
На странице "Мои мероприятия" нужно добавить кнопки "Редактировать" и "Удалить" (формат кнопок на усмотрение дизайнера, мне (@il12) кажется что кнопки-иконки подойдут лучше чем текстовые)

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] На странице "Мои мероприятия" у ещё не начавшихся ивентов присутствует кнопка "Редактировать"
- [ ] На странице "Мои мероприятия" нажатие на кнопку "Удалить" удаляет ивент, предварительно открыв уведомление, действительно ли пользователь хочет удалить ивент?
- [ ] На странице "Мои мероприятия" нажатие на кнопку "Редактировать" открывает форму редактирования.
- [ ] Удалить можно так же уже закончившиеся ивенты
- [ ] Всплывающие окна и надписи на них соответсвуют выбранному языку
- [ ] Кнопки можно выбрать и произвести дейстие с помощью TAB
- [ ] При наведении кнопки подсвечивают зону действия и изменяют цвет иконки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- [Риски]

**Comment by ElenaArtamoshkina** [comment]
[](url)

**Comment by Dashaart2004** [comment]
https://github.com/openworld-community/ows-events/issues/1299

**Comment by toprogramm** [comment]
сделано. есть не закрытая бага указанная выше. починю в слудющем спринте
