### ISSUE TITLE
Как пользователь, я хочу видеть индикатор загрузки (Loader) на главной странице, когда мероприятия подгружаются, чтобы я мог понять, что происходит, и дождаться загрузки информации

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1069]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
