### ISSUE TITLE
(500 Ошибка) Как пользователь, когда я сталкиваюсь с 500 страницей на сайте, я хочу, чтобы мне предоставили сообщение о том, что это "неизвестная ошибка сервера", и возможные пути решения проблемы

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1070]
### Описание задачи
Создать страницу отображаемую в случае неожиданной ошибки сервера (сервер возвращает статус 500)
- Макет
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=4034-6347&mode=design&t=NrxupoqfiuzOSfCX-4 
### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Мы не можем сейчас протестировать 500 ошибку. проверять нечего, так как сложно сделать кейс чтоб она отработала и проверить все специальные кейсы.  Она есть и функционирует(я проверял у себя, как и макет соответствует). Работает эквивалентно 404-й ошибке. 

Я отправил ее на тест вместе с 404-й т.к. эту часть сложно разделить.
### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
