### ISSUE TITLE
Таски Перебрать

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1071]
- [x] Я как пользователь хочу видеть Афиша переделано с 1-3 странице поиска гугл или яндекс, чтобы быстро найти события которые проходят в Сербии и Черногории (SEO Оптимизация) <mark style="background: #BBFABBA6;">- Добавлено в бэклог </mark>
- [x] Я как пользователь хочу мочь находить мероприятия афиши в контекстной рекламе (контекстная реклама) ----------------------------
- [x] Сделать на карточках кнопку для администратора и модератора для "редактирования" и "удаления" ивента. 
	- [x] Кнопка редактирования (при нажатии удалить появляется Уведомление что вы хотите удалить и кнопка продолжить, после этого появляется окно с уведомлением "Вы действительно хотите удалить сообщение?" ) ---------------------------------------

- [x] Я хочу иметь краткую инструкцию как создавать события и пользоваться сайтом, так как я не знаю как сайт работает <mark style="background: #FFB86CA6;">- есть в бэклоге</mark>

- [x] Я как пользователь хочу иметь возможность быстро поделиться ссылкой на мероприятие в социальных сетях -  Кнопка Поделиться на странице мероприятия в конце текста для фейсбука, инстраграмма, твиттера (Х), телеграм. 

- [x]  Баг - ивенты можно искать только по полному названию

**Comment by i-salimzhanov** [comment]
(контекстная реклама) Как пользователь, я хочу иметь возможность находить мероприятия афиши в контекстной рекламе через поисковые системы, чтобы удобно получать информацию о предстоящих событиях, интересных мне, при выполнении поисковых запросов в интернете.

**Критерии приемки:**

SEO-оптимизация: Страницы мероприятий афиши должны быть оптимизированы для поисковых систем (Google, Яндекс), чтобы повысить их видимость в поисковой выдаче.
Интеграция с контекстной рекламой: При поиске информации о мероприятиях или смежных интересах, пользователь должен видеть контекстную рекламу, соответствующую его запросам, что требует тесной интеграции контента мероприятий с ключевыми словами и SEO-стратегией.
Адаптация под запросы пользователей: Контент рекламы мероприятий должен соответствовать наиболее часто используемым поисковым запросам целевой аудитории, чтобы максимально увеличить шансы на его обнаружение.
Измерение эффективности: Необходимо настроить аналитику для отслеживания эффективности SEO и контекстной рекламы, включая количество кликов, просмотров и конверсии, чтобы оценить и оптимизировать стратегию продвижения.

**Дополнительные замечания:**

Важно обеспечить согласованность между контентом рекламы и SEO-стратегией, используя анализ ключевых слов и предпочтений целевой аудитории.
Рекламные кампании должны регулярно обновляться в соответствии с изменениями в трендах поисковых запросов и интересов целевой аудитории.
Необходимо учитывать аспекты мобильной оптимизации, поскольку значительная часть поисковых запросов происходит с мобильных устройств.

**Comment by toprogramm** [comment]
закрыто выполнено перенесено в глобальный бэклог.
