### ISSUE TITLE
БАГ: Если при сохранении ивента быстро нажать пару раз на кнопку "Сохранить", то создается два идентичных ивента

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1074]
### Окружение
Тест

### Описание задачи
Если при сохранении ивента быстро нажать пару раз на кнопку "Сохранить", то создается два идентичных ивента

https://github.com/openworld-community/ows-events/assets/19169013/9d74f590-59cc-4124-9211-be3d571dd0d9

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] При быстром нажатии кнопки "Сохранить" создаётся только один ивент 

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
