### ISSUE TITLE
(Перенос кнопки) Как пользователь, я хочу, чтобы кнопка создания события была расположена в правом верхнем углу страницы, избегая проблем с браузером, и низ страницы может быть скрыт.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1080]
### Описание задачи
Как пользователь, я хочу, чтобы кнопка создания события была расположена в правом верхнем углу страницы, чтобы это соответствовало моему ожидаемому поведению интерфейса сайта и обеспечивало удобство доступа, избегая возможных проблем с расширениями браузера, которые могут перекрывать элементы в нижней части страницы.

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] Кнопка создания события должна быть видима и доступна в правом верхнем углу на всех страницах сайта, где это применимо.
- [x] На мобильных устройствах кнопка "Создать мероприятие" должна быть продублирована в бургер-меню
- [x] На мобильных устройствах кнопка "Создать мероприятие" остается в виде "зеленого плюса"
- [x] При нажатии на кнопку должен открываться интерфейс создания события без задержек и ошибок.
- [x] Расположение кнопки не должно конфликтовать с другими элементами интерфейса и должно быть интуитивно понятным для новых пользователей.
- [x] Должны быть проведены тесты с использованием наиболее распространенных расширений браузеров, чтобы убедиться, что кнопка остается доступной и видимой.

#### Ценность:
Перемещение кнопки создания события в правый верхний угол улучшит пользовательский опыт, повысит удобство использования сайта и может привести к увеличению количества создаваемых событий, поскольку пользователи будут чувствовать себя более комфортно и менее склонны к прерыванию из-за интерфейсных неудобств.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
