### ISSUE TITLE
(БАГ Скролл) Скролл становится черным при наведении на него. Видно на выборе города при создании ивента

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1085]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Сделать выделение чуть менее ярким чтобы было видно скролл

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
