### ISSUE TITLE
(Подсказки валидации на странице регистрации)Как пользователь, я хочу видеть немедленное оповещение о некорректном вводе email или несовпадении паролей при регистрации, чтобы исправить ошибки и зарегистрироваться.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1086]
### Описание задачи
(Подсказки валидации на странице регистрации)Как пользователь, я хочу видеть немедленное оповещение о некорректном вводе email или несовпадении паролей при регистрации, чтобы исправить ошибки и зарегистрироваться.

### Критерии приемки

- [ ] Если email введен не верно , появляется подсказка "Введите действительный адрес электронной почты" - текст обсуждаем.
- [ ] Если пароли не совпадают появляется подсказка "Пароли не совпадают" - текст обсуждаем.
- [ ] Соответствует дизайну
    - [ ] Цвета подсказок в красном спектре (хорошо видимые)
    - [ ] Всплывающее окно / подсказка снизу или сбоку инпута - обсуждаемо. 

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
ошибка при вводе емейла сразу же не отображается, так же как и не отображается ошибка при вводе разных паролей
https://drive.google.com/file/d/1ORUEgDFBGbRwoZ0TXOUPPloedxkFl2Kj/view?usp=sharing
