### ISSUE TITLE
Тестовая

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1092]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
тестовая. закрыто
