### ISSUE TITLE
Создать удобную и логическую навигацию по сайту

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1094]
### Описание задачи
1. При нажатии личный кабинет предлагает авторизоваться, но после авторизации вместо личного кабинета юзер попадает на главную
2. При нажатии на главной странице кнопки 'создать объявление' предлагает авторизоваться, но после авторизации вместо создания иаента юзер попадает на главную
3. При выходе из аккаунта перекидывает не на главную, а на страницу авторизации (на которой неочевидно куда можно пойти, есть только крестик, по нажатию которого неизвестно что произойдет)

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] При навгации на защищенную страницу неавторизованного юзера (как при вводе  url в адресную строку так и при навигации по линкам сайта) юзера сначала перекидывает на автоизацию а после - на ту страницу на которую хотел юзер
- [ ] Дополнительно: user/profile доступна только для авторизованного (была доступна всем но выскакивала 500 вроде)
- [ ] Дополнительно - на странице мои объявления при отсутствии моих объявлений кнопка logout раюботает (закрывалась друшгим элементом и не срабатывала)
- [ ] при logout - переход на главную (был на авторизацию) - обсуждается, если как раньше лучше - верну как раньше

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
