### ISSUE TITLE
Создать layout для всех (большинства страниц)  и вынести туда header и footer

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1095]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] хэдер и футер отображаются как и раньше, новых багов по сравнению с demo нет

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
