### ISSUE TITLE
Create wrapper for NuxtLink with localePath

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1097]
### Описание задачи
LocalePath используется вместе с NuxtLink, чтобы не импортировать его каждый раз создать wrapper NuxtLinkWithLocalePath. И заменить NuxtLink этим wrapper везде где используется NuxtLink вместе с localePath

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by il12** [comment]
Если я правильно понял идею, возможно проще будет использовать этот компонент из библиотеки локализации
https://i18n.nuxtjs.org/docs/api/components#nuxtlinklocale
