### ISSUE TITLE
Поведение после авторизации - то куда осущкствляется переход после того как юзер авторизовался

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1099]
-после авторизации если была нажата кнопка profile - возвращаемся на ту же страницу где и были до авторизации
- если при нажаьтт любой кнопки Создать ивент необходима авторизация - то после авторизации попадаем на страницу создания ивента

**Comment by i-salimzhanov** [comment]
Я как пользователь хочу после авторизации возвращаться на ту страницу, с которой перешёл на страницу авторизации.
Сейчас после авторизации я всегда попадаю в личный кабинет.

**Comment by Sinamon-maker** [comment]
не хватает описания поведения при нажатии кнопки Создать событие

**Comment by i-salimzhanov** [comment]
предлагаю следущий путь:
открытие главной страницы
нажатие кнопки создать мероприятие
переход на страницу авторизации / регистрации пользователя
возврат на главную страницу
нажатие кнопки создать мероприятия
перенаправление на страницу создания мероприятия

создание мероприятия из личного кабинета:
Открытие главной страницы
Нажатие кнопки авторизоваться
переход на страницу авторизации / регистрации пользователя
возврат на главную страницу
Нажатие кнопки Пользователь
нажатие кнопки создать мероприятия
перенаправление на страницу создания мероприятия
