### ISSUE TITLE
(Валидация Дробная Цена) Как пользователь я хочу вводить дробную цену например $3,5 так как это важная часть моей культуры

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1108]
### Описание задачи
Сделать возможным ввод в поле цена дробного значения (в формате десятичной дроби с двумя разрядами после запятой)

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] При создании и редактировании ивента в поле цена можно ввести число с дробной частью 
### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by Dashaart2004** [comment]
https://github.com/openworld-community/ows-events/issues/1218
