### ISSUE TITLE
На странице event/id и create-id при невалидном id  заменить back to main на throwError и кинуть 404 (разкомментить)

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1111]
### Описание задачи
при невадидном id перекидывать на 404 через throw Error, back tp main убрать

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] При невалидном id перекидвает на 404 - not found

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
