### ISSUE TITLE
Картинка при создании ивента - изменить размер

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1112]
### Описание задачи
Изменить размер картинки на странице создания объявления - сделать больше и сделать соотношение сторон как на шлавной чтобы юзер видел как картинка располагается внутри предлагаемых соотношений сторон и мог поменять или отредактировать и вставить новую

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
