### ISSUE TITLE
Доработать отображения поиска на главной странице

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1114]
### Описание задачи
Изменить логику отображения облака тегов.
По дефолту облако тегов не показывается.
Есть кнопка "Показать теги"
По нажатию на неё теги показываются, надпись на кнопке меняется на надпись "Скрыть теги"
По повторному нажатию тэги скрываются.
Дизайн и текст на кнопках доработать

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] По дефолту облако тегов не показывается.
- [x] Есть кнопка "Показать теги"
- [x] По нажатию на неё теги показываются, надпись на кнопке меняется на надпись "Скрыть теги"
- [x] По повторному нажатию тэги скрываются.
- [x] Поле поиска не показывается на главной странице

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
макеты 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=4695-23727&mode=design&t=Cp58hZV1V2toGYaV-4 - десктоп 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=3638-59102&mode=design&t=qjolY9FfFJTddGOo-4 - мобилка
