### ISSUE TITLE
Mobile resolution user/profile - press back on header return to main not user page - fix it

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1119]
### Описание задачи
На мобильном разрешении кнопка назад на user/profile page сработывает на главную в не на user page

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] На мобильном разрешении кнопка назад на user/profile page возвращает на user page - в личный кабинет с выбором меню

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
