### ISSUE TITLE
Invalid data в поле Календаря при загрузке страницы DONE remove task

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1138]
### Описание задачи
Invalid data в поле Календаря при загрузке страницы

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
пофикшено - не актуально
