### ISSUE TITLE
Добавить продуктовые метрики (BigQuery/Google Аналитика) по конкретным критериям

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1140]
### Описание задачи
7 дней и 28 дней для активных пользователей, количество регистраций пользователей, созданий мероприятий и т.п.

Какие метрики вижу я на первый этап: 1.Конверсия пользователя на сайте (просто посещение) в разрезе день, месяц, квартал, год. 
- Конверсия регистраций аккаунтов.
- Конверсия создания ивентов (так же по определенным срокам)
- Отслеживание того, какие страны и города сколько ищут ивенты, а так же в каких странах и городах сколько создают ивенты.
- Количество добавлений в избранное любых ивентов.
- Количество открытий карточек ивента, а не просто просмотр главной страницы.

Переход на страницу каждого ивента (количество - для получения популярных)
Группировка ивентов по создателю (сколько было создано, чтобы потом можно было отдать человеку статистику)
Количество переходов по кнопке связаться (измерние активности)
Статистика по нахождению на конкретной странице (время/ тип страницы)
Создание ивента(где в основном происходит личный кабинет/кнопка в хедере/кнопка внизу)

У нас метрики собиряются с помощью gtag путем добавления ивентов и ипараметров в код (не с помошью tag assistant - это метод где настройки событий осуществляются в самой аналитике, нет необходимости задействовать девелоперов - это отличие gtag и tag manager)

Существующие метрики (collect automatically by gtag) и параметры которыe собираются (https://support.google.com/analytics/answer/9216061?hl=en&ref_topic=13367566&sjid=16679869983330832348-EU):
- user_engegement - the amount of time someone spends with your web page in focus or app screen in the foreground
- page_view - each time the page loads or the browser history state is changed by the active site. This event is collected 
      automatically. You cannot turn off collection. Main page with different query counts as different page_views (see page _referer)
              parameters: page_location (page URL), page_referrer (previous page URL) - automatically, page_title - custom
- scroll -  the first time a user reaches the bottom of each page, no parameters
- click - each time a user clicks a link that leads away from the current domain
       parameters - link_classes, link_domain, link_id, link_url, outbound (boolean)
- view_search_results - By default, the event is triggered based on the presence of one of the following 5 query parameters in 
        the URL: , q, s, search, query, keyword. You can optionally configure this event to look for other URL query parameters (добавлено как custom event поскольку не обнаружено в списке событий в аналитике при попвтке менять query).
-  form_start  - the first time a user interacts with a form in a session, You can only use the parameters in your reports if you [create custom dimensions](https://support.google.com/analytics/answer/10075209) for them.
- form_submit - when the user submits a form, You can only use the parameters in your reports if you [create custom dimensions](https://support.google.com/analytics/answer/10075209) for them.

Добавлены следующие custom события:
 1. view_search_results ({search_term (url после ?), city, tags})
 2. try_login({method: Google/Telegram}) - нажатие на соответствующие кнопки
 3. add_favourites({id_event, id_user, city, country, online})
 4. form_event(id_event, id_user, city, country, online)
 5. redirect to event url({link_url, id_event, city, country, online}) - redirect как с шлавной так и с личного кабинета (было заведено но без параметров) -  стоит ли creator_Id сюда лобавить?

### Критерии приемки
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by i-salimzhanov** [comment]
Возможность выгружать данные из Google Analytics 4 (GA4) в BigQuery по заданным параметрам существует. 

В GA4 интеграция с BigQuery предоставляет возможность экспортировать сырые данные о пользовательских событиях, что позволяет проводить более глубокий анализ и настраивать отчеты по конкретным требованиям. Для выгрузки данных по мероприятиям, размещенным определенным пользователем-организатором, используется следующий подход:

1. **Идентификация событий**: Убедитесь, что каждое мероприятие имеет уникальные идентификаторы или метки, которые могут быть связаны с определенным организатором. Это могут быть специальные параметры события в GA4.

2. **Настройка и фильтрация в BigQuery**: После того как данные попадут в BigQuery, вы можете использовать SQL-запросы для извлечения данных по нужным параметрам. Например, если у вас есть атрибут `organizer_id` для каждого события, вы можете написать запрос, который будет извлекать данные только для этого организатора.

3. **Регулярная выгрузка**: В BigQuery вы можете настроить регулярное обновление данных, чтобы организаторы могли получать актуальную информацию о своих мероприятиях.

4. **Обеспечение безопасности и конфиденциальности**: При работе с данными пользователей важно учитывать аспекты безопасности и конфиденциальности данных. Удостоверьтесь, что выгрузка данных ограничивается только теми данными, доступ к которым разрешен.

Для начала работы с BigQuery требуется настроить экспорт данных из GA4 в BigQuery через интерфейс GA4, где выбираете соответствующий проект и датасет в Google Cloud. После этого, начнется выгрузка данных, которую затем можно настроить под конкретные нужды анализа. 

Такой подход позволит предоставлять организаторам мероприятий персонализированную информацию о посещаемости их мероприятий.

 Предположим, что у вас есть таблица events, которая содержит следующие столбцы: event_id, event_name, organizer_id, event_date, и attendees_count. Ваш запрос для извлечения данных о мероприятиях, организованных пользователем с organizer_id равным 123, мог бы выглядеть следующим образом:

```
SELECT event_id, 
       event_name, 
       event_date, 
       attendees_count
FROM `your_dataset.events`
WHERE organizer_id = '123'
ORDER BY event_date DESC;
```

В этом запросе:

SELECT определяет, какие столбцы данных вы хотите получить (в данном случае event_id, event_name, event_date, и attendees_count).
FROM указывает на имя вашей таблицы данных, в которой хранится информация о мероприятиях (your_dataset.events представляет собой имя датасета и таблицы).
WHERE задаёт условие для фильтрации записей, чтобы выбрать только те, что соответствуют конкретному organizer_id.
ORDER BY event_date DESC сортирует результаты по дате мероприятия в обратном порядке (от самых новых к старым).
Этот запрос позволит получить список всех мероприятий, организованных пользователем с organizer_id равным 123, вместе с количеством посетителей на каждое мероприятие и датами проведения мероприятий.
