### ISSUE TITLE
Edit page titles in meta tag

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1163]
### Описание задачи
Check all titles and description (about 160 characters) meta tags on all pages and change if not suited to current page content and add new for the new pages:
- **main page**: 
      title: Events Calendar for Serbia and Montenegro / Афиша мероприятий Сербии, Черногории
      description:  The catalog features dozens of events across various categories: concerts, meetings, exhibitions, festivals, masterclasses / В каталоге представлены десятки мероприятий по различным направлениям: концерты, встречи, выставки, фестивали, мастер-классы
- **event-id**: 
     title: event's title (restriction - max 50)
     description: Classic format, industrial and entertaining talks, networking, activities, and a focus on the community. /  В каталоге представлены десятки мероприятий по различным направлениям: концерты, встречи, выставки, фестивали, мастер-классы
- **abou**t: 
     title: About Peredelano Afisha Project / О проекте Peredelano Афиша
     description:  Learn more about our project, team and mission / Узнайте больше о нашем проекте, команде и миссии
- **donate**: 
     title: Support the Peredelano Afisha Project / Поддержать проект  Peredelano Афиша
     description: Thanks to your support, we are expanding the project, enhancing its capabilities, and bringing our boldest ideas to life. /  Благодаря вашей помощи мы развиваемся, расширяем возможности проекта и реализуем наши самые смелые идеи
- **user**: 
       title: User Profile / Личный кабинет
       description: Manage your profile and events in your personal account / Управляйте Вашим профилем и мероприятиями в личном кабинете

Эти страницы новые или относительно новые, для них не придумали title еще (поэтому автоматом берется title от главной - Events Calendar for Serbia and Montenegro):
- **auth**: (раньше была оьъединена со страницей User Profile) 
       title: Authorization in Peredelano  Afisha  / Авторизация в Peredelano Афиша
       description: Authorize in Peredelano Afisha to create, manage events / Авторизуйтесь в Peredelano Афиша чтобы создавать,  управлять мероприятиями
- **support**: (new page)
          title: Peredelano  Afisha Technical Support  /  Служба технической поддержки Peredelano Афиша,
          description: If you have any question - we always ready to help / Если у вас есть вопросы - вы всегда можете обратиться за помощью
- **collaboration**: new page():
        title:  Collaboration with  Peredelano Afisha  / Сотрудничество с проектом  Peredelano Афиша
        description:  Our startup unites the cultural and social space of the Balkans, offering a convenient platform for discovering and organizing events. Join us and explore new opportunities! / Наш стартап объединяет культурное и общественное пространство Балкан, предлагая удобную платформу для поиска и организации мероприятий. Присоединяйтесь к нам и откройте новые возможности!
- **event/edit-id**: (страница создания ивента, не заводили отдельный title )
        title:  Create new Event / Создание новгого мероприятия
        description:  Create new Event /  Создание новгого мероприятия

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] При наведении мышкой на вкладку браузера высвечивается title соотвктствующей страницы, с учетом выбранного языка страницы
- [ ] (необязательно) description видно при поиске страницы в гугл при заданиее оответствующих слов поиска, можно попробовать реально ли найти тест а не прод и увидеть описание

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
- main page: Events in Serbia and Montenegro,
- donate: Donate to Peredelano Afisha Project
- auth: Authorization Page
- support: Technical Support
- collaboration: Collaborate with Afisha Peredelano
- event/edit-id: Create new Event (не уверен нужно ли его в общую пихать)

**Comment by Elizaveta-S** [comment]
Баги по задаче описала в таблице https://docs.google.com/spreadsheets/d/1_q4VJT0x9oYbaoBDqpg03jxNdrT-0I61F0OuEVJPRvo/edit?pli=1#gid=1613863115

**Comment by Elizaveta-S** [comment]
Баг-фиксы протестированы, все баги закрыты
