### ISSUE TITLE
Провести нагрузочное тестирование

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1199]
### Описание
Опишите задачу

### Критерии приёмки
- *Критерии приёмки*

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Dashaart2004** [comment]
Первый набор данных:
Время выполнения: 00:00:14 (14 секунд)
Общее количество запросов: 1
Средняя частота запросов: 0.1 в секунду
Среднее время ответа: 9393 мс
Минимальное время ответа: 9393 мс
Максимальное время ответа: 9393 мс
Ошибок: 0
Количество активных запросов: 7
Количество начатых запросов: 7
Количество завершенных запросов: 0<br/><br/>2. Второй набор данных:
Время выполнения: 00:00:27 (27 секунд)
Общее количество запросов: 103
Средняя частота запросов: 3.8 в секунду
Среднее время ответа: 563 мс
Минимальное время ответа: 56 мс
Максимальное время ответа: 12802 мс
Ошибок: 0
Количество активных запросов: 1
Количество начатых запросов: 21
Количество завершенных запросов: 203. Итоговые данные:
Общее количество запросов: 250
Средняя частота запросов: 2.5 в секунду
Среднее время ответа: 468 мс
Минимальное время ответа: 42 мс
Максимальное время ответа: 12802 мс
Ошибок: 0<br/><br/>Исходя из этих данных, можно сделать вывод, что в тесте отсутствуют ошибки (Err: 0) и производительность приложения в целом стабильна. Среднее время ответа и частота запросов также находятся на приемлемом уровне. Однако, стоит обратить внимание на случаи с максимальными значениями времени ответа. Возможно, имеет смысл более детально исследовать причины таких отклонений.
