### ISSUE TITLE
Создание отдельных страниц в соответствии с городом (переделывается)

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1225]
### Описание
Необходимо создать странички под каждый отдельный город, где будет меняться заголовок для оптимизации поиска в гугл.

### Критерии приёмки
- Созданы странички под каждый город, в соответствии с списком городов из БД
- На каждой отдельной странице меняется заголовок в соответствии с городом, конкретные заголовки в разработке (Афиша мероприятий в "Город" см. подзадачу #1266 )
- разработать meta title and meta description
- Отдельные странички имеют такой же функционал, как главная страничка
- На этих страничках можно выбрать другой город, в таком случае пользователь попадет на страничку другого города с заголовком, который соответствует другому городу
- При переходе на страницу города выбранные дата и тэги сбрасываются

### Дополнительная информация
Подзадачи:
#1266 

### Ссылки на баги, относящиеся к этой задаче
> [!CAUTION] 
> *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Baidak-Evgenii** [comment]
Проверено 20.09.24 в окружениях:
- Chrome Версия 128.0.6613.13, разрешения экрана: 1920*1080, 768*1701, 375*1932
- Opera Версия 113.0.5230.26, разрешения экрана: 1920*1080, 768*1701, 375*1932
- browserstack Safari 18, разрешения экрана: 1536*738

ОШИБОК НЕ ОБНОРУЖЕНО.
