### ISSUE TITLE
Уменьшить вертикальное расстояние на странице About  - слишком много лишнего пространства

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1249]
также на десктопе текст выровнять как в фигме - по середине по отношению к картинке а не по верхнему краю

**Comment by i-salimzhanov** [comment]
Убрать знаки препинания в конце списка на приложенных скриншотах.

![Image](https://github.com/openworld-community/ows-events/assets/146735283/a26d484c-23c6-4ce5-a6de-8490ef868fe4)
![Image](https://github.com/openworld-community/ows-events/assets/146735283/fc1c4bfa-c888-4ac7-95dc-69fd2b3c19eb)
