### ISSUE TITLE
Перевод Стран и Городов на Русский и Английский

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1263]
### Описание
При отображении Страны или Города они должны быть написаны на русском или английском в зависимости от выбранного языка
При выборе города на главной в фильтр попадает англ версия (в поисковую строку url)
Города на странице создания/редактирования отсортированы по алфавиту

### Критерии приёмки
- Проверка корректности отображения Названия городов/стран на страницах (в соответствии с выбранным языком) :
 - Главная
 - Ивент
 - Создание/Редактирования Ивента
 - Города на странице создания/редактирования отсортированы по алфавиту
 - При выборе страны валюта подтяшивается в соответствии со страной (можно поменять потом, но при смене страны для Черногории евро и для Сербии rsd)
- Хотя бы по основным городам следует проверить правописание городов (как в гугле)
- Попросить список городов на проверку у Игоря Бэка
- 

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by il12** [comment]
Список городов:

[citiesTranslationList.csv](https://github.com/user-attachments/files/16411092/citiesTranslationList.csv)

**Comment by toprogramm** [comment]
Поправленный с городами из гугла. Какие то города почему то не нашлись в Google Geocoding Api в общем только проверить и вперед) можно внедрять

[citiesTranslationList.csv](https://github.com/user-attachments/files/16447805/citiesTranslationList.csv)

**Comment by Dashaart2004** [comment]
Отчет о тестировании  : 1.Поиск городов на английском в гугл картах
2.Проверка правильного расположения(Черногория\Сербия) городов
3.Поиск городов на русском в гугл картах
4.Поиск названия на русском(при необходимости)
Примечание: 
1.В 5 колонке написаны найденные из тех что не найдено в 4 колонке
2.Также в 5 колонке написаны названия в том случае если по названию из 4 колонки не найти 
https://docs.google.com/spreadsheets/d/1ttFh3oYNzx3OcGmgc-FCnhzd6gPwUKBWYXuMSHGhpC8/edit?usp=sharing

**Comment by il12** [comment]
[service_cities_22-08-24.json](https://github.com/user-attachments/files/16708616/service_cities_22-08-24.json)
