### ISSUE TITLE
Доработка странички СТРАНЫ для семантического ядра

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1265]
### Описание
Добавить Заголовки, Метатеги, Микроразметку на ГЛАВНУЮ
### Критерии приёмки:
1) Страна Сербия
- Пользователь видит следующие заголовки: H1 с надписью "Афиша Сербия"+ слоган под заголовком, H2, который находится под карточками мероприятий слева с надписью "Мероприятия Сербия" H2 заголовок карточек мероприятий 
- Пользователь видит мероприятия, которые проходят в стране Сербия
- В поле "страна" предвыбрана страна Сербия, пользователь может поменять страну по желанию
- Пользователь в списке городов может выбрать только 1 город из списка, который относится к Сербии
- Когда пользователь выбирает город, то он попадает на страничку с этим городом
- Соответствие Метатегов, нужен список
- Соответствие Тайтла - Афиша Сербия
- Соответсвие макету
- Микроразметка, нужен список - пока под вопросом

2) Страна Черногория
- Пользователь видит следующие заголовки: H1 с надписью "Афиша Черногория"+ слоган под заголовком, H2, который находится под карточками мероприятий слева с надписью "Мероприятия Черногория" H2 заголовок карточек мероприятий 
- Пользователь видит мероприятия, которые проходят в стране Черногория
- В поле "страна" предвыбрана страна Черногория
- Пользователь в списке городов может выбрать только 1 город из списка, который относится к Черногории
- Когда пользователь выбирает город, то он попадает на страничку с этим городом
- Соответствие Метатегов, нужен список
- Соответствие Тайтла - Афиша Черногория
- Соответсвие макету
- Микроразметка, нужен список - пока под вопросом

**На странице должна быть CTA-кнопка (плюсик) создания мероприятия**
**На странице (мобильное разрешение) должен быть футер**

### Дополнительная информация
Макет в фигме
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=6767-19898&t=HJAFylouM83T8GdL-4

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Egor-ScrumMaster** [comment]
Не тестируем заголовки, пока не будет доработка

**Comment by Baidak-Evgenii** [comment]
Заведен баг (не соответствует макету)  https://github.com/orgs/openworld-community/projects/6/views/36?pane=issue&itemId=79839239
