### ISSUE TITLE
Доработка странички ГОРОДОВ для семантического ядра

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1266]
### Описание
Доработать страничку с всеми заголовками, метатегами, тайтлами и микроразметкой
### Критерии приёмки
- Пользователь видит следующие заголовки: H1 с надписью "Афиша ГОРОД"+ слоган под заголовком, H2, который находится под карточками мероприятий слева с надписью "Мероприятия ГОРОД" H3 заголовок карточек мероприятий 
- Пользователь видит мероприятия, которые проходят в выбранном городе
- Пользователь в списке городов (фильтре) видит выбранный город и может его поменять
- Соответствие Метатегов, нужен список
- Соответствие Тайтла "Афиша ГОРОД"
- Соответствие макету

Неактуально на даннный момент
- В поле "страна" предвыбрана страна Сербия
- Микроразметка, нужен список - пока под вопросом

**На странице должна быть CTA-кнопка (плюсик) создания мероприятия**
**На странице (мобильное разрешение) должен быть футер**

### Дополнительная информация
Макет в фигме
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=6777-65347&t=HJAFylouM83T8GdL-4
#1301 

Тайтл:
- Афиша ГОРОД
### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Egor-ScrumMaster** [comment]
Не тестируем заголовки, пока не будет доработка

**Comment by Baidak-Evgenii** [comment]
Данная таска подзадача таски #1225 (https://github.com/orgs/openworld-community/projects/6/views/59?pane=issue&itemId=69036475), которая в смою очередь была проверена 20.09.24 - ошибок не обнаружено
