### ISSUE TITLE
СРОЧНО картинка в meta/utils должна меняться в зависимости от языка

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1269]
### Описание
Опишите задачу

https://api.afisha.peredelano.com/image/url-image.png 
это картинка которая используется в meta как default image - на ней надпись по русски

### Критерии приёмки
-на англ версии сайта не должно быть надписи на русском

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by ElenaArtamoshkina** [comment]
Дизайн - https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=7069-25589&t=w43sPU41SkPqr5Qv-4
