### ISSUE TITLE
Передача Времени проведения мероприятия в ISO

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1273]
### Описание
У нас таймзоны сейчас передаются не совсем корректно, формат данных привожу ниже в скриншотах.
линк прикреплю если что позже. 

- Рекомендации от гугла 
![Image](https://github.com/user-attachments/assets/e0bfb4a5-adc3-4bb6-afb4-5ff752262127)
- Видел вот два таких варинта в афишах
![Image](https://github.com/user-attachments/assets/ef5f3456-378b-4b06-b863-0a5753347a88)
![Image](https://github.com/user-attachments/assets/0533280d-7c1d-4d84-a3e3-b14dec13224c)

### Критерии приёмки
- *Критерии приёмки*

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Sinamon-maker** [comment]
https://developers.google.com/search/docs/appearance/structured-data/event?hl=ru#date-time-best-guidelines
