### ISSUE TITLE
Покрасить Кнопку Избранное на странице ивента в Зеленый цвет, когда ивент добавлен в избранное.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1278]
### Описание
Описано заголовком картинка ниже 

![Image](https://github.com/user-attachments/assets/89122eb5-97c3-45a9-8e1a-35976c947a70)

### Критерии приёмки
- [x] Сделан Дизайн
- [ ] Кнопка - зеленая и соответствует макету (код)

#### Поведение 

отжатый лайк - серая обводка
отжатый лайк ховер - серое сердце / зеленая ободка
активный лак - зеленое сердце
активный лайк ховер - серое сердце

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by ElenaArtamoshkina** [comment]
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=5049-20595&t=IxpYPSXEHnEChz2q-4
