### ISSUE TITLE
Создание микроразметки на страницах городов

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1301]
### Описание
Добавить микроразметку согласно ссылкам в комментарии, в head добавить тэг script содержащий ld-json

### Критерии приёмки
- в head есть тэг script содержащий ld-json

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной
#1174 

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Sinamon-maker** [comment]
https://developers.google.com/search/docs/appearance/structured-data/carousel?hl=ru
схема для обзорных страниц, тип event не поддерживается

**Comment by Sinamon-maker** [comment]
https://schema.org/ListItem

ссылка на  schema org где пример в виде микроразметки

**Comment by Sinamon-maker** [comment]
![Image](https://github.com/user-attachments/assets/d5553ee8-6bf4-4183-baa0-ed4b15c841ef)

**Comment by Sinamon-maker** [comment]
https://search.google.com/test/rich-results?hl=ru
проверка (уже на тест или demo)

**Comment by Sinamon-maker** [comment]
на сайте гугла и на сайте схема орг json немного отличается, ждать когда будет на test или demo
