### ISSUE TITLE
Глобальные стили для страницы "Поддержка" согласно фигме

### ISSUE THREAD

**Issue by safonovvvv** [openworld-community/ows-events#1321]
### Описание
Заменить стили на глобальные, для страницы "Поддержка", согласно таблицы в фигме.

### Критерии приёмки
1. Соответствие дизайну в фигме (ссылка ниже)
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=4501-22838&t=lstPZIpUIJOMwxon-0
Ссылка на таблицу : https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=1-17019&t=0xRFrGRZxxHF9MOx-0
2. Удалены старые стили

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Baidak-Evgenii** [comment]
Заведен баг https://github.com/orgs/openworld-community/projects/6/views/36?filterQuery=assignee%3A%22Baidak-Evgenii%22&pane=issue&itemId=79707722 #

**Comment by Baidak-Evgenii** [comment]
На 26.09.24 остались не пофикшены следюющие бари из задачи #1379 :
