### ISSUE TITLE
Отсутствуют отступы на главной странице у заголовков на мобильном разрешении

### ISSUE THREAD

**Issue by Dashaart2004** [openworld-community/ows-events#1324]
### Критичность
S4

### Описание
Заголовки h2 АФИША ЧЕРНОГОРИЯ | АФИША СЕРБИЯ

### Ожидаемое поведение
Положение всех элементов интерфейса соответствуют макету 
ссылка на макет https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3638-59102&t=WAsWFI5dxKoELY1w-0

### Условия воспроизведение
- Device [e.g. iPhone6]
- OS: [e.g.]

### Шаги воспроизведения
1.Перейти на сайт  https://test.afisha.peredelano.com/ru/
2.Включить мобильное разрешение 

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
https://drive.google.com/file/d/1LdCUtw79aOdOxs5ThIX0g2Itb6rTvMuX/view?usp=sharing

**Comment by toprogramm** [comment]
@Sinamon-maker пж ветку прицепи сюда и закрой)
