### ISSUE TITLE
Показываются тэги всех ивентов, а не только будущих

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1353]
### Критичность
Укажите уровень критичности

### Описание
На всех страницах при отображении списка тэгов показываются тэги всех ивентов, а не только будущих

### Ожидаемое поведение
На всех страницах при отображении списка тэгов показываются тэги только будущих ивентов

### Условия воспроизведение
- Device [e.g. iPhone6, Desktop]
- OS: [e.g. iOS, Windows]

### Шаги воспроизведения
1. Зайти на главную страницу/страницы стран или городов
2. Нажать на кнопку категории.
3. Увидеть список тэгов, в том числе прошедших мероприятий

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
- **Ссылки на скриншоты или картинки**
![image](https://github.com/user-attachments/assets/cd4b7267-ee8c-40a0-b252-135d7ef7c1f2)

### Дополнительная информация* (необязательное)
Баг пофикшен в прикрепленной к таске ветке

**Comment by zhadetskaya-olga** [comment]
Заблокирована задачей 1392
