### ISSUE TITLE
Доработка размера заголовков на страницах Главная,Страны,Города в соответствии с дизайном

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1358]
### Описание
Изменить заголовки, дизайн таска 
https://github.com/orgs/openworld-community/projects/6/views/58?pane=issue&itemId=72257411 

### Критерии приёмки
- размер соответсвует дизайну

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by Baidak-Evgenii** [comment]
Данная задяча является дублем? задачи [#1268](https://github.com/openworld-community/ows-events/issues/1268) по результатам проверки которой, в свою очередь заведена задача [1381](https://github.com/orgs/openworld-community/projects/6/views/59?filterQuery=baid&pane=issue&itemId=79839239) с выявленными багами
