### ISSUE TITLE
В файлах локализации поправить ключи

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#136]
Прописать снейк-кейсом, чтобы не писать ключи в кавычках

<img width="358" alt="Снимок экрана 2023-05-24 в 23 07 09" src="https://github.com/openworld-community/ows-events/assets/124285205/cbc2dfe2-9882-4d3c-bfc4-af9c05877d00">

Еще желательно раздробить на разные файлы, пока база не разрослась: один файл соответствует компоненту

**Comment by HugeLetters** [comment]
> 

Ключи переделаю, оке.

Касаемо разбиения - такие планы были и я обсуждал с @orby-tech , что можно было бы этим заняться. Он сказал, что пока не в приоритете.

**Comment by bigKingPenguin** [comment]
окей, тогда позже. Запиши пожалуйста куда-нибудь
