### ISSUE TITLE
Глобальные стили - главная (страны и города) карточка и инфо на ивенте

### ISSUE THREAD

**Issue by Sinamon-maker** [openworld-community/ows-events#1360]
### Описание
Глобальные стили - главная (страны и города) карточка и инфо на самом ивенте (location, price, date)

### Критерии приёмки
-  на главной, страны и города карточка ивента и инфо на странице ивенте (location, price, date) - совпадает с фигмой 

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by zhadetskaya-olga** [comment]
отсутствует пиктограмма купюры на карточке ивента на главной и страницах городов\стран. вместо нее пиктограмма доллара.
