### ISSUE TITLE
Добавить отображение года и таймзоны в дату мероприятия на странице мероприятия

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#1392]
### Описание
Добавить отображение года и таймзоны в даты мероприятия внутри страницы(карточке) мероприятия. На карточке мероприятия (на главной) год добавлять не надо
Приведены примеры онлайна, ниже приведены текстом форматы для офлайна
Логика отображения года должна быть следующая: показываем год только в том случае, если он отличен от текущего.

### Критерии приёмки
- На странице мероприятия отображается полные даты (со временем и таймзоной) начала и конца (при необходимости) мероприятия
- Пользователь видит год проведения ивента только в том случае, если он отличен от текущего.
- Таймзона отображается только на онлайн ивентах

ВАЖНО! Новые условия по доработке задачи:
Необходимо разнести даты и время на разные строки, как это будет выглядеть привожу снизу. 

Изменения формата дат следующим образом:
- Офлайн: 
24 августа 2024 
в 10:00 (или 10:00-19:00, если есть начало и конец)
- Офлайн период:
*Период в одном и том же году: 
24 авг. - 30 ноя. 2024 
в 10:00 (или 10:00-19:00, если есть начало и конец)
*Период с началом и концом в разных годах:
24 авг. 2024 - 30 ноя. 2025 
в 10:00 (или 10:00-19:00, если есть начало и конец)

- Онлайн: 
24 августа 2024 
в 10:00 (GMT+12) (или 10:00-19:00 (GMT+12), если есть начало и конец)
- Онлайн период: 
*Период в одном и том же году:
24 авг.  - 30 ноя. 2024 
в 10:00 (GMT+12) (или 10:00-19:00 (GMT+12), если есть начало и конец)
*Период с началом и концом в разных годах:
24 авг. 2024  - 30 ноя. 2025 
в 10:00 (GMT+12) (или 10:00-19:00 (GMT+12), если есть начало и конец)

### Дополнительная информация
- Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by toprogramm** [comment]
скинул предложку даты ![Image](https://github.com/user-attachments/assets/0dd0dbd2-9897-48ce-9fa1-e419f1ffe3a9)
