### ISSUE TITLE
Я, как пользователь, хочу увидеть информацию о функционале создания ивентов, что бы узнать, что я могу это сделать.

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1401]
### Описание
Задача для разработки. Необходимо добавить банер в карточку ивента, в котором будет информация о том, что пользователь может сам создать ивент, а другие пользователи смогут найти мероприятия такого типа. Версия 1.0

### Критерии приёмки
- Соответствует дизайну:
мобилка https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=7673-8560&t=WxxKF1h8O7iuQ5pQ-4
дектоп https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=399-26682&t=WxxKF1h8O7iuQ5pQ-4
таблет https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup
- На баннере Подробнее" отрисовано, но скрыто.
- У баннера нет функциональности кликабельности, он просто информационный.

### Дополнительная информация
Добавьте информацию о User Story которую вы считаете важной

### Ссылки на дочерние задачи и задачи-баги
- [!NOTE] *Дочерняя задача*

### Оценка
Оцените User Story в сторипоинтах

**Comment by zhadetskaya-olga** [comment]
https://github.com/openworld-community/ows-events/issues/1518 - баг на баннере
