### ISSUE TITLE
Расширить количество символов в Описании и Заголовке  ивента

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1415]
### Описание
Разрешенное количество символов в Заголовке - 90
разреешнное Количество символов в Описании - 1500

### Критерии приёмки
- Разрешенное количество символов в Заголовке - 90
- Разреешнное Количество символов в Описании - 1500

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by zhadetskaya-olga** [comment]
сообщения об ошибках: "Длина должна быть не более 90 символов" - для поля "Название"
"Длина должна быть не более 1500 символов" - для поля "Описание"
