### ISSUE TITLE
Доработка кнопки назад в карточке ивента на мобилке (удалить её) Дизайн готов, ссылка на макет в коммент

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1423]
### Описание
Убрать кнопку назад в карточке ивента. кнопка назад в ЛК остаётся.
Можно сначала изменить в разработке, потом актуализировать на макете.

### Критерии приёмки
- Кнопки назад в карточке ивента нет, есть лого.
- Кнопка назад в ЛК на страницах Мои ивенты, Избранное и Профайл.
- В личном кабинете на страницах Мои ивенты, Избранное и Профайл вернулись названия экранов

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by ElenaArtamoshkina** [comment]
Исправленные макеты
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=1-17057&t=9ITvMQyFvgJT5TV8-4
