### ISSUE TITLE
Актуализация страницы "Помочь Афиша"

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1433]
### Описание
Нужно убрать лишние способы донатов: Пэйпал. Проверить Бусти, Патреон и крипту.
На разработке убрать лишнее, потом отразить на макете. После разработки переделать задачу под дизайн.
### Критерии приёмки
- На странице отсутствует Пэйпал
- В остальном страница соответсвует макету

### Дополнительная информация
ссылка на доп задачу с криптой https://github.com/orgs/openworld-community/projects/6/views/62?pane=issue&itemId=85214412&issue=openworld-community%7Cows-events%7C1453

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by ElenaArtamoshkina** [comment]
Десктоп
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3759-61150&t=dVfhVV9ofGfKcA9S-4
Таблет
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3759-61335&t=dVfhVV9ofGfKcA9S-4
Мобильная
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3697-59968&t=dVfhVV9ofGfKcA9S-4
