### ISSUE TITLE
Поменять расстояния между элементами и размер картинок согласно отзывов от пользователей

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1440]
### - 🔴 Мобильная
- [x] Соотношение сторон поменять на 16/9 на мобилке (на макете поменять на без отступов с краю)
- [x] Расстояние от заголовка Афиша Сербия   |   Афиша Черногория
  - [x] верх 23 
  - [x] низ 17
  
- [x] Расстояние между датой, ценой, адресом - 5px
- [x] между картинка-Заголовок, заголовок -Организатор, организатор - дата, дата -теги - 7px
- [x] расстояние между ивентами - 20px

### - 🔴 Десктоп
- [x] Изменение картинок на соотношение 16/9  На главной странице на карточке ивента
- [x] Расстояние от заголовка Афиша Сербия   |   Афиша Черногория
  - [x] верх - 40px
  - [x] низ 30px
- [x]  Расстояние (горизонтальное) между ивентами - 20px
 
### -  🔴 Планшет
- [x] Изменение картинок на соотношение 16/9  На главной странице на карточке ивента
- [x] Расстояние от заголовка Афиша Сербия   |   Афиша Черногория
  - [x] верх - 40px
  - [x] низ 30px
- [x]  Расстояние (горизонтальное) между ивентами - 20px
---
### - 🔴 Мобильная
- [x] картинка ивента - 16/9
- [x] между Адресом и описанием  -10px

### - 🔴 Планшет
- [x] картинка ивента - 16/9
---
### Редактирование ивента
- Поменять aspect-ratio предпросмотра изображения на 16/9  В десктоп, планшет, мобилка
---
Дополнение по макету
### - 🔴 Мобилка
  - [x] В правом углу напротив Афиша Сербия  |   Афиша Черногория - отступ справа 2 px
### - 🔴 Планшет
  - [x] В правом углу напротив Афиша Сербия  |   Афиша Черногория - отступ справа как и у списка ивентов var(--padding-side)
### - 🔴 Десктоп
 - [x]  По центру напротив Афиша Сербия  |   Афиша Черногория
---
 
### Дополнительная информация
❗❗❗Пожалуйста проверьте кейс с лоадером когда мероприятий не найдено❗❗❗
❗❗❗А так же страницы городов и стран там такие же характеристики как на главной❗❗❗

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by ElenaArtamoshkina** [comment]
Десктоп
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3646-20941&t=G3cyXM4ZVCcckAoP-4
Таблет
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=4697-20571&t=G3cyXM4ZVCcckAoP-4
Мобильная
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3638-59102&t=G3cyXM4ZVCcckAoP-4
