### ISSUE TITLE
Неверный текст сообщения об ошибке при вводе недопустимого количества символов в поля "Название" и "Описание"

### ISSUE THREAD

**Issue by zhadetskaya-olga** [openworld-community/ows-events#1446]
### Критичность
P3 Низкий (Low)

### Опиcание
@Неверный текст сообщения об ошибке при вводе недопустимого количества символов в поля "Название" и "Описание"

### Ожидаемое поведение
"Заголовок слишком длинный"/"Title is too long" при вводе более 90 символов в поле "Название"
"Описание слишком длинное"/"Description is too long" при вводе более 1500 символов в поле "Описание"

### Условия воспроизведение
- Device [e.g. Desktop]
- OS: [e.g. Windows]
- Browser [e.g. chrome,]

### Шаги воспроизведения
1. Открыть тестовый стенд по ссылке https://test.afisha.peredelano.com/ru/event/229627a5-bd3e-48ae-adba-b1d55124dd6c
2. Авторизоваться
3. Нажать на кнопку "Создать мероприятие"
4. Заполнить все обязательные поля валидными данными
5. В поле "Название ввести 91 символ
6. В поле "Описание" ввести 1501 символ
7. Нажать на кнопку "Сохранить"
8. Посмотреть на тексты сообщений об ошибках в полях "Название" и "Описание"

### Ссылка на родительскую задачу
[[!IMPORTANT]](https://github.com/openworld-community/ows-events/issues/1415) Ссылка на родительскую задачу

### Скриншоты* (необязательное)
![Image](https://github.com/user-attachments/assets/acbdbb45-1289-4510-972a-823608e393c9)
![Image](https://github.com/user-attachments/assets/40001fcb-0ad4-4f02-81d5-dc5a558669e9)

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by toprogramm** [comment]
по описанию баг, это дописано было в таску после того как ее аппрувнули и смержили 😄
на дейлике тоже обсудим, желательно указать по моему сколько символов может ввести пользователь. иначе это неочевидно в чем ошибка.

**Comment by il12** [comment]
Прошу прощения, мой косяк.

Для названия:
Title should be no more then 90 total in length
Длина должна быть не более 90 символов

Для описания:
Description should be no more then 1500 total in length
Длина должна быть не более 1500 символов

Скриншоты соответствуют, таску закрываю
