### ISSUE TITLE
Картинка в личном кабинете "Внести вклад" не соответствует макету.

### ISSUE THREAD

**Issue by MarinaYuraneva** [openworld-community/ows-events#1452]
### Критичность
незначительная

### Описание
Картинка в личном кабинете "Внести вклад" не соответствует макету.

### Ожидаемое поведение
Картинка "Внести вклад" соответствует цвету ACACAC
Фактический результат: Цвет картинки 4Е4Е4Е темнее, чем в макете. 

### Условия воспроизведение
- Device [desktop]
- OS: [macOs]
- Browser [chrome, safari, firefox]
- Version [Google Chrome (129.0.6668.101), Safari 8.0 (20619.1.26.31.6), Mozilla (131.0.3)]

### Шаги воспроизведения
Открыть тестовое окружение
Авторизоваться
Перейти в личный кабинет

### Ссылка на родительскую задачу
#1319

**Comment by il12** [comment]
Иконка кнопки "внести вклад"
