### ISSUE TITLE
Актуализировать адреса криптокошельков

### ISSUE THREAD

**Issue by i-salimzhanov** [openworld-community/ows-events#1453]
### Описание
Привести в соответствие адреса криптокошельков указанных тут с тем что указаны на странице Помочь Afisha.

**USDT (TRC20)** TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3
**USDC (TRC20)**
TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3
**Ethereum**
0x4Dac7f4fAC521F170079eA912706BBe731F960a7
**Bitcoin**
bc1q0krv6zupalsuz4c8hpqg2e9z6m3klvxxdhwt88

### Критерии приёмки
- указаны актуальные адреса криптокошельков на странице Помочь Afisha.

**Comment by toprogramm** [comment]
Адреса всего на тесте сейчас(Поддержать проект):

Донат ресурсы
- https://www.patreon.com/afisha_peredelano - патреон
- https://boosty.to/afisha_prdln - бусти
- Paypal недоступен - удалить

Криптокошельки 
- TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3 - USDT(TRC20)
- TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3 - USDC(TRC20)
- 0x4Dac7f4fAC521F170079eA912706BBe731F960a7 - ETHEREUM
- bc1q0krv6zupalsuz4c8hpqg2e9z6m3klvxxdhwt88 - BITCOIN

**Comment by toprogramm** [comment]
то что сейчас на проде
- TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3 - USDT(TRC20) - соответствует
- TJw5KcaAdbPFnC3EEjLttwaVfEQxBuzWQ3 - UCDC(TRC20) - соответствует
- 0x4Dac7f4fAC521F170079eA912706BBe731F960a7 - ETHEREUM - соответствует
- bc1q0krv6zupalsuz4c8hpqg2e9z6m3klvxxdhwt88 - BITCOIN - соответствует
