### ISSUE TITLE
Поправить в дизайне "Выберите город" "Выберите страну" на то как на проде

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#1455]
### Критичность
Укажите уровень критичности
![Image](https://github.com/user-attachments/assets/0fff212c-c08b-4e0a-8c79-8794112c77d6)

### Описание
Опишите баг

### Ожидаемое поведение
Опишите ожидаемое поведение

### Условия воспроизведение
- Среда [e.g. Prod, Demo]
- Device [e.g. iPhone6, Desktop]
- OS: [e.g. iOS, Windows]

### Шаги воспроизведения
Пошаговое описание условий возникновения бага

### Релиз
В каком релизе был добавлен функционал, в котором возникла ошибка

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
- **Ссылки на скриншоты или картинки**

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by ElenaArtamoshkina** [comment]
Таблет
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=4697-20571&t=9ITvMQyFvgJT5TV8-4
Десктоп
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3646-20941&t=9ITvMQyFvgJT5TV8-4
Мобильная
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3638-59102&t=9ITvMQyFvgJT5TV8-4
