### ISSUE TITLE
Иконки соц.сетей в правом нижнем углу футера расположены в неверном порядке

### ISSUE THREAD

**Issue by zhadetskaya-olga** [openworld-community/ows-events#1462]
### Критичность
P03

### Описание
Иконки расположены в следующем порядке: Instagram, Twitter, LinkedIn, Telegram

### Ожидаемое поведение
Иконки расположены в следующем порядке: Twitter, Instagram, LinkedIn, Telegram

### Условия воспроизведение
- Среда: Prod
- Device: Desktop
- OS:  Windows
- Browser: chrome

### Шаги воспроизведения
Открыть сайт по ссылке: https://afisha.peredelano.com/ru

### Релиз
-

### Ссылка на родительскую задачу
баг найден в результате исследовательского тестирования

### Скриншоты* (необязательное)
![Image](https://github.com/user-attachments/assets/499d8f98-0b0f-49d1-815a-07d99dcee1e9)
![Image](https://github.com/user-attachments/assets/a9410e33-e899-4d88-9fad-d3ab22b2fac9)

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by ElenaArtamoshkina** [comment]
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3646-20941&t=fyEGtdAeJyW0vjwX-4

**Comment by ElenaArtamoshkina** [comment]
На макетах исправлено
https://www.figma.com/design/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?node-id=3646-20941&t=Lq3qZnydKBSyiEUE-4
