### ISSUE TITLE
Не работает кнопка "Удалить" мероприятие в личном кабинете

### ISSUE THREAD

**Issue by MarinaYuraneva** [openworld-community/ows-events#1470]
### Критичность
Укажите уровень критичности

### Описание
Если кликнуть на кнопку "Удалить" мероприятие в личном кабинете (внутри мероприятия), то оно не удаляется.

### Ожидаемое поведение
Мероприятие удалено.

### Условия воспроизведение
- Device [Desktop]
- OS: [macOs 15]
- Browser [chrome]
- Version [129.0.6668.101]

### Шаги воспроизведения
1. Открыть личный кабинет
2. Открыть Мои мероприятия
3. Открыть мероприятие
4. Кликнуть кнопку "Удалить"

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
(https://github.com/user-attachments/assets/b144f4ba-da13-471e-aaa9-c8b53ca55f7a)
![Image](https://github.com/user-attachments/assets/5b163aed-5be5-4a1b-b7a4-845923d12fec)

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by Sinamon-maker** [comment]
это не страница личного мероприятия, это страница ивента, также не проверена функциональность кнопки на других разрешениях
