### ISSUE TITLE
Фикс проблемы с индексацией.

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#1480]
### Описание
Пропала индексация по запросам "Афиша переделано", "Афиша Сербия Черногория"
работа с LD+JSON (+Почистить от лишних ошибок), возможно добавление линков или  создание сайтмап. 
Часть ресерч: доработка ключевых слов, метатеги (посмотреть код конкурентов). 

### Критерии приёмки
- При запросе в поисковике гугл "Афиша переделано" мы должны выпадать на 1-2 место, как это было раньше.
- При запросе "Афиша Сербия" и тп по странам и городам, мы должны хотябы на каких-то страницах индексироваться 
 главные странички стран и городов.
- Запрос должен индексироваться на русском и английском.

### Дополнительная информация
Добавьте информацию о задаче которую вы считаете важной

### Ссылки на баги, относящиеся к этой задаче
- [!CAUTION] *Ссылка на задачу-баг*.

### Оценка
Оцените задачу

**Comment by toprogramm** [comment]
заменить на русском head - на Афиша Переделано, на английском все ок.
meta key words - добавить
