### ISSUE TITLE
Ошибка в названии кнопки "Create event" в англ версии

### ISSUE THREAD

**Issue by MarinaYuraneva** [openworld-community/ows-events#1486]
### Критичность
низкая

### Описание
Название кнопки "Create event" лучше поменять на: "Create an event" или "New event".

### Ожидаемое поведение
У кнопки грамматически правильное название.

### Условия воспроизведение
- Device [Desktop, mobile, tablet]
- OS: [macos]
- Browser [chrome, safari, firefox]

### Шаги воспроизведения
1. Открыть главную страницу.
2. Выбрать английский язык.

### Ссылка на родительскую задачу
[!IMPORTANT] Ссылка на родительскую задачу

### Скриншоты* (необязательное)
![Image](https://github.com/user-attachments/assets/fbed4253-53e4-4c32-a597-f8d5e7690d16)
![Image](https://github.com/user-attachments/assets/ec088fd7-1642-4d43-868d-216be81d149b)

### Дополнительная информация* (необязательное)
Добавьте информацию о баге которую вы считаете важной

**Comment by toprogramm** [comment]
Изменены 
На главной странице сверху и в бургере
![Image](https://github.com/user-attachments/assets/797cc5ee-07a3-4da6-bd9b-fa95fec64e87)
![Image](https://github.com/user-attachments/assets/246c5764-53de-44a0-b3bf-25528e89e343)

На странице создания ивента
![Image](https://github.com/user-attachments/assets/a5c910e5-a3e1-46a7-b96a-b87b44c7d0fb)

Внутри ивента в информационном баннере 
![Image](https://github.com/user-attachments/assets/68f68ce3-a42c-41b3-8fa3-f8412af8724b)
