### ISSUE TITLE
📱 Нарисовать MVP ячейки списка событий

### ISSUE THREAD

**Issue by IlyaGulya** [openworld-community/ows-events#201]
Дизайн тут: https://www.figma.com/file/SMp69pu3EZenbYBBOxL5TG/Afisha-(peredelano)?type=design&node-id=162-409&t=E9cMZdtiVqlsK5mA-0

Пока рисуем не особо оглядываясь на дизайн, берём его только как концепцию.
Используем библиотеку компонентов чтоб двигаться быстрее.
Библиотека компонентов уже подключена в проект.
https://docs.getwidget.dev/introduction/

**Comment by ArkadiiIL** [comment]
Я хочу написать

**Comment by IlyaGulya** [comment]
@ArkadiiIL 
Бери задачу на себя сразу (справа вверху есть кнопка `assign yourself`)
