### ISSUE TITLE
Не кликабельна кнопка "Отменить" при создании мероприятия 

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#224]
Если заполнить все поля, то невозможно путем клика на "Отменить" вернуться к главной странице https://github.com/openworld-community/ows-events/assets/116894308/e48aeea2-3afd-42b3-831e-5f8223b04b07

**Comment by bigKingPenguin** [comment]
Вроде сейчас работает в dev версии, но нужно будет еще проверить

**Comment by bigKingPenguin** [comment]
В dev версии
