### ISSUE TITLE
(404 Ошибка) Как пользователь, когда я сталкиваюсь с 404 страницей на сайте, я хочу, чтобы мне предоставили сообщение о том, что страница не найдена, и возможные пути решения проблемы.

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#237]
Нужны как минимум:
1. Глобальный, который перекидывает на home, если в поисковой строке введена несуществующая страница
2. Отслеживающий введенные в поисковой строке ивенты, и перекидывающий на home, если такой страницы не существует
### На данный момент 404 утверждена вот такой страницей 

![Image](https://github.com/openworld-community/ows-events/assets/74075594/7d77e6b9-9533-42f7-8b70-1d4e45624940)

Критерии приемки
- [ ] При переходе на несуществующую страницу происходит редирект на "404" страницу.
- [ ] Отображение страницы должно соответствовать дизайну в Фигме: ...

**Comment by HugeLetters** [comment]
https://developers.google.com/search/docs/crawling-indexing/http-network-errors?hl=en&visit_id=637566240571379726-2206685189&rd=1#soft-404-errors
Пишут, что и для индексации, и для юзер экспириенса не оч делать редиректы, если страница не найдена - мб, тогда все же попросить дизайнеров запилить нам 404 страницу и на нее переводить в случае любых ошибок: не найден ивент, просто несуществующая страница и тд?

**Comment by Anaisnet** [comment]
Я за страницу 404. Это решило бы проблему с кучей редиректов и отслеживания их.

**Comment by i-salimzhanov** [comment]
> Сейчас происходит редирект на главную, если ивента не существует. Также при отсутствии авторизации происходит редирект со страниц "my events" и "favourites" на страницу пользователя с кнопкой авторизации. @asyavee @valentinudovik @i-salimzhanov нужно ли взять в работу идею с дизайном 404 страницы или можно закрыть этот таск?

я за кастомную страницу с ошибкой, пускай даже с ой, что-то пошло не так. Хотя и 404 вцелом тоже ок.

**Comment by Anaisnet** [comment]
Да, можно сделать кастомную при случае.

**Comment by Anaisnet** [comment]
Примеры кастомных страниц:
https://web-valley.ru/articles/404-oshibka-na-sajte

**Comment by AlexeyPQA** [comment]
Проверено
