### ISSUE TITLE
Рефакторинг главной страницы

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#240]

**Comment by IanaBlinova** [comment]
![c4o6K4Ld9A](https://github.com/openworld-community/ows-events/assets/116894308/c88add8b-27d9-4e0b-8ef6-f48c3cdad515)
![chrome_5BmFTdOtHF](https://github.com/openworld-community/ows-events/assets/116894308/7d74cb31-4ee0-4cd5-9d14-94a34f439a75)

Эмилия, не забудь, пожалуйста, просто ошибки на скринах
