### ISSUE TITLE
В поле "Название мероприятия" иконка крестика перекрывает вводимые буквы

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#248]
![IMG_20230601_191355.jpg](https://github.com/openworld-community/ows-events/assets/116894308/45a981ee-e4be-4050-9b98-f77db0312bee)

**Comment by bigKingPenguin** [comment]
Скоро подъедут кастомные инпуты, в них должно быть окей, но пока не закрываю баг
