### ISSUE TITLE
На экране оплаты, плашка для возврата не на всю ширину экрана

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#276]
**Describe the bug**
После прохождения регистрации на конференцию, на экране оплаты, плашка для возврата назад не на всю ширину экрана и по бокам виден текст при скроллинге вниз

**Screenshots**
Прилается

![IMG_2557](https://github.com/openworld-community/ows-events/assets/64010883/e30a2733-fccc-4a60-9c7c-bdfb4089ca80)

**Comment by bigKingPenguin** [comment]
таск #228
