### ISSUE TITLE
Не добавляется картинка при создании мероприятия. 

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#337]
https://github.com/openworld-community/ows-events/assets/116894308/e42e3ed4-a2a4-43e5-9bcd-d52ca68cd5d0

**Comment by HugeLetters** [comment]
@il12  если это с демки, то по идее ты это пофиксил уже вчера как раз.

**Comment by HugeLetters** [comment]
> @il12 если это с демки, то по идее ты это пофиксил уже вчера как раз.

Либо кстати, изображение слишком большойе - тогда не добавляется, но не уверен какой там лимит. У меня также было, когда добавлял картинку весом 1 мб.

**Comment by HugeLetters** [comment]
@IanaBlinova попробуй картинку небольшого размера - пусть даже 50кб и посмотри, добавится ли. Если да, то думаю, дело в лимите - не уверен правда ограничен где-то в настройках фастифая или это у фетча такие ограничения. Скорее, первое.

**Comment by il12** [comment]
> @IanaBlinova попробуй картинку небольшого размера - пусть даже 50кб и посмотри, добавится ли. Если да, то думаю, дело в лимите 
> @il12 это тебе надо где-то тогда в фастифае посмотреть, где настраивается.
> ![image](https://github.com/openworld-community/ows-events/assets/119697239/d73995d0-1866-441a-886b-6fdaa07cc6d7)
> 

Я знаю где, надо определиться с размером

**Comment by HugeLetters** [comment]
@IanaBlinova если с маленькими картинками бага не наблюдается, то тогда можно закрывать, я думаю

**Comment by IanaBlinova** [comment]
@HugeLetters добавила сейчас картинку 65кб, там 404 теперь

**Comment by HugeLetters** [comment]
> @HugeLetters добавила сейчас картинку 65кб, там 404 теперь

Типа пустая картинка будто файл не найден? Ну вот это Игорь точно уже вчера пофиксил тогда.

**Comment by IanaBlinova** [comment]
@HugeLetters это дев, баг воспроизводится

**Comment by bigKingPenguin** [comment]
pr #338

**Comment by NVIvanov** [comment]
@bigKingPenguin важная штука
