### ISSUE TITLE
Редактирование изображения ивента

### ISSUE THREAD

**Issue by HugeLetters** [openworld-community/ows-events#338]
Надо прописать рабочую логику для всех 3 кейсов:
1. Юзер удалил старое фото
2. Юзер удалил старое фото и добавил новое
3. Юзер не трогал никак поле с фото вообще

Пока что не оч корректно работает.

**Comment by HugeLetters** [comment]
Схема текущего стейта и ожидаемой логики исполнения, чтоб я ее не потерял потом
![image](https://github.com/openworld-community/ows-events/assets/119697239/070355ca-08ec-434f-b479-e50a48836f3c)

**Comment by IanaBlinova** [comment]
Данная задача выполнена, но баг 337 мешает ее корректной работе.

**Comment by HugeLetters** [comment]
> Данная задача выполнена, но баг 337 мешает ее корректной работе.

Я и написал в твоём ишшу, что не уверен, что это связанные проблемы. Я-то в этом пр свою отдельную обнаруженную проблему чинил, а не твой баг. Если твой баг ещё есть то открой снова пожалуйста и можешь отписаться там он только на телефоне или на десктопе тоже так? Лога и скрин нетворк таба тоже помогли бы очень
