### ISSUE TITLE
При попытке открыть страницу открываемую ТГ-ботом при регистрации в Chrome, слетает авторизация

### ISSUE THREAD

**Issue by ImKaQA** [openworld-community/ows-events#339]
Steps to reproduce
1.  Открыть https://poster-test-peredelano.orby-tech.space/
2. Нажать на иконку регистрации
3. Нажать на всплывающее окно "Войти" и перейти в ТГ-Бот
4. Нажать в боте на присланную ссылку и перейти на сайт https://poster-test-peredelano.orby-tech.space/ на внутреннем браузере в ТГ
5. Нажать на кнопку "Открыть в браузере..."

Expected behavior
Страница открывается с сохранением авторизации пользователя выполненной во Внутреннем браузере ТГ

Actual behavior
Страница открывается, но пользователь не авторизован

Smartphone (please complete the following information):
- Device: [iPhone 12 mini]
- OS:  iOS 16.5]
- Browser [Chrome ver. 114.0.5735.99]
- Application [Telegram ver. 9.6.3]

https://github.com/openworld-community/ows-events/assets/118220079/cee76a60-e2fc-4f83-8d1d-bb9d5bbbe8ce

**Comment by HugeLetters** [comment]
Неактуально вроде? @bigKingPenguin

**Comment by bigKingPenguin** [comment]
Да, изменили авторизацию
