### ISSUE TITLE
Не верно определяется местоположение

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#341]
![IMG_20230611_134026.jpg](https://github.com/openworld-community/ows-events/assets/116894308/c212dc7a-00bb-4d1a-a48b-b6c45fc0351a)

Я нахожусь в Казахстане, Алматы

**Comment by HugeLetters** [comment]
@orby-tech @il12 у нас случайно не где-то там сервер захосчен как раз? Думаю, это из-за сср и что реквест идет с сервера - если так, то надо будет переделать просто, чтоб только с клиента этот запрос шел.

**Comment by il12** [comment]
> @orby-tech @il12 у нас случайно не где-то там сервер захосчен как раз? Думаю, это из-за сср и что реквест идет с сервера - если так, то надо будет переделать просто, чтоб только с клиента этот запрос шел.

Всë верно, ровно в Амстердаме и захощен.
