### ISSUE TITLE
Привести модалку авторизации в соответствие с макетом

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#353]
<img width="297" alt="Снимок экрана 2023-06-12 в 22 34 02" src="https://github.com/openworld-community/ows-events/assets/124285205/bd81362e-ccc6-4fdc-b112-7f578b63f5ff">

Когда юзер авторизован, в хэдере модалки вместо текста должен быть юзернейм, зеленые кнопки должны иметь текст "войти/выйти" в зависимости от наличия авторизации

**Comment by IanaBlinova** [comment]
прошу уточнить, тут должна быть кнопка "Выйти" или "Отмена" как сейчас?

![Image](https://github.com/openworld-community/ows-events/assets/116894308/4e067807-1e5b-4020-94ca-c59f788eb500)

**Comment by bigKingPenguin** [comment]
Судя по скрину, ты авторизована в данный момент, "выйти" - значит деавторизоваться
