### ISSUE TITLE
Заменить инпуты на главной странице на новые

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#360]
<img width="330" alt="Снимок экрана 2023-06-14 в 13 12 30" src="https://github.com/openworld-community/ows-events/assets/124285205/b5c38d3b-6180-4d72-99f2-bf3d5edc7e29">

Новые инпуты лежат в frontend/cpmponents/common/ui

**Comment by NVIvanov** [comment]
@bigKingPenguin задача на после MVP
