### ISSUE TITLE
Удаление ивента не работает

### ISSUE THREAD

**Issue by HugeLetters** [openworld-community/ows-events#368]
Удаление через `http://localhost:7080/api/events/delete` фейлится тк сервер не может найти файл изображения, которое надо удалить вместе с ивентом
```
{
    "statusCode": 500,
    "code": "ENOENT",
    "error": "Internal Server Error",
    "message": "ENOENT: no such file or directory, unlink 'C:\\assets\\img\\e30bf933-143f-4fd3-ac50-ecc64fee0d5f.png'"
}
```
Редактирование ивента с удалением изображения работает ок

**Comment by il12** [comment]
#370
