### ISSUE TITLE
Поправить стили в модалках

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#382]
Цвета и бордеры у шапки и футера в соответствии с макетом (Modal window update proposal)
У добавленного изображения сделать крестик вместо кнопки "удалить изображение":

![Image](https://github.com/openworld-community/ows-events/assets/124285205/11a24116-fce4-48c4-b98b-ed1e5b174acb)

**Comment by NVIvanov** [comment]
@bigKingPenguin кажется не приоритетно
