### ISSUE TITLE
НЕ авторизованый пользователь может добавлять мероприятия, но в итоге не до конца..

### ISSUE THREAD

**Issue by ImKaQA** [openworld-community/ows-events#388]
**To Reproduce**
1. Открыть https://poster-test-peredelano.orby-tech.space/
2. Быть НЕ авторизованым 
3. Нажать на кнопку добавления мероприятия

**Expected behavior**
1. Открыто окно с предложением авторизоваться)
**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: [ win10 ]
- Browser [ Chrome ]
- Version [ Версия 114.0.5735.134 ]

https://github.com/openworld-community/ows-events/assets/118220079/a9c53699-6f3c-4893-8978-d1d84200f9ae

https://github.com/openworld-community/ows-events/assets/118220079/9882fb05-729e-4a97-816e-bb157bd2de29

**Comment by bigKingPenguin** [comment]
Временно подключали при разработке и забыли убрать, пофиксили
