### ISSUE TITLE
Неверная обозначение, отлично от макета

### ISSUE THREAD

**Issue by ImKaQA** [openworld-community/ows-events#398]
**To Reproduce**
1.  Открыть https://poster-test-peredelano.orby-tech.space/
2. Найти в ленте бесплатное мероприятие

**Expected behavior**
На бесплатных мероприятиях обозначение "Бесплатно"

**Screenshots**

**Desktop (please complete the following information):**
OS [ win10 ]
Browser [ Chrome ]
Version [ Версия 114.0.5735.134 ]

**Additional context**

**Comment by il12** [comment]
Не очень понимаю. На тесте видны как мероприятия с ценой "Бесплатно", так и с ценой "123 RSD". Так же есть мероприятия с ценой "Цена не указана", о цене которых нам неизвестно.

**Comment by ImKaQA** [comment]
> Не очень понимаю. На тесте видны как мероприятия с ценой "Бесплатно", так и с ценой "123 RSD". Так же есть мероприятия с ценой "Цена не указана", о цене которых нам неизвестно.

А как может  быть такое что неизвестно какая цена? Как реализовать это с сайта я уже нашел, я имею ввиду вообще, само по себе как явление?

**Comment by ImKaQA** [comment]
> > > Не очень понимаю. На тесте видны как мероприятия с ценой "Бесплатно", так и с ценой "123 RSD". Так же есть мероприятия с ценой "Цена не указана", о цене которых нам неизвестно.
> > 
> > 
> > А как может  быть такое что неизвестно какая цена? Как реализовать это с сайта я уже нашел, я имею ввиду вообще, само по себе как явление?
> 
> Большая часть ивентов у нас будет приходить от сервисов парсинга. На некоторых сайтах, с которых мы берём информацию цена ивента может быть не указана

Принял!
