### ISSUE TITLE
При создании мероприятия не исчезает элемент "Часы"

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#429]
**Describe the bug**
При создании мероприятия не исчезает элемент "Часы" на Android

**To Reproduce**
1. Заходим на сайт
2. Нажимаем кнопку создания мероприятия ("+")
3. Выбираем время мероприятия
4. После выбора времени исчезает элемент "Часы"

**Expected behavior**
Элемент "Часы" должен исчезнуть при нажатие на другое поле

**Screenshots**
Прилагается видео

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- Device: [Xiaomi Redmi Note 7] 
- OS: [MiUi 12.5.3]
- Browser [Mi browser]

https://github.com/openworld-community/ows-events/assets/64010883/ec39b79b-32fe-417c-8427-e3250bf66e87

**Comment by bigKingPenguin** [comment]
@IvanEmelianov а календарь скрывается?

**Comment by IvanEmelianov** [comment]
Да, календарь скрывается

**Comment by bigKingPenguin** [comment]
Календарь скрывается при выборе даты,
Время должно скрываться при клике вне дропдауна

**Comment by bigKingPenguin** [comment]
@IvanEmelianov ты через enter между инпутами переключаешься?

**Comment by bigKingPenguin** [comment]
@IvanEmelianov я добавила закрытие дропдаунов при нажатии enter, должно стать лучше
