### ISSUE TITLE
Нет интервалов между полями

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#430]
**Describe the bug**
Нет интервалов между полями. Android.

**To Reproduce**
1. Заходим на сайт
2. Нажимаем кнопку создания мероприятия ("+")
3. Нет интервалов между полями локации, общей информации, начала и окончания

**Screenshots**
Прилагается

**Smartphone (please complete the following information):**
- Device: [Xiaomi Redmi Note 7]
- OS: [MiUi 12.5.3]
- Browser [Chrome]
- Version [83.0.4103.101]
![photo_2023-06-20_22-14-53](https://github.com/openworld-community/ows-events/assets/64010883/8d0148c0-91d8-47b1-a081-13827f6e4fc3)

**Comment by bigKingPenguin** [comment]
Андроид не поддерживает css gap, добавить маргины
