### ISSUE TITLE
Видны кнопки Удалить и Редактировать у мероприятий Peredelano при неавторизованном пользователе

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#432]
To Reproduce
Пред.: выйти из профиля пользователя

1. Выбрат мероприятие Peredelano (пр. Cyprus, Limassol)

Expected behavior
Видна только карточка мероприятия с фотографией, описание и другими полями

https://github.com/openworld-community/ows-events/assets/108461088/381bedec-c9b0-41be-9897-068e87549d67

Smartphone (please complete the following information):

Device: iPhone11

OS: iOS16.5

Browser Firefox

Version 114.2

Device: Xiaomi Redmi 9C NFC

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153

**Comment by HugeLetters** [comment]
Можешь, пожалуйста, перепроверить, сохранился ли баг? Ранее была ошибка, что кнопка логаута ничего не делала - возможно, с ней связано попросту, но на текущей версии она пофикшена.

**Comment by il12** [comment]
> @il12 можешь подсказать у этого ивента какой creatorID? Если "dev-user", то бага нет - я так понял @bigKingPenguin просто добавила это для возможности дебагать без ауфа некоторые ивенты. [14145d4#diff-a2095b3ac9e1e3ec5ad11d13f0d612f19bc191f3f6ea6e6bea8299e94462aa05R163](https://github.com/openworld-community/ows-events/commit/14145d4eb112b39035ebab0275d62a7840d9b363#diff-a2095b3ac9e1e3ec5ad11d13f0d612f19bc191f3f6ea6e6bea8299e94462aa05R163)

У этого ивента нет creatorId
