### ISSUE TITLE
Кнопка "Сохранить" в модальном окне создания мероприятия disabled при всех заполненных полях. 

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#433]
Может быть связано с неподтягиванием города и часового пояса. 
https://github.com/openworld-community/ows-events/assets/116894308/d308af84-ed05-455d-ab1b-4b1b65006d65

**Comment by HugeLetters** [comment]
@bigKingPenguin Все работает как и должно - если не указан валидный часовой пояс, то кнопка сохранить не должна быть активной

https://github.com/openworld-community/ows-events/blob/910ac8892a82a024691a9af8f26c28de08d0d215/frontend/components/modal/Event.client.vue#L67
