### ISSUE TITLE
Проскролленая лента возвращается в начало после просмотра мероприятия

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#434]
To Reproduce

1. Проскроллить ленту мероприятий вниз
2. Выбрать любое мероприятие
3. Нажать назад

Expected behavior
Лента осталась на мероприятии, которое было просмотрено последним

Desktop (please complete the following information):

OS: Windows 10
Browser Chrome
Version 114.0.5735.134
Smartphone (please complete the following information):

Device: iPhone11

OS: iOS16.5

Browser Firefox

Version 114.2

Device: Xiaomi Redmi 9C NFC

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153

https://github.com/openworld-community/ows-events/assets/108461088/c991a32e-d8e1-4572-9314-a3c61de37971

**Comment by bigKingPenguin** [comment]
Пока не добавляли этот функционал и до MVP не успеем

**Comment by HugeLetters** [comment]
> Пока не добавляли этот функционал и до MVP не успеем

Я вот утром гуглил наскок это легко сделать - вроде звучит как фича, которая в Нуксте нативно должна быть. 
Типа у нас и поисковый запрос сбрасывается при возращения назад, но это-то фиксится добавлением пропа keepalive на страницы

**Comment by bigKingPenguin** [comment]
наверное все же на домашнюю, но уточни пожалуйста еще этот момент у дизайнеров, возможно они что-то другое предусмотрели в user flow

**Comment by HugeLetters** [comment]
@valentinudovik подскажешь, пожалуйста, по вопросу выше?

**Comment by HugeLetters** [comment]
Посоветовавшись с дизайнерами было принято решение убрать кнопку назад и показывать кнопку возвращения на домашнюю. Для возвращения назад предполагается, что юзеры будут использовать нативную кнопку назад, которая есть в браузерах(или свайп вправо на телефоне)
