### ISSUE TITLE
Нельзя посмотреть загруженное изображение

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#435]
Describe the bug
Нельзя просмотреть загруженное изображение, видно только превью

To Reproduce
1. Нажать Добавить мероприятие (+)
2. Добавить фото
3. Просмотреть добавленное изображение

Expected behavior
Можно раскрыть и увидеть изображение, которое было добавлено

Desktop (please complete the following information):
<img width="291" alt="Screenshot 2023-06-21 at 10 04 50" src="https://github.com/openworld-community/ows-events/assets/108461088/61273020-8106-4b50-9855-a6a914763e7d">

OS: Windows 10
Browser Chrome
Version 114.0.5735.134
Smartphone (please complete the following information):

Device: iPhone11

OS: iOS16.5

Browser Firefox

Version 114.2

Device: Xiaomi Redmi 9C NFC

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153

**Comment by HugeLetters** [comment]
Больше похоже на feature request, а не баг. Добавленное изображение и так видно на странице ивента.
@bigKingPenguin нам нужен такой функционал?

**Comment by bigKingPenguin** [comment]
Пока только так работает, оставим реквест на будущее
