### ISSUE TITLE
Ошибка при редактировании и удалении мероприятия 

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#450]
**Describe the bug**
Не работает редактирование и удаление меропрития 

**To Reproduce**
1. Создаем мероприятие
2. Нажимем на кнопку педактировать (удалить)
3. Всплывает окно error.forbidden

**Expected behavior**
Редактирование / удаление меропрития 

**Screenshots**
Прилагаются
![image](https://github.com/openworld-community/ows-events/assets/64010883/ae8d1451-ac50-48ee-9058-2b23d1758aee)
![image](https://github.com/openworld-community/ows-events/assets/64010883/48339f6e-57f4-4791-a32a-4d6ba0d69a88)

**Comment by HugeLetters** [comment]
А можно скрины preview/payload, пожалуйста?

**Comment by HugeLetters** [comment]
И как давно был создан ивент? А то мб с момента создания ты логинился заново и новый токен сгенерился для логина , например

**Comment by IvanEmelianov** [comment]
@HugeLetters ивент был создан мной несколько дней назад, с того момент я с аккаунта не выходил и при входе на сайт не авторизировался

Редактирование
![image](https://github.com/openworld-community/ows-events/assets/64010883/ef4c764c-f660-4bcc-9bad-197909ba8f50)
![image](https://github.com/openworld-community/ows-events/assets/64010883/a219c276-b9f8-4a97-ab3f-28073920daf8)

Удаление
![image](https://github.com/openworld-community/ows-events/assets/64010883/1b8719b9-f396-4659-ba72-919575964afa)
![image](https://github.com/openworld-community/ows-events/assets/64010883/8f36f4c4-1e7b-4c5c-b597-e10fcb8e0b69)

**Comment by HugeLetters** [comment]
@il12 есть возможность позырить какой creatorID у ивента? Явно тут что-то не так происходит. У нас у jwt какой-то срок годности есть? Мб он истек просто?
https://github.com/openworld-community/ows-events/blob/b3180172edf540c162220c992e78149915312be2/backend/src/rest/v1/events/controller.ts#L72

**Comment by il12** [comment]
> @il12 есть возможность позырить какой creatorID у ивента? Явно тут что-то не так происходит. У нас у jwt какой-то срок годности есть? Мб он истек просто?
> 
> https://github.com/openworld-community/ows-events/blob/b3180172edf540c162220c992e78149915312be2/backend/src/rest/v1/events/controller.ts#L72

Такого ивента в базе нет.
При истечении жизни токена кидается другая ошибка (WRONG_TOKEN).
Предлагаю почистить кэш, и попробовать воспроизвести. Если буде твоспроизводиться - прошу скинуть в личку скриншот  Headers, потому что, выглядит как проблема с приходящим на бэк токеном.
