### ISSUE TITLE
Ошибка при добавлении картинки в мероприятие 

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#462]
**Describe the bug**
Ошибка при добавлении картинки в мероприятие 

**To Reproduce**
1. Создаем мероприятие
2. Добавляем прикрепляем картинку
3. Видим ошибку

**Expected behavior**
Прикрипляю скрины бага, payload и preview

![image](https://github.com/openworld-community/ows-events/assets/64010883/057b1db9-f295-4b01-b2a4-a531b16b57c4)

![image](https://github.com/openworld-community/ows-events/assets/64010883/3b96474d-1671-4614-93db-05a8f2188c8c)

![image](https://github.com/openworld-community/ows-events/assets/64010883/201f45ae-5246-4930-b50c-83f3f989fb5f)

**Comment by il12** [comment]
Это защита от дубликатов ивента. Нельзя добавить больше одного активного ивента с одинаковыми ссылками) 
Решение временное, когда доделаем сервис комплаенса - будет лучше

**Comment by il12** [comment]
Попробуй с другой ссылкой

**Comment by IvanEmelianov** [comment]
@il12 
Мне кажется не в ссылки дело. Баг воспроизводится с другими ссылками

![image](https://github.com/openworld-community/ows-events/assets/64010883/c248dfcf-799a-454a-9c10-2573e6383ea2)

**Comment by il12** [comment]
В базе есть ивент с такой ссылкой)
Картинки нормально добавляются, по логам проверил

**Comment by IvanEmelianov** [comment]
@il12 С такой ссылкой не думаю, что есть)

![image](https://github.com/openworld-community/ows-events/assets/64010883/e17c1d98-b72c-4786-95d9-ebcd834d5189)

**Comment by il12** [comment]
Опа, локализовал проблему, спасибо)

На самом деле ивент добавляется, только почему-то потом идёт ещё один запрос, от которого и падает ошибка (что логично)
@bigKingPenguin @HugeLetters Посмотрите пожалуйста, как время будет

**Comment by HugeLetters** [comment]
> 

@il12 
Два `add` реквеста и должно быть - первый добавляет картинку, второй сам ивент(ну и префлайты на оба). У меня и самого ща на тесте было два реквеста, но оба прошли ок. Тут судя по порядку реквестов выглядит так, что картинка при добавлении ивента-дубликата прошла(логично, у нас на это проверок нет никаких), а вот уже сам ивент - нет.

@IvanEmelianov можешь, пожалуйста, воспроизвести баг и скинуть скрины payload и preview всех реквестов, которые у тебя проходят при попытке сохранить ивент? И успешные реквесты, и сфейленные.

**Comment by il12** [comment]
Мне действительно не удаётся воспроизвести. 

@IvanEmelianov Можешь, пожалуйста, скинуть браузер и ОС на которых тестишь?

**Comment by IvanEmelianov** [comment]
@HugeLetters Вот скрины payload и preview всех реквестов (первый и последний add - это OPTIONS, там нет информации в payload и preview

@il12 
OC: Windows 10
Браузер: Chome
Версия:  114.0.5735.111 (64 бит)

![image](https://github.com/openworld-community/ows-events/assets/64010883/3d3f4ac2-4299-48a9-ae6a-037b7fd2357e)

![image](https://github.com/openworld-community/ows-events/assets/64010883/32547c83-2dc9-4127-8b67-72306fe13076)

![image](https://github.com/openworld-community/ows-events/assets/64010883/6c137123-0dc1-49fc-948c-9ecfdc3d7900)

![image](https://github.com/openworld-community/ows-events/assets/64010883/64283d9c-4b27-4990-b0c8-b96899a4ec18)

**Comment by il12** [comment]
Окей, теперь ошибка другая, теперь в ивенте что-то вызвало подозрение у сервиса автомодерации.

**Comment by HugeLetters** [comment]
Ну так все ок вроде - ты добавил ивент успешно, какие-то проверки не прошли и он на модерацию отправлен. В списке ивентов его не будет, пока он модерацию не пройдет

**Comment by IvanEmelianov** [comment]
ой, да, с дату не ту поставил...

и да, все заработало, видимо действительно проблема была не в картинки, а в ссылке, как писал @il12 в первом комментарии)

я предупрежу остальных тестировщиков, чтобы с этим же вопросом не приходили, думаю баг можно закрывать)
