### ISSUE TITLE
Нет интервалов между кнопками

### ISSUE THREAD

**Issue by IvanEmelianov** [openworld-community/ows-events#463]
**Describe the bug**
Нет интервалов между кнопками в мероприятие 

**To Reproduce**
1. Создаем мероприятие
2. Заходим в него
3. Видим баг

**Screenshots**
Прилагается

**Smartphone (please complete the following information):**
- Device: [Xiaomi Redmi Note 7]
- OS: [MiUi 12.5.3]
- Browser [Chrome]
- Version [83.0.4103.101]

![photo_2023-06-22_20-50-04](https://github.com/openworld-community/ows-events/assets/64010883/c81ce867-dbe3-4402-b3a5-9199bfed5f00)

**Comment by bigKingPenguin** [comment]
@IvanEmelianov а на главной странице на этом же девайсе инпуты не слипаются?
