### ISSUE TITLE
Верстка не адаптируется под разрешение экрана

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#465]
To Reproduce

1. Ввести адрес сайта в адресную строку
2. Перейти на сайт

Xiaomi Redmi 9C 

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153

https://github.com/openworld-community/ows-events/assets/108461088/c06b7ce4-45a6-42de-ae89-6bbd29d61c09

![2023-06-23 14 03 34](https://github.com/openworld-community/ows-events/assets/108461088/08bfc91c-e3c9-4574-b044-7eaa5c64d20a)

**Comment by bigKingPenguin** [comment]
По дизайну, минимальная ширина экрана 375px

**Comment by bigKingPenguin** [comment]
@GermanVasev этот баг вылез недавно или всегда так было?
