### ISSUE TITLE
Можно ввести текст в поле Стоимость при создании мероприятия

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#466]
To Reproduce

1. Тапнуть создать мероприятие
2. Ввести Стоимость
3. Заполнить остальные поля
4. Сохранить

Desktop (please complete the following information):

OS: Windows 10
Browser Chrome
Version 114.0.5735.134

Smartphone (please complete the following information):

Device: iPhone11

OS: iOS16.5

Browser Firefox

Version 114.2

Device: Xiaomi Redmi 9C NFC

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153
<img width="231" alt="Screenshot 2023-06-23 at 14 29 36" src="https://github.com/openworld-community/ows-events/assets/108461088/05dbb577-c50c-4891-a25e-b45853d5e298">

**Comment by bigKingPenguin** [comment]
Да, так и есть, потому что от бэка был запрос, чтобы из этого поля приходили данные в формате String, а не Number.
@il12 нужно наверное ограничивать на бэке

**Comment by il12** [comment]
Мы ж вроде на строку и договаривались временно, разве нет? После мвп надо будет проработать и этот вопрос и даты гораздо более серьёзно

**Comment by bigKingPenguin** [comment]
временно? окей
значит пока этот баг никуда не деть

**Comment by bigKingPenguin** [comment]
В инпут цены подставляется по умолчанию строка, инпут некорректно отрабатывает

**Comment by bigKingPenguin** [comment]
#537

**Comment by bigKingPenguin** [comment]
Действительно, type="number" не дает вводить буквы только в хроме, для файерфокса и сафари нужно добавить еще паттерн

**Comment by bigKingPenguin** [comment]
@IanaBlinova, на данный момент для firefox и safari это можно будет сделать только на уровне валидации, поэтому привяжу эту задачу к #556 
Можно, конечно, начать разрабатывать свой сервис масок для инпутов, но сейчас на это точно не хватит ресурсов

**Comment by dimatakoy** [comment]
Может просто прикрутить https://maskito.dev/frameworks/vue от ребят из тинькофф?
