### ISSUE TITLE
При редактировании ивента не сохраняются изменения

### ISSUE THREAD

**Issue by ImKaQA** [openworld-community/ows-events#475]
**To Reproduce**
1. Открыть сайт https://poster-test-peredelano.orby-tech.space/
2. Нажать на  созданный нами ивент
3. Нажать на кнопку «Редактировать»
4. Внести изменения в модальном окне редактирования мероприятия 
5. Нажать на кпопку «Сохранить»

**Expected behavior**
Внесенные изменения сохранены

**Actual behavior**
Выдает окно с ошибкой

**Screenshots**

**Smartphone (please complete the following information):**
- Device: [ iPhone 12 mini ]
- OS: [ iOS 16.5 ]
- Browser [ Chrome ]

https://github.com/openworld-community/ows-events/assets/118220079/2aac5cbf-f507-4bf7-bfd3-f6874f6eafde

**Comment by il12** [comment]
Попробуй, пожалуйста, выйти из аккаунта и зайти заново

**Comment by ImKaQA** [comment]
> Попробуй, пожалуйста, выйти из аккаунта и зайти заново

Все заработало!!!
