### ISSUE TITLE
HTTP to HTTPS redirect doesn't work

### ISSUE THREAD

**Issue by NVIvanov** [openworld-community/ows-events#482]
**Describe the bug**
Не работает редирект с http на https.

**To Reproduce**
Воспроизводится на десктопе и на мобилке.
iOS, safari: открыть браузер и перейти по адресу afisha.peredelano.com
macOS, chrome: открыть браузер, перейти по адресу **http**://afisha.peredelano.com

**Expected behavior**
При попадании на http происходит редирект на https, как для запросов к фронту, так и для запросов к бэкенду по API.

**Desktop (please complete the following information):**
- OS: macOS
- Browser: chrome

**Smartphone (please complete the following information):**
- OS: iOS
- Browser safari

**Comment by il12** [comment]
Нам точно нужно именно такое поведение?

**Comment by bigKingPenguin** [comment]
а почему нет?

**Comment by bigKingPenguin** [comment]
После выполнения таска seo анализатор пишет, что с редиректом все в порядке

![Image](https://github.com/openworld-community/ows-events/assets/124285205/8ecd6bfc-6c10-4604-bb12-53448913d874)
