### ISSUE TITLE
Прошедшие ивенты можно редактировать

### ISSUE THREAD

**Issue by HugeLetters** [openworld-community/ows-events#489]
Необходимо прописать логику и для бэкенда(если ее еще нет), и для фронтенда(точно еще нет)

**Comment by bigKingPenguin** [comment]
а что на бэке нужно?

**Comment by HugeLetters** [comment]
> а что на бэке нужно?

а бэк у нас как-то запрещает редачить прошедшие ивенты? мне что-то мешает сделать curl на бэк с моим токеном и отредачить ивент так?

**Comment by bigKingPenguin** [comment]
@il12 тогда на фронте мы сделали ограничение, передаем на вашу сторону

**Comment by il12** [comment]
Вы уже смержили в мэйн? В новой ветке делать или в вашей?

**Comment by Yulia-Kotlyarova** [comment]
я вмержила, так понимаю по новому флоу нужно от этой ветки ответвляться

**Comment by il12** [comment]
> я вмержила, так понимаю по новому флоу нужно от этой ветки ответвляться

Ага, хорошо, тогда скоро сделаю
