### ISSUE TITLE
Кнопки "Удалить" и "Редактировать" не меняют цвет после нажатия в окне созданного мероприятия

### ISSUE THREAD

**Issue by GermanVasev** [openworld-community/ows-events#494]
To Reproduce

1. создать мероприятие
2. тапнуть кнопку "Удалить" или "Редактировать"

Desktop (please complete the following information):

OS: Windows 10
Browser Chrome
Version 114.0.5735.134

Smartphone (please complete the following information):

Device: iPhone11

OS: iOS16.5

Browser Firefox

Version 114.2

Device: Xiaomi Redmi 9C NFC

OS: Android 10, MIUI Global 12.0.14

Browser Chrome

Version 110.0.5481.153

https://github.com/openworld-community/ows-events/assets/108461088/ea71711b-3351-4ac2-a057-788a4876da5f

**Comment by HugeLetters** [comment]
@bigKingPenguin не уверен, что это стоит считать багом - после закрытия модалки это стандартная практика, что фокус переводится обратно на кнопку, которая стриггерила появление модалки. Потому когда юзер закрывает модалку удалить ивент, кнопка удалить ивент получает фокус. Наша кнопка подсвечивается, когда над ней висит курсор или когда она в фокусе.Подсветка сфокусированных кнопок - это также хорошая практика для a11y.

Так что имхо такое поведение стоит оставить.

**Comment by bigKingPenguin** [comment]
Я бы тоже пока оставила, тем более что у нас пока нет стилей для outline элементов, находящихся в фокусе

**Comment by bigKingPenguin** [comment]
Я немного не об этом: нам нужен отдельный дизайн для элементов в фокусе, и уже потом отдельный таск на стилизацию. Этот таск можно закрыть, да
