### ISSUE TITLE
Event modal datepicker issues

### ISSUE THREAD

**Issue by HugeLetters** [openworld-community/ows-events#502]
- [x] Очистка даты должна очищать время
- [x] Очистка даты начала должна очищать дату конца
- [x] Для даты окончания минимальным значением должно быть выбранная дата начала
- [x] аналогично для времени но чето там посложнее логика наверное
- [x] если дата начала сменена на дату позднее текущей даты конца, выставить дату конца как дату начала
- [x] аналогично со временем

**Comment by HugeLetters** [comment]
@bigKingPenguin все ли верно указал? Или мб наоборот не хотим пункты 1/2? Пункт 3 думаю однозначно нужен

**Comment by bigKingPenguin** [comment]
Нужно уточнить у @valentinudovik @lebedandrei. Как должны вести себя инпуты даты и времени в форме создания?

**Comment by valentinudovik** [comment]
1. Да, если удаляем дату, то удаляется и время. 
2. Согласен. 

И есть еще косяк, на мой взгляд: когда я создавал мероприятие, то по ошибке указал поставил в дате окончания 26 июня, хотя дата начала была 30. Мы этого не предусмотрели и по идее у юзера не должно быть возможности так делать.

+ еще дизайнерский косяк с вводом времени. Надо бы туда и клавиатуру числовую прикрутить
