### ISSUE TITLE
Внедрить полную локализацию на русском

### ISSUE THREAD

**Issue by OSKotelianets** [openworld-community/ows-events#511]

**Comment by il12** [comment]
Локализация описаний ивентов

**Comment by IvanEmelianov** [comment]
Описание ивентов доступно на русском и английском языке


![Image](https://github.com/openworld-community/ows-events/assets/64010883/ac9ee579-5c25-4e4f-a030-b814474c5c8e)

**Comment by bigKingPenguin** [comment]
@IvanEmelianov имеется в виду, что название не переведено?
