### ISSUE TITLE
i18n fixes

### ISSUE THREAD

**Issue by HugeLetters** [openworld-community/ows-events#520]
- [x] #522
- [x] #523
- [x] миграция на nuxt/i18n
- [x] lazy loading по локалям
- [ ] lazy loading по страницам - скорее всего невозможно на nuxt/i18n вместе с лейзилоадом по локалям
- [x] разобраться с интеграцией числительных
- [ ] структурировать как составляются объекты с ресурсами переводов
- [x] попытаться сделать название страницы динамическим все же а не сугубо по инишиал лоаду
- [x] может быть получиться сделать еще роутинг по локалям - так вроде лучше для SEO. Очень вероятно придется переползать на другую i18n либу или чето свое пытаться запилить 💀

**Comment by KemSummons** [comment]
**1. На страницах, где нет в хэдере кнопки "назад", в хэдере есть переключатель языков (английский/русский)** - ☑️
**2. При переключении языка происходит редирект по адресу afisha.peredelano.com/ru или afisha.peredelano.com/en** - ☑️
**3. По умолчанию язык русский** - ☑️
**4. При переключении языка переводится страница, дальнейшая навигация осуществляется на выбранном языке** - ☑️
**5. Нигде не потеряны переводы** - ❌ 
Есть баг в карточке создания мероприятия: в полях ввода Start и End плейсхолдеры на русском
![Скриншот-16-12-2023 21_09_54](https://github.com/openworld-community/ows-events/assets/95969907/8f98a920-e1f6-4338-b60d-41c5d9dcc444)
**6. Все пользовательские сценарии выполняются корректно** - ☑️

**Comment by KemSummons** [comment]
@bigKingPenguin 
Есть баг в карточке создания мероприятия: при английском варианте сайта в полях ввода Start и End плейсхолдеры на русском - пофикшено только на тесте, в демо и на проде баг еще есть

**Comment by bigKingPenguin** [comment]
@KemSummons так мы на демо еще не заливали эти правки
