### ISSUE TITLE
Сверстать user page

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#521]
Макет есть в фигме: 
<img width="339" alt="Снимок экрана 2023-06-27 в 18 42 40" src="https://github.com/openworld-community/ows-events/assets/124285205/34868c1b-dbb7-425e-a610-35124bd6369d">

1. Создать пустую страницу в pages/ с названием "user"
2. Добавить enum для этой страницы в constatns/enums/route.ts
3. Добавить в навбар (components/header/navigation/Sidebar.vue) ссылку на эту страницу с названием "Пользователь" и иконкой user (аналогично ссылке "O нас")
4. Сверстать страницу в соответствии с макетом, пока без логики. В тех местах, в которые должен динамически вставляться текст, оставить рандомные заглушки

**Comment by valentinudovik** [comment]
Можем немного повременить? Нет уверенности, что это финальный вариант. @bigKingPenguin

**Comment by bigKingPenguin** [comment]
Далее нужно сверстать модал для редактирования данных:
<img width="258" alt="Снимок экрана 2023-06-29 в 14 38 00" src="https://github.com/openworld-community/ows-events/assets/124285205/d4993b7d-bebe-4385-a747-df6e78a89cc7">

Он должен открываться при клике на кнопку "редактировать" и содержать те же поля, что и юзерпейдж, за исключением никнейма (он будет подтягиваться автоматически как ник из телеграмма).
Образец построения тела модалки можно посмотреть в компоненте components/modal/Event.client.vue.
Все поля - необязательные к заполнению.

Поле "Компания" лучше пока переименовать в "Организатор", и в плейсхолдере указать, что это имя, от которого будут создаваться мероприятия.
Поле "имя" должно содержать плейсхолдер вроде "как к вам обращаться?".

Все данные из инпутов должны записываться в скрипт аналогично примеру(см. inputValues в Event.client.vue), корректность отображения можно проверить в vue devtools.

При клике на кнопку "отмена" модал должен закрываться.
Кнопка "сохранить" должна активироваться, если заполнено хотя бы одно поле. При клике на кнопку "сохранить" (пока) модал должен закрываться.

**Comment by bigKingPenguin** [comment]
Теперь нужно доработать навбар (components/header/navigation/Sidebar.vue):


![Image](https://github.com/openworld-community/ows-events/assets/124285205/ca6588ba-e6f0-4d1a-92e5-2f82f86a9663)

Элемент "Авторизоваться/Выйти" уже не нужен.
Вместо него должен остаться элемент "Авторизоваться/Пользователь", который динамически меняется в зависимости от авторизации. 
Иконка тоже должна меняться: для "авторизоваться" иконка с названием "login" стандартного серого цвета, для "пользователь" - иконка с названием "user" (для нее должен быть color-accent-green-main)

**Comment by bigKingPenguin** [comment]
### Критерии готовности
- **Критерии готовности задачи**  
1. Добавляется новая страница
2. Если пользователь не авторизован, на ней размещена кнопка авторизации
3. При авторизации размещена инфо о пользователе (имя, фамилия, никнейм - как в информации в телеграмме)
4. Ее можно отредактировать: при нажатии на кнопку редактирования открывается форма, после изменения и сохранения обновляется информация на юзер пейдж (после обновления страницы инфо не отличается)

**Comment by KemSummons** [comment]
Тесты на Chrome и Firefox. Safari решили вместе с Эмилией тестить вместе в отдельном виде, так как у меня iOSа нет.

1. Добавляется новая страница - ☑️
2. Если пользователь не авторизован, на ней размещена кнопка авторизации - ☑️
3. При авторизации размещена инфо о пользователе (имя, фамилия, никнейм - как в информации в телеграмме) - ☑️
4. Ее можно отредактировать: при нажатии на кнопку редактирования открывается форма, после изменения и сохранения обновляется информация на юзер пейдж (после обновления страницы инфо не отличается) - ☑️

В целом по браузерам:
Chrome - ☑️
Firefox - ☑️
Safari - ⏳ (в работе)

p.s. вопрос по 3 пункту критериев приемки. Предполагаю, что все данные о пользователе (имя, фамилия, никнейм) берутся из телеграма только при **первой** авторизации. Если же мы авторизуемся второй и т.д. раз, либо же авторизуемся с другого устройства/браузера, то данные остаются такими, какими их указал пользователь в форме редактирования профиля, т.е. уже без учета того, что указано в телеграме. Возможно, стоит это прописать в критериях приемки, т.е. в следующем виде:
3. При первой авторизации размещена инфо о пользователе (имя, фамилия, никнейм - как в информации в телеграмме). При второй и последующих авторизациях (на любом устройстве/браузере) инфо о пользователе остается в том виде, в каком ее сохранил/оставил без изменений пользователь.

**Comment by bigKingPenguin** [comment]
Да, по п. 3 ты все правильно написал. 
Все ли ок при первой авторизации? Инфо из телеграмма подставляется?

**Comment by KemSummons** [comment]
Да, все работает в соответствии с критериями приемки.
