### ISSUE TITLE
Добавить swagger-схему на эндпоинт аутентификации через телеграм

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#532]
### Задача
Нужно добавить swagger-схему на эндпоинт `/api/auth/telegram`

### Имеющиеся данные

- **Формат запроса**
Данный эндпоинт принимает GET-запрос с querystring типа [TGUser](https://github.com/openworld-community/ows-events/blob/main/common/types/user.ts)

- **Формат ответа**
Данный эндпоинт редиректит на страницу `frontend_url/postauth/:token`

### Порядок выполнения задачи
1. Создать файл schema.ts в директории backend/src/rest/v1/auth
2. Наполнить его по образцу других файлов schema.ts в подпапках backend/src/rest/v1 ([пример](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/location/schema.ts))
3. В файле [router.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/auth/router.ts) в директории backend/src/rest/v1/auth импортировать созданный на предыдущем шаге объект
4. В файле [router.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/auth/router.ts) в директории backend/src/rest/v1/auth в обработчике маршрута `/telegram` заменить обработчик `telegramLogin` на объект вида `{schema: schema, handler: handler}`
5.  Протестировать конкретно этот механизм не получится, так что просто убедитесь, что dev-сервер запускается

### Критерии готовности
- **Критерии готовности задачи**
Эндпоинт принимает запросы и отправляет ответ в том же виде, что и сейчас
Эндпоинт появляется в автогенерируемой документации swagger

- **Критерии готовности кода**
Код проходит автоматизированные проверки
Получен approve пулл реквеста от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>  
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.  
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>  
5. Запросить код ревью от лида команды   
6. Дождаться аппрува от лида команды  
7. Смержить пуллреквест в ветку <b><em>main</em></b>  
8. Закрыть задачу  
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main  
    2. Влить данную ветку в ветку, с которой вы работали изначально  
    3. Создать пуллреквест в ветку **<em>main</em>**   
    4. Дождаться аппрува от лида команды  
9. Принять благодарность от лида команды и всей команды Afisha Peredelano  
</details>

**Comment by HugeLetters** [comment]
### Задача
Нужно добавить swagger-схему на эндпоинт `/api/auth/telegram`

### Имеющиеся данные
**Формат запроса**
Данный эндпоинт принимает GET-запрос с querystring типа [TGUser](https://github.com/openworld-community/ows-events/blob/main/common/types/user.ts)

**Формат ответа**
Данный эндпоинт редиректит на страницу `frontend_url/postauth/:token`

### Порядок выполнения задачи
1. Создать файл schema.ts в директории backend/src/rest/v1/auth
2. Наполнить его по образцу других файлов schema.ts в подпапках backend/src/rest/v1 ([пример](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/location/schema.ts))
3. В файле [router.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/auth/router.ts) в директории backend/src/rest/v1/auth импортировать созданный на предыдущем шаге объект
4. В файле [router.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/auth/router.ts) в директории backend/src/rest/v1/auth в обработчике маршрута `/telegram` заменить обработчик `telegramLogin` на объект вида `{schema: schema, handler: handler}`
5.  Протестировать конкретно этот механизм не получится, так что просто убедитесь, что dev-сервер запускается

### Критерии готовности

**Критерии готовности задачи**
Эндпоинт принимает запросы и отправляет ответ в том же виде, что и сейчас
Эндпоинт появляется в автогенерируемой документации swagger

**Критерии готовности кода**
Код проходит автоматизированные проверки
Получен approve пулл реквеста от ревьюера
<details>
  <summary>Порядок работы с git</summary>

  1. В интерфейсе задачи, справа от описания, в графе _Assignees_ нажать на ссылку _assign yourself_
2. Отбранчеваться (создать ветку) от ветки **_main_**. Пожалуйста, при работе с гитом этого репозитория следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на наименование веток.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку **_main_**
5. Запросить код ревью от лида команды 
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку **_main_**
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **_main_** 
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano

</details>
