### ISSUE TITLE
Сделать лендосы для саб сервисов

### ISSUE THREAD

**Issue by OSKotelianets** [openworld-community/ows-events#550]
https://docs.google.com/document/d/1VODi8TAv_TXDmxK9KSZT9Q1cpYIQ2R734LmCnVSExjk/edit

**Comment by valentinudovik** [comment]
https://docs.google.com/document/d/1VODi8TAv_TXDmxK9KSZT9Q1cpYIQ2R734LmCnVSExjk/edit
