### ISSUE TITLE
Добавить поле address в location ивента.

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#562]
Подзадача задачи #381 для бэкенда

### Задача
Добавить поле `address` в `location` ивента в схеме базы данных.
Добавить поле `address` в `location` ивента в типе, описывающем ивент.
Добавить поле `address` в `location` ивента в схеме для Swagger

### Имеющиеся данные
Тип `EventOnPoster` в файле [`common/types/event.ts`](https://github.com/openworld-community/ows-events/blob/main/common/types/event.ts)  
Схема БД `schema` в файле [`backend/src/models/event.model.ts`](https://github.com/openworld-community/ows-events/blob/main/backend/src/models/event.model.ts)  
Элемент схемы Swagger `ItemEvent` в файле [`backend/src/rest/v1/events/schema.ts`](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/schema.ts)

### Порядок выполнения задачи
1. Добавить поле `location.address` в тип `EventOnPoster` (файл [`common/types/event.ts`](https://github.com/openworld-community/ows-events/blob/main/common/types/event.ts))
2. Добавить поле `location.address` в переменную `schema` (файл [`backend/src/models/event.model.ts`](https://github.com/openworld-community/ows-events/blob/main/backend/src/models/event.model.ts)), со следующими ограничениями: `{type: String}` (не делать его обязательным)
3. Добавить поле `location.address` в переменную `ItemEvent` (файл [`backend/src/rest/v1/events/schema.ts`](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/schema.ts)) со следующими ограничениями: `{type: 'string'}`
3. Проверить, что сервер запускается, отвечает на запросы по адресам `/api/events/:id`, `/api/events`, `api/events/add`, `api/events/find`

### Критерии готовности
- **Критерии готовности задачи**  
Сервер отвечает данными об ивенте (поле `location.address` - не обязательно должно присутствовать) на запрос по адресу `/api/events/:id` 
Сервер отвечает списком ивентов (поле `location.address` - не обязательно должно присутствовать) на запрос по адресу `/api/events` 
Сервер отвечает id ивента (при добавлении ивента с полем `location.address`) на запрос по адресу `/api/events/add` 
Сервер отвечает списком ивентов (поле `location.address` - не обязательно должно присутствовать) на запрос по адресу `/api/events/find` 

- **Критерии готовности кода**  
Код запускается в dev-окружении
Код прошел review от @il12 

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by Dichell** [comment]
Задача видмо была сделана ранее.
Все поля из задачи прописаны и сервер отдает location.

**Comment by il12** [comment]
> Задача видмо была сделана ранее. Все поля из задачи прописаны и сервер отдает location.

Поправил описание, прошу прощения. Добавить нужно поле `address` в `location`
