### ISSUE TITLE
Санитайзер - для парсера ивентов от Переделано

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#590]
### Задача
Подключить плагин-санитайзер

### Имеющиеся данные

https://www.npmjs.com/package/nuxt-sanitize-html

### Порядок выполнения задачи
Подключить библиотеку, поменять вставку разметки через v-html, используя функцию санитайзера

### Критерии готовности
- **Критерии готовности задачи**  
Укажите критерии готовности задачи (что могут протестировать тестировщики)

Можно протестировать только на одном устройстве (мобайл или десктоп)
- [ ] у мероприятий Переделано отображается описание мероприятия (та часть, что идет после даты, адреса и цены)

- **Критерии готовности кода**  
Укажите каким критериям должен соответствовать код (например, что получен approve от ревьюера) 

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by Anaisnet** [comment]
Наша подстраховка от взлома Гитхаба Переделано и приходящих от них плохих данных по ивентам Переделано.
Используется наш парсер Гитхаба Переделано.

Сложность: 2.
Актуальность: средняя.
Очередность: после внедрения нашего парсера.

**Comment by KemSummons** [comment]
Проверено

**Comment by bigKingPenguin** [comment]
Обнаружены неучтенные проблемы: 
1. В спаршенных ивентов Peredelano в meta description вставляется разметка html и некорректно отображается в поисковиках:

![Image](https://github.com/openworld-community/ows-events/assets/124285205/ac4f6937-ad59-4bd7-8aeb-0ef7b2ad7b00)

2. В спаршенных ивентов Peredelano в описании, где вставляется html-разметка, может вставляться тег h1, что негативно сказывается на SEO (т.к. на странице уже есть h1 - название мероприятия)

Необходимо вставить универсальное описание для спаршенных ивентов Peredelano: "Мы собираемся, чтобы помогать другим и себе. Классический формат, индустриальные и развлекательные доклады, нетворкинг, активности и упор на сообщество."
Необходимо настроить замену h1 на h2 в санитайзере

Тестирование (достаточно только десктопа):

- [ ] На [сайте проверки seo ](https://www.seobility.net/en/seocheck/) вставить для анализа ссылку на [Perepelanoconf в Тбилиси ](https://test.afisha.peredelano.com/ru/event/Peredelanoconf-Tbilisi-2024-01-13) и проанализировать: в самом низу результатов найти Search preview - текст описания должен соответствовать указанному выше
- [ ] Открыть разметку на странице мероприятия [Perepelanoconf в Тбилиси ](https://test.afisha.peredelano.com/ru/event/Peredelanoconf-Tbilisi-2024-01-13): в описании мероприятия отсутствуют теги <h1>

**Comment by KemSummons** [comment]
Проверено
