### ISSUE TITLE
При вводе запроса в поисковую строку выдает результат только на целое слово, на часть слова - результата нет. 

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#597]
ЗАДАЧА ДЛЯ БЭКЭНДА
На скрине ниже прикрепляю, если вводить "post" - результата нет, хотя ивенты с таким названием есть. Если вводить "postman" - результат будет. 
![Esxv8dGk3a](https://github.com/openworld-community/ows-events/assets/116894308/27588270-5635-46e0-b4b0-9bfb46d5ac95)

**Comment by Jus1x-by** [comment]
https://github.com/openworld-community/ows-events/pull/642
