### ISSUE TITLE
Использовать метод сжатия GZip в Nuxt

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#604]
### Задача
Изучить варианты с использованием сжатия в ответах nuxt и добавить его

### Имеющиеся данные
[Вариант](https://stackoverflow.com/questions/72882000/how-do-i-make-my-nuxt-app-v3-serve-mjs-br-brotli-files-instead-of-the-regul/73670394#73670394), который удалось найти, которой возможно решает эту проблему 

### Порядок выполнения задачи
Изучить варианты сжатия ответов nuxt методом GZip (gz)

### Критерии готовности
- **Критерии готовности задачи**  
HTML-страницы от nuxt отдаются с использованием метода сжатия GZip (протестировать @bigKingPenguin )

- **Критерии готовности кода**  
Получен approve от @bigKingPenguin

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by bigKingPenguin** [comment]
Добавила по описанному https://github.com/nuxt/nuxt/issues/14794, но сжатие идет не для всех файлов, после подключения [модуля сжатия](https://github.com/Baroshem/compression) тоже ничего не поменялось.

@il12 возможно все-таки что-то на бэке нужно еще сделать?
