### ISSUE TITLE
В сафари при вводе невалидной ссылки на ивент - мероприятие сохраняется и отправляется на модерацию.

### ISSUE THREAD

**Issue by IanaBlinova** [openworld-community/ows-events#608]
https://github.com/openworld-community/ows-events/assets/116894308/e7ae3b49-e47c-49a1-8633-93b5cb26c495

**Comment by vealruk** [comment]
Обнаружилась проблема с различной обработкой поля ввода типа url в разных браузерах. В частности, браузер Chrome требует полный URL, включая протокол и домен, тогда как Firefox и Safari позволяют отправить форму даже с неполным URL.
Данная проблема будет учтена в рамках задачи по валидации.

**Comment by bigKingPenguin** [comment]
#556

**Comment by Anaisnet** [comment]
Сложность: не известна (на исследовании).
Критичность: низкая.
Скорее как техдолг будет - тема валидации форм ивентов.
