### ISSUE TITLE
Разработка компонента filter

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#615]
### Задача
Разработать компонент filterItem в соответствии с макетом

### Имеющиеся данные
Использовать компонент СommonUISelect, добавив ему kind: 'filter' и необходимые стили
Для открывающегося списка использовать vue-final-modal

### Порядок выполнения задачи
1. Разработать компонент фильтра
2. Подключить его к фильтру стран и городов

### Критерии готовности
- **Критерии готовности задачи**  
Укажите критерии готовности задачи (что могут протестировать тестировщики)

- **Критерии готовности кода**  
Укажите каким критериям должен соответствовать код (например, что получен approve от ревьюера) 

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
3. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
4. Выполнить задачу по секции "Порядок выполнения задачи"
5. Создать пуллреквест в ветку <b><em>main</em></b>
6. Запросить код ревью от лида команды
7. Дождаться аппрува от лида команды
8. Смержить пуллреквест в ветку <b><em>main</em></b>
9. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
10. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

Story points: 2

**Comment by Anaisnet** [comment]
Задача была начата, но был изменён дизайн. В процессе доделки, в основном в рамках разработки фильтра по тегам.

**Comment by KemSummons** [comment]
Проверено
