### ISSUE TITLE
Спроектировать пользовательский сценарий покупки/участия в мероприятии для обеих ролей

### ISSUE THREAD

**Issue by valentinudovik** [openworld-community/ows-events#616]
1. Что видит пользователь, когда нажимает на CTA в ивент пейдже? 
2. Что видит организатор, когда пользователь присоединяется к мероприятию? 
3. Как пользователь оплачивает билет, если мероприятие платное? На какой платформе это происходит? Куда ведет редирект? 
4. Как отображается информация о посетителеях мероприятия у организатора? Что это за информация? Из чего она состоит?
5. Могут ли связываться организатор и пользователь между собой прямо на платформе?

**Comment by il12** [comment]
План места в яндексе 
[yandex-hallplanDisplay.txt](https://github.com/openworld-community/ows-events/files/12214001/yandex-hallplanDisplay.txt)
