### ISSUE TITLE
Задизайнить кнопку с переводом на странице ивента

### ISSUE THREAD

**Issue by valentinudovik** [openworld-community/ows-events#617]

**Comment by valentinudovik** [comment]
![Image](https://github.com/openworld-community/ows-events/assets/53011108/b0dba43a-1577-4ff3-bbd0-7ddbaa0e0338)

**Comment by valentinudovik** [comment]
@bigKingPenguin добавил кнопочку

**Comment by bigKingPenguin** [comment]
Дублирую комментарий из фигмы:
Эта кнопка должна быть статичной вместе с нижними кнопками? Если да, то на экране останется совсем мало места для скроллящегося описания. А если она должна скроллиться вместе с описанием, то при длинном описании ее не будет видно, пока не проскроллить описание вниз
