### ISSUE TITLE
Добавить типы ивентов

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#621]
### Задача
Необходимо добавить разделение ивентов на бэкенде по типам: спаршенные, продвигаемые, пользовательские.

### Имеющиеся данные
Тип `EventOnPoster` в файле [common/types/event.ts](https://github.com/openworld-community/ows-events/blob/main/common/types/event.ts) 
Схема БД в файле [backend/src/models/event.model.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/models/event.model.ts)
Обработчик создания ивента `addEvent` в файле [backend/src/rest/v1/events/controller.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/controller.ts)
Переменная `ItemEvent` в Swagger-схеме в файле [backend/src/rest/v1/events/schema.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/schema.ts)
Дамп БД для тестирования миграций (напишите в личку @il12 в дискорде (никнейм в дискорде - iskopaem0e))

### Порядок выполнения задачи
1. В папке `common/const` создать файл `eventTypes` экспортирующий enum со значениями `parsed`, `paid`, `user-generated`.
2. В тип `EventOnPoster` в файле [common/types/event.ts](https://github.com/openworld-community/ows-events/blob/main/common/types/event.ts) добавить поле `type`, которое может принимать значения из enum, созданного на предыдущем шаге.
3. В схему БД в файле [backend/src/models/event.model.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/models/event.model.ts) добавить поле `type`, которое может принимать значения из enum, созданного на первом шаге.
4. В переменную `ItemEvent` в Swagger-схеме в файле [backend/src/rest/v1/events/schema.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/schema.ts) добавьте поле `type` с типом `string`
4. В обработчике создания ивента `addEvent` в файле [backend/src/rest/v1/events/controller.ts](https://github.com/openworld-community/ows-events/blob/main/backend/src/rest/v1/events/controller.ts) добавить проверку, на то, что ивент был создан парсером (`creatorId === parser`) и в этом случае добавлять к ивенту поле `type` со значением `parsed` (используйте enum, созданный на первом шаге). В противном случае - добавляйте к ивенту поле `type` со значением `user-generated` (используйте enum, созданный на первом шаге).
5. Создайте миграцию, которая добавляет поле `type` к уже существующим записям в БД. Логика присвоения значений аналогична предыдущему шагу.

### Критерии готовности
- **Критерии готовности задачи**
При создании ивента определяется и сохраняется его тип
При запросе ивента/ивентов поле `type` присутствует в ответе  
Миграция проходит успешно

- **Критерии готовности кода** 
Код проходит автоматические проверки гитхаба
Код работает на локальном окружении 
Код прошел ревью @il12 

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by il12** [comment]
Для QA: 
Во внутренней структуре ивента должно быть поле `type`, со значениями `parse, paid или user-generated`. Проверить можно посмотрев ответ сервера по любому API, возвращающему ивент или массив ивентов.

**Comment by KemSummons** [comment]
Проверено
