### ISSUE TITLE
Добавить в форму создания ивентов страны

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#643]
### Задача
Добавить новые страны присутствия: Черногория, Кыргызстан

### Имеющиеся данные
В форме создания ивента уже прибита вручную Сербия, необходимо добавить еще 2 страны (вручную, без запроса к бэку)

### Порядок выполнения задачи
1. добавить страны в location.store
2. разблокировать поле выбора страны в форме создания ивента
3. проверить, что страны появляются в поле выбора, а также корректно подтягиваются города и таймзоны

### Критерии готовности
- **Критерии готовности задачи**  
1. При создании ивентов можно выбрать одну из трех стран: Сербия, Черногория, Кыргызстан
2. При выборе страны корректно подтягивается список городов выбранной страны и определяется таймзона
3. В фильтрах на главной странице корректно отображаются страны и города присутствия

- **Критерии готовности кода**  
Получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
4. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
5. Выполнить задачу по секции "Порядок выполнения задачи"
6. Создать пуллреквест в ветку <b><em>main</em></b>
7. Запросить код ревью от лида команды
8. Дождаться аппрува от лида команды
9. Смержить пуллреквест в ветку <b><em>main</em></b>
10. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    4. Влить данную ветку в ветку, с которой вы работали изначально
    5. Создать пуллреквест в ветку **<em>main</em>**
    6. Дождаться аппрува от лида команды
11. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
Критерии готовности задачи:
1. При создании ивентов можно выбрать одну из трех стран: Сербия, Черногория, Кыргызстан - ☑️
2. При выборе страны корректно подтягивается список городов выбранной страны и определяется таймзона - ☑️ (проверял примерно по 7-10 городов, по принципу классов эквивалентности должно отрабатывать корректно. Проверить наличие каждого населенного пункта на предмет присутствия на сайте - очень тяжело)
3. В фильтрах на главной странице корректно отображаются страны и города присутствия - ☑️

В целом по браузерам:
Chrome - ☑️
Firefox - ☑️
Safari - ⏳ (в работе)

**Comment by KemSummons** [comment]
Критерии 1 и 3 ок.

Во втором критерии есть следующий баг:
- на экране создания мероприятия выбрать любые страну и город (автоматически подтягивается таймзона);
- в поле выбора страны выбрать другую страну (кликать не на крестик, а на левую часть поля);
- обратить внимание на то, что страна и таймзона меняются, а город не меняется
как варианта решения: сделать все поле, включая крестик - одной кнопкой, которая будет автоматически очищать уже выбранное и показывать выпадающий список
https://drive.google.com/file/d/1L3JnZq72ZHK1DY0m81HTxHS7_e-HD058/view
P.s. баг воспроизводится и на тесте, и на демо!

**Comment by KemSummons** [comment]
@bigKingPenguin 
Пофикшено на тесте, на демо все еще воспроизводится

**Comment by bigKingPenguin** [comment]
@KemSummons так мы на демо еще не заливали эти правки
