### ISSUE TITLE
Добавить в форму создания ивентов валюты

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#645]
### Задача
Добавить в форму создания ивента выбор валюты (USD, EUR, RSD, KGS) и криптовалюты (BTC, USDT, USDC, ETH). Добавить галочку "бесплатно"

### Имеющиеся данные
Макет в фигме:
<img width="202" alt="Снимок экрана 2023-08-07 в 17 33 55" src="https://github.com/openworld-community/ows-events/assets/124285205/960c9ddf-197a-4051-8e22-4faca386e1fc">

### Порядок выполнения задачи
1. добавить валюты в location.store
2. добавить селект в форму создания ивента
3. создать компонент "check" в соответствии с макетом
4. добавить check "бесплатно", при выборе которого поля "стоимость" и "валюта" становятся неактивными, а данные для отправки price заполняются следующим образом:
```
price: {
maxValue: null,
value: 0,
minValue: null,
currency: null
}
```

Требования к функционалу см в "критерии готовности"

### Критерии готовности
- **Критерии готовности задачи**  
1. В форме создания ивента рабочее поле выбора валюты и check "бесплатно"
2. Пока не выбрана конкретная страна, поле валюты пустое, при выборе страны поле валюты предзаполнено в соответствии с валютой выбранной страны
3. Поля с ценой и выбором валюты неактивны, если выбран check "бесплатно"
4. При создании ивента корректно отображается цена и валюта, а при выбранном поле "бесплатно" появляется соответствующий тэг

- **Критерии готовности кода**  
Получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
6. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
7. Выполнить задачу по секции "Порядок выполнения задачи"
8. Создать пуллреквест в ветку <b><em>main</em></b>
9. Запросить код ревью от лида команды
10. Дождаться аппрува от лида команды
11. Смержить пуллреквест в ветку <b><em>main</em></b>
12. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    5. Влить данную ветку в ветку, с которой вы работали изначально
    6. Создать пуллреквест в ветку **<em>main</em>**
    7. Дождаться аппрува от лида команды
13. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by bigKingPenguin** [comment]
Беру на доработку

**Comment by KemSummons** [comment]
Проверено
