### ISSUE TITLE
Добавить отображение избранного и созданных мероприятий

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#662]
### Задача
1. Добавить кнопку добавления в избранное на странице мероприятия (показывается, если пользователь авторизован)
2. Добавить страницу "избранное" и "мои мероприятия" - переход на них по ссылкам с юзерпейджа (в соответствии с макетом в фигме)

### Имеющиеся данные
Юзерпейдж со ссылками-заглушками, страница ивента

### Порядок выполнения задачи
1. Добавить на страницу ивента кнопку для добавления/удаления избранного
2. Добавить разделы "мои мероприятия" и "избранное"

### Критерии готовности
- **Критерии готовности задачи**  
1. На странице мероприятия есть кнопка, которая добавляет/удаляет мероприятие в избранное
2. На странице пользователя есть ссылки, ведущие на разделы "избранное" и "мои мероприятия" (отражаются созданные мероприятия)
3. Если пользователь не авторизован, эти разделы не открываются, происходит редирект на страницу пользователя
4. Если нет избранных или созданных мероприятий, на этих страницах имеется надпись, что еще нет мероприятий, если такие мероприятия есть - отображаются карточки соответствующих мероприятий
5. Карточки мероприятий - это ссылки, которые ведут на страницу соответствующего мероприятия

- **Критерии готовности кода**  
получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
3. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
4. Выполнить задачу по секции "Порядок выполнения задачи"
5. Создать пуллреквест в ветку <b><em>main</em></b>
6. Запросить код ревью от лида команды
7. Дождаться аппрува от лида команды
8. Смержить пуллреквест в ветку <b><em>main</em></b>
9. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
10. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
Проверено
