### ISSUE TITLE
Доработать блок пользователя

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#679]
### Задача
Доработать юзерпейдж в соответствии с макетом

### Имеющиеся данные
Макет в фигме

### Порядок выполнения задачи

- [x] 1. Доработать страницу авторизации
- [x] 2. Добавить ссылку на страницу донатов
- [x] 3. Поменять иконки в ссылках на избранное и мои мероприятия
- [x] 4. Вставить картинки для пустых экранов избранного и моих мероприятий
- [x] 5. Сделать поле "Никнейм" обязательным в форме

### Критерии готовности
- **Критерии готовности задачи**  
Верстка блока пользователя соответствует макету

- **Критерии готовности кода**  
Получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
5. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
6. Выполнить задачу по секции "Порядок выполнения задачи"
7. Создать пуллреквест в ветку <b><em>main</em></b>
8. Запросить код ревью от лида команды
9. Дождаться аппрува от лида команды
10. Смержить пуллреквест в ветку <b><em>main</em></b>
11. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
12. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
1. Доработать страницу авторизации - ☑️ 
 2. Добавить ссылку на страницу донатов - ☑️ 
 3. Поменять иконки в ссылках на избранное и мои мероприятия - ☑️ 
 4. Вставить картинки для пустых экранов избранного и моих мероприятий - ☑️ 
 5. Сделать поле "Никнейм" обязательным в форме - ☑️ 

В целом по браузерам:
Chrome - ☑️
Firefox - ☑️
Safari - ⏳ (в работе)

p.s. Вопрос - у нас в макете на страницах Мои мероприятия и Избранное есть фильтрационные выпадающие окна (Тема, дата и цена). На тестовом сайте их пока нет, т.е. у нас просто идут страницы Мои мероприятия и Избранное, без возможности фильтровать ивенты. Относится ли этот момент к данной таске?

**Comment by bigKingPenguin** [comment]
@KemSummons пока не добавляли фильтрацию, т.к. это объемная задача и для фронта, и для бэка. Скорее всего будет реализована уже после того, как доделаем фильтрацию на главной странице
