### ISSUE TITLE
Сверстать футер

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#686]
### Задача
Сверстать футер в соответствии с макетом

### Имеющиеся данные
Макет в фигме

### Порядок выполнения задачи
1. Создать компонент футер
2. Подключить его как layout в app.vue
3. Отображать его только на главной странице мобилки

### Критерии готовности
- **Критерии готовности задачи**  
1. футер на главной странице соответствует макету
2. все ссылки рабочие и ведут на соответствующие страницы

- **Критерии готовности кода**  
получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
4. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
5. Выполнить задачу по секции "Порядок выполнения задачи"
6. Создать пуллреквест в ветку <b><em>main</em></b>
7. Запросить код ревью от лида команды
8. Дождаться аппрува от лида команды
9. Смержить пуллреквест в ветку <b><em>main</em></b>
10. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    3. Влить данную ветку в ветку, с которой вы работали изначально
    4. Создать пуллреквест в ветку **<em>main</em>**
    5. Дождаться аппрува от лида команды
11. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
Проверено
