### ISSUE TITLE
Создать стейты для интерактивных элементов

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#688]
### Задача
Для кликабельных элементов (кнопок, ссылок, инпутов) доработать стейты в соответствии с UI-kit

### Имеющиеся данные
UI-kit в фигме

### Порядок выполнения задачи
1. Создать тип кнопки 'text'
2. Добавить стейты для кнопок-иконок
3. Добавить стейты для ссылок на странице пользователя, в избранном и моих мероприятиях
4. Отредактировать disabled состояние для инпутов

### Критерии готовности
- **Критерии готовности задачи**  
Все интерактивные элементы имеют состояния hover, active и (где применимо) disabled

- **Критерии готовности кода**  
Получен approve от ревьюера 

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
5. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
6. Выполнить задачу по секции "Порядок выполнения задачи"
7. Создать пуллреквест в ветку <b><em>main</em></b>
8. Запросить код ревью от лида команды
9. Дождаться аппрува от лида команды
10. Смержить пуллреквест в ветку <b><em>main</em></b>
11. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
12. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
@bigKingPenguin 
_Критерии готовности задачи:
Все интерактивные элементы имеют состояния hover, active и (где применимо) disabled_
Это очень тяжелая формулировка для проверки. Слишком велик шанс что-то упустить или не заметить.
Предлагаю следующий вариант: я сделаю список элементов, которые найду, с которыми может взаимодействовать пользователь, с скриншотами и припиской возможных состояний. Вместе глянем, добавим нужное/уберем ненужное, и после я уже протестирую по составленному списку. Это более надежно и понятно.
p.s. сразу вопрос - все ли элементы сайта выполнены в точности как в макете фигмы или там не совсем актуальная информация? Т.е. - могу ли я на 100 % опираться на макет в фигме при проверках?

**Comment by bigKingPenguin** [comment]
@KemSummons Текущие кнопки и ссылки сделаны в соответствии с UI-kit в фигме. У нас есть четые вида кнопок (красные, зеленые, серые и текстовые без бордера), плюс кнопки-иконки, а также инпуты. Для этих типовых элементов все состояния прописаны в одном месте, и дальше по коду они вставлены в виде компонентов (то есть выглядят одинаково). 
Ссылки стилизованы отдельно (но не отрисованы состояния ссылок на местоположение мероприятий, а ссылки в навбаре и ссылку-лого отрисовывала я, без дизайна). 
Может быть эта информация облегчит тебе задачу

**Comment by KemSummons** [comment]
Проверено
