### ISSUE TITLE
Redundant countries

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#690]
**Describe the bug**
Redundant countries (where all events already finish) on main page in filter

**Comment by il12** [comment]
Для QA:
Был баг, при котором в поле для фильтрации по стране появлялись страны, в которых не было ни одного ивента. Причина была в том, что у нас на главной странице не показываются прошедшие ивенты. А страны в фильтре не были ограничены только будущими ивентами. Например, если в Турции был один ивент и он уже прошел, Турция все равно попадала в список стран по которым можно было фильтровать ивенты

**Comment by KemSummons** [comment]
Исправлено
