### ISSUE TITLE
Добавить поле "организатор" в данные ивента

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#694]
### Задача
Добавить необязательное поле "организатор" в ивент

### Имеющиеся данные
Тип данных 
Схема БД
Сваггер-схема

### Порядок выполнения задачи
Добавить поле "организатор" в ивент

### Критерии готовности
- **Критерии готовности задачи**  
У ивента есть необязательное поле "организатор"
Если заполнено поле "организатор" на странице пользователя, данные автоматически подтягиваются в форму, но их можно изменить при создании мероприятия
Если поле "организатор" было заполнено при создании мероприятия, информация об организаторе отображается в карточке и на странице мероприятия

- **Критерии готовности кода**  
Пройдены проверки гитхаба
Получен аппрув

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
1. В форме создания ивента есть необязательное поле "организатор" - ✅
2. Если заполнено поле "организатор" на странице пользователя, данные автоматически подтягиваются в форму, но их можно изменить при создании мероприятия - ✅
3. Если поле "организатор" было заполнено при создании мероприятия, информация об организаторе отображается в карточке и на странице мероприятия - 🚫 (не создается ивент). Ждал минут 10. Либо нет прав на создание ивента, либо проблемы с сохранением инфы в полях и публикацией ивента. Также стоит проверить БД, возможно, данные записываются на беке, но визуально не прогружаются.

В целом по браузерам:
Chrome - 2/3 ⏳ (в работе)
Firefox - 2/3 ⏳ (в работе)
Safari - 0/3 ⏳ (в работе)

**Comment by bigKingPenguin** [comment]
@KemSummons временно не работает создание мероприятий на тесте из-за сервиса переводов, Игорь даст информацию, когда починит

**Comment by KemSummons** [comment]
1. В форме создания ивента есть необязательное поле "организатор" - ✅
2. Если заполнено поле "организатор" на странице пользователя, данные автоматически подтягиваются в форму, но их можно изменить при создании мероприятия - ✅
3. Если поле "организатор" было заполнено при создании мероприятия, информация об организаторе отображается в карточке и на странице мероприятия - ✅

В целом по браузерам:
Chrome - 3/3 ⏳ (в работе)
Firefox - 3/3 ⏳ (в работе)
Safari - 0/3 ⏳ (в работе)

p.s. Вопрос по такому моменту. У нас в профиле указано название организации, например, A. Мы создаем ивент, туда автоматически подтягивается название организации А. После мы идем в личный кабинет и меняем название организации на Б. Создаем новый ивент, туда подтягивается название организации Б. При этом, в первом ивенте остается название организации А. Как я понимаю, это статичные данные и они меняются только вручную, так и должно работать? Т.е. у нас не происходит автоматического обновления названия организации в уже созданных ивентах.

**Comment by bigKingPenguin** [comment]
@KemSummons так и было задумано, да. Потому что в конкретный момент пользователь создает мероприятие от имени конкретного организатора. 
Живой пример: у нас есть всемирный организатор Peredelano и локальный для РФ Reworked. Если Peredelano создает несколько мероприятий от этого имени, а потом меняет название, чтобы создать несколько мероприятий Reworked, название организатора первых мероприятий меняться не должно.

**Comment by KemSummons** [comment]
Проверено
