### ISSUE TITLE
(Демо) Все срочные задачи для Тестирования - ещё раз.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#704]
**Тестирование Бэкэнда**

2. https://github.com/openworld-community/ows-events/issues/690

### Критерии приемки
Критерии внутри задач
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность

- Сложность 1.
- Объём 2-3 дня.
- Риски 0.

**Comment by KemSummons** [comment]
По состоянию на 11.10.2023:
https://github.com/openworld-community/ows-events/issues/521 - ☑️ (кроме Сафари)
https://github.com/openworld-community/ows-events/issues/694 - ☑️ (кроме Сафари)
https://github.com/openworld-community/ows-events/issues/679 - ☑️ (кроме Сафари)
https://github.com/openworld-community/ows-events/issues/662 - ☑️ (кроме Сафари)
https://github.com/openworld-community/ows-events/issues/645 - ❌ требует доработки
https://github.com/openworld-community/ows-events/issues/643 - ☑️ (кроме Сафари)
