### ISSUE TITLE
Текстовые недочёты

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#705]
**Describe the bug**
Все недочёты собраны QA Александром в 1 файле:
https://docs.google.com/document/d/17SkB6pHRjy3W7lRUg8jg7U7O7paGjh4WFM2EqdHXxQg

**Additional context**
Так же есть небольшие замечания юридического характера.

story points: 1

**Comment by bigKingPenguin** [comment]
Вопрос по пункту 5: Как будто хочется звездочку именно рядом с названием строки, а не в поле ввода. Более привычно, что ли.
Проблема в том, что у нас есть в некоторых местах одно название на несколько строк, в котором могут быть и обязательные, и необязательные поля
<img width="425" alt="Снимок экрана 2023-10-02 в 15 24 46" src="https://github.com/openworld-community/ows-events/assets/124285205/07888757-0a8f-44df-bb71-eccc8db76de1">
Придется пока оставить как есть, а в новом формате создания мероприятий (постраничное) нужно это учесть @valentinudovik

**Comment by KemSummons** [comment]
@bigKingPenguin я в английском не силен, на уровне чтения со словарем, но запишу себе, проверю на этой неделе, после горящих тасков.

**Comment by KemSummons** [comment]
п. 7 раздела "Ограничение ответственности".
Пользователь и третьи лица обязуются урегулировать конфликты с Афишей во внесудебном порядке путём направления претензий по любым доступным каналам связи. В случае невозможности урегулировать конфликт в претензионном порядке, он подлежит урегулирован**ии** в соответствии с применимым законодательством.
Правильно будет - урегулированию.
p.s. сам недосмотрел в прошлый раз 

Все остальные недочеты устранены.

**Comment by KemSummons** [comment]
Исправлено
