### ISSUE TITLE
Внести все кнопки в UI-kit

### ISSUE THREAD

**Issue by valentinudovik** [openworld-community/ows-events#707]
Сделать всем новым кнопкам отдельные компоненты и стейты
**story points: 1**

**Comment by valentinudovik** [comment]
@bigKingPenguin оба UI кита пометил как ready for dev, кнопки в десктопном вынес наверх. если что-то забыл - напиши, пжл, коммент

**Comment by bigKingPenguin** [comment]
@valentinudovik оставила комментарии в фигме
