### ISSUE TITLE
10=Как организатор ивента, я хочу создавать онлайн ивенты, чтобы собирать людей со всего мира.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#717]
### Описание задачи
Предоставление пользователю возможности создания онлайн-мероприятия.
На такой странице пользователю не нужно будет указывать:
- страну, город
- место локации
Будет автоматом подставляться тег "онлайн ивент".

На будущее: 
- Будет дополнительное поле, для заполнения создателем ивента: "язык мероприятия"
- При создании ивента сам пользователь будет переходить на новую страницу - предпросмотр онлайн-ивента.
- На странице предпросмотра онлайн-ивента будут все те же кнопки и с тем же функционалом, что и для оффлайн ивента: удалить отредактировать выложить на сайт.

### Критерии приемки
Создание ивента
- [ ] При создании ивента даётся возможность присвоить мероприятию формат "Онлайн"
- [ ] При выборе формата онлайн, поля "Страна", "Город" и "Адрес" очищаются и отключаются (становятся недоступными для ввода).

~~- [ ] Максимально возможное количество выбранных тегов: 5~~

- [ ] Поля "Страна" и "Город" необязательны для ввода при выбранном формате "Онлайн" (отсутствует *, на бэк отправляются пустые строки)
- [ ] В поле "Часовой пояс" автоматически подставляется часовой пояс пользователя
- [ ] К мероприятию добавляется тэг "online", который нельзя убрать и который не виден в форме создания
- [ ] При нажатии кнопки "сохранить" все данные будут сохраняться в базе данных, пользователь будет перенаправляться на страницу мероприятия

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

1. 2-5
2. 5
3. 2

**Comment by bigKingPenguin** [comment]
Не изменяем максимально возможное количество выбранных тегов (оставляем 6), т.к. "онлайн" не будет виден в списке тегов [в карточке мероприятия ](https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2726-12232&mode=design&t=ohw6iBmOGG2qqP48-4)

**Comment by AlexeyPQA** [comment]
Проверено.
