### ISSUE TITLE
Как любой пользователь сайта, я хочу авторизоваться (логиниться на сайте) через Google аккаунт, т.к. мне так удобнее.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#726]
### Описание задачи
Любой пользователь может иметь возможность авторизоваться (логиниться) на сайте через Google аккаунт, т.к. так ему удобнее.

### Критерии приемки
- [ ] Любой пользователь сайта, уже зарегистрированный через Google на сайте, должен иметь возможность авторизоваться через Google аккаунт, выбрав кнопку Авторизоваться/Залогиниться.
- [ ] Если пользователь раньше не регистрировался через Google аккаунт и он выбрал авторизацию через Google аккаунт, ему будет предложено зарегистрироваться через Google аккаунт.
- [ ] Если пользователь ранее уже регистрировался через Google аккаунт, он будет успешно авторизован и переброшен на гл. страницу сайта.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
