### ISSUE TITLE
Перенести форму создания мероприятия на отдельную страницу

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#741]
### Задача
Перенести все поля для заполнения и функции на отдельную страницу

### Имеющиеся данные
Весь код для создания мероприятия - в форме Event.client.vue 

### Порядок выполнения задачи

1. Создать новую страницу event form
2. Перенести на нее все данные из формы
3. Сделать кнопку "создать мероприятие" ссылкой на эту страницу
4. Добавить модалку для подтверждения закрытия формы при нажатии на кнопку "отмена"
5. Создать middleware, чтобы на эту страницу не мог попасть неавторизованный пользователь

### Критерии готовности

- [x] Кнопка "новое мероприятие" для неавторизованного пользователя ведет себя, как раньше (вызывает модал с информацией о необходимости авторизоваться), для авторизованного - редиректит на страницу "event form"
- [ ] При попытке неавторизованного пользователя вбить в поисковую строку ссылку на страницу "event form" происходит редирект на user page (unauthorized screen)
- [ ] Все поля на странице мероприятия работают, как раньше
- [x] При нажатии кнопки "отмена" или "назад" (если в форму были внесены изменения) появляется модал с предупреждением, что информация не будет сохранена (при подтверждении происходит редирект на предыдущую страницу; а при отмене пользователь остается на странице создания, при этом информация в инпутах сохраняется)
- [x] При нажатии кнопки "сохранить" (если заполнены все обязательные поля) мероприятие сохраняется, происходит редирект на страницу созданного мероприятия
- [x] При редактировании мероприятия также происходит переход на страницу event form, все поля предзаполнены информацией о мероприятии, страница ведет себя так же, как описано выше

- **Критерии готовности кода**  
получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
6. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
7. Выполнить задачу по секции "Порядок выполнения задачи"
8. Создать пуллреквест в ветку <b><em>main</em></b>
9. Запросить код ревью от лида команды
10. Дождаться аппрува от лида команды
11. Смержить пуллреквест в ветку <b><em>main</em></b>
12. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
13. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by bigKingPenguin** [comment]
Задача вылита на демо

**Comment by KemSummons** [comment]
1. Кнопка "новое мероприятие" для неавторизованного пользователя ведет себя, как раньше (вызывает модал с информацией о необходимости авторизоваться), для авторизованного - редиректит на страницу "event form" - ☑️
2. При попытке неавторизованного пользователя вбить в поисковую строку ссылку на страницу "event form" происходит редирект на user page (unauthorized screen) - ❌ не переводит на страницу пользователя, а выдает 500 localStorage is not defined https://drive.google.com/file/d/19V_t-zFqdGGP5CA6y3hnrfaIXGhTmy1a/view?usp=sharing
Если после пятисотки обновить страницу - тогда перенаправит на user page как и положено
3. Все поля на странице мероприятия работают, как раньше - ❓ очень неконкретный критерий, но я постарался все прокликать (обязательные и не очень поля). В идеале - надо поднять старый таск по проверке (если такой был) и по нему пробежаться, для надежности.
4. При нажатии кнопки "отмена" или "назад" (если в форму были внесены изменения) появляется модал с предупреждением, что информация не будет сохранена (при подтверждении происходит редирект на предыдущую страницу; а при отмене пользователь остается на странице создания, при этом информация в инпутах сохраняется) - ☑️
5. При нажатии кнопки "сохранить" (если заполнены все обязательные поля) мероприятие сохраняется, происходит редирект на страницу созданного мероприятия - ☑️
6. При редактировании мероприятия также происходит переход на страницу event form, все поля предзаполнены информацией о мероприятии, страница ведет себя так же, как описано выше (в пятом критерии?) - ☑️

**Comment by KemSummons** [comment]
https://docs.google.com/document/d/1l3WneMrYnWFQghmmWOp510bW6mTmws9g6XHtShmqKnE/edit
Правок и комментариев прилично, поэтому сделал в отдельном доке, доступ открыл.
Фиксить все что без галочек.

**Comment by bigKingPenguin** [comment]
@KemSummons баги пофикшены, дополнительные замечания откомментированы, правки залиты на тест и на демо

**Comment by KemSummons** [comment]
@bigKingPenguin проверено, баги пофикшены, моменты, которые остались:
1. скрол (ждем ответа дизайнеров)
2. поле ввода "Цены" принимает не только цифры (уже в обоих браузерах - см. комментарий в доке https://docs.google.com/document/d/1l3WneMrYnWFQghmmWOp510bW6mTmws9g6XHtShmqKnE/edit)
3. при выборе check "бесплатно" не удаляется цена
Думаю, надо еще у Аси спросить мнение, пушим с такими багами или нет.
