### ISSUE TITLE
Выпилить определение местоположения посетителя сайта.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#766]
### Описание задачи
Выпилить функционал определения местоположения посетителя сайта.

![Image](https://github.com/openworld-community/ows-events/assets/33966405/d31f202d-906f-446d-95e8-4724d1e18ab5)

### Критерии приемки
- [ ] При заходе на сайт и после релоуда не запрашивает определение вашей локации и не показывает "Мы не смогли найти вас".

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by bigKingPenguin** [comment]
#763
