### ISSUE TITLE
Исправить названия ссылок в хэдере и футере

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#767]
### Описание задачи
Навигация в хэдере:

![Image](https://github.com/openworld-community/ows-events/assets/33966405/3a5d173c-3dd7-41ac-9b01-bd9c404a3e5c)

Изменить на: "О проекте Поддержка Помочь Afisha" в хэдере и футере

### Критерии приемки
- [x] Наименования ссылок в хэдере: "О проекте, Поддержка, Помочь Afisha" (на английском "About the project, Support, Help Afisha")
- [ ] Наименования ссылок в футере: "О проекте, Поддержка, Помочь Afisha, Ограничение ответственности" (на английском "About the project, Support, Help Afisha, Limitation of liability")

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

story points: 1

**Comment by bigKingPenguin** [comment]
Сейчас в хэдере и футере ссылки называются "Об Афише", "Поддержка", "Помочь Afisha", что не соответствует описанию задачи. Необходимо исправить в русском и английской версии

**Comment by bigKingPenguin** [comment]
@KemSummons Проверено: названия ссылок в хэдере и футере соответствуют критериям приемки

**Comment by KemSummons** [comment]
@bigKingPenguin Исправлено только на тесте, на демо все еще Limitation of Liability :)

**Comment by bigKingPenguin** [comment]
@KemSummons так мы на демо еще не заливали эти правки
