### ISSUE TITLE
Правка по дизайну блока фильтров

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#770]
### Описание задачи
В Хэдере, у большой зеленой плашки убрать закругления:
![Image](https://github.com/openworld-community/ows-events/assets/33966405/68970996-2b33-489c-8a1a-4e305812eb43)

### Критерии приемки
- [ ] Зелёная плашка всегда выглядит в виде прямоугольника

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by bigKingPenguin** [comment]
Дизайн и верстка сделаны
