### ISSUE TITLE
Нарисовать страницы «О нас» и «помочь Афише».

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#772]
### Описание задачи
Нет страниц «о нас» и «помочь Афише», Эмилия их делала на глаз.

- [x] Обсудить с Эмилией.

- [x] Страница "О проекте": красиво расположить текст и кнопки соцсетей. Возможно отрисовать какую-то доп. картинку.
![Image](https://github.com/openworld-community/ows-events/assets/33966405/5d793624-da7c-4520-9eea-1303f8995401)

- [x] Страница «помочь Афише»: красиво расположить текст и кнопки на разные способы оплаты.
![Image](https://github.com/openworld-community/ows-events/assets/33966405/6dd53a9a-059a-452f-88ea-0516f39ad415)

### Критерии приемки

- [x] Отображение страницы должно соответствовать дизайну в Фигме: ...

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
Завершено, перенести на разработку по фронту!
