### ISSUE TITLE
Как создатель ивента, я хочу иметь возможность создавать ивенты прямо из ЛК и Мои мероприятия, тк не удобно постоянно возвращаться на главную страницу для создания ивента.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#781]
### Описание задачи
В Личном Кабинете и на странице "мои пероприятия" добавить кнопку для создания ивента. От Дизайнеров предварительно нужен вид кнопки в Фигме.

### Имеющиеся данные
1. функция, отрабатывающаяся при клике на кнопку "+" (вынести в хэлперы)
2. макеты в фигме
- мобайл 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9669&mode=design&t=F5ZMcWREXx9eVF4F-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9760&mode=design&t=F5ZMcWREXx9eVF4F-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9830&mode=design&t=F5ZMcWREXx9eVF4F-4
- десктоп
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1348-47072&mode=design&t=uhzZn1uubsITT1pY-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1366-60538&mode=design&t=uhzZn1uubsITT1pY-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1367-60901&mode=design&t=uhzZn1uubsITT1pY-4

### Критерии приемки
необходимо проверить на мобилке и десктопе
- [ ] Любой пользователь видит на главной странице кнопку "+"
- [ ] Авторизованный пользователь на странице пользователя и "мои мероприятия" видит кнопку "Создать мероприятие".
- [ ] При клике по этим кнопкам **авторизованный** пользователь попадает на отдельную страницу создания ивента.
- [ ] Верстка кнопок соответствует макету

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
в десктопной версии расположение кнопки "Добавить мероприятие" отличаетися от макета в Фигме, также отличается название кнопки: в фигме "Добавить новое мероприятие", а на тесте "Создать новое мероприятие".
