### ISSUE TITLE
Разработать добавление тэгов мероприятия при создании/редактировании мероприятия

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#783]
### Задача
В форме мероприятия добавить "чипсы" с категориями мероприятий 

### Имеющиеся данные
С бэка приходит [] с категориями

### Порядок выполнения задачи
При открытии формы получать список категорий из enum Tags
Отрисовать их в виде <input type="check"> (названия локализовать на фронте по ключам) по циклу
Можно нажимать теги, добавляя/удаляя категорию из массива тегов в eventStore
При выборе 6 категорий кнопки невыбранных тэгов переходят в состояние disabled
При редактировании, если у мероприятия уже есть категории, соответствующие кнопки дб нажаты

### Критерии готовности
- **Критерии готовности задачи**  

- [ ] в форме создания мероприятия имеются кнопки тэгов (Конференция, Фестиваль, Выставка, Театр, Стендап, Экскурсия, Лекция, Вечеринка, Мастер-класс, Спорт, Туризм, Праздник, Концерт, для детей, 18+)
- [ ] если создается новое мероприятие, при открытии формы категории тэгов не выбраны
- [ ] можно выбрать несколько категорий (не более 6)
- [ ] при выборе 6 категорий кнопки невыбранных тэгов переходят в состояние disabled, если после этого убрать один или больше тегов, кнопки невыбранных тэгов становятся активными
- [ ] при сохранении мероприятия на бэк отправляется информация о выбранных тэгах
- [ ] при редактировании мероприятия, при открытии формы выбраны те категории тэгов, которые были указаны в мероприятии
- [ ] если при редактировании мероприятий поменять последовательность тегов в массиве (убрать их и снова добавить в порядке, отличающемся от порядка в массиве, пришедшем с бэка), при попытке покинуть страницу нажатием кнопки "назад" или "отмена" форма не будет выбрасывать модалку с предупреждением об измененных данных

- **Критерии готовности кода**  
 получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
**при сохранении мероприятия на бэк отправляется информация о выбранных тэгах** - нет доступа на бек. Надо чекнуть отдельно
все остальное вроде ок
баги не по критериям отписал в личку Эмилии и в канал тестов дискорда

**Comment by KemSummons** [comment]
@bigKingPenguin проверил. все работает, считаю таску полностью выполненной в плане тестирования
