### ISSUE TITLE
Изучить варианты решения проблемы с SSOT(Single source of truth) для ключей библиотеки переводов (i18n)

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#802]
### Описание задачи
Нужно сделать так, чтобы все ключи (тэгов, ошибок), по которым определяется текст перевода находились в одном месте (файле/папке)

### Критерии приемки
- [ ] Переводы работают корректно (на страницах сайта с переводами нет появлений странных текстов формата `header.title`)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by bigKingPenguin** [comment]
Решает задачу #674
