### ISSUE TITLE
Подключение Google Analytics

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#806]
### Описание задачи
На данный момент у сайта нет ни какой аналитики.
Нужно решить - что и как мы будем с этим делать.

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи **story points: 3**
- Сложность
- Объём
- Риски

**Comment by bigKingPenguin** [comment]
@Anaisnet, какие именно показатели нам нужно отслеживать?

**Comment by valentinudovik** [comment]
[!-- Google tag (gtag.js) --.txt](https://github.com/openworld-community/ows-events/files/13424805/--.Google.tag.gtag.js.--.txt)

**Comment by valentinudovik** [comment]
https://analytics.google.com/analytics/web/#/a289973997p412273502/admin/streams/table/6297123522

**Comment by bigKingPenguin** [comment]
Можно тестировать начиная с понедельника 27.11.23

**Comment by Anaisnet** [comment]
Заработает через 2 суток на Тестовом сервере.

**Comment by bigKingPenguin** [comment]
Тег подключен на сайт, определяется в googleAnalytics

![Image](https://github.com/openworld-community/ows-events/assets/124285205/d1306e9e-2856-447b-a421-e99bc92b97a3)

![Image](https://github.com/openworld-community/ows-events/assets/124285205/fa013275-5a41-4fe2-aeeb-735cb098585a)

**Comment by KemSummons** [comment]
Проверено
