### ISSUE TITLE
Вместо ссылка на регистрацию -  "Для связи"

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#822]
### Описание задачи
Изменить текст: Вместо "ссылка на регистрацию" -  "Ссылка для связи".

### Критерии приемки
Добавьте критерии приёмки здесь
- [ ] Отображение текста: "Ссылка для связи" в русской версии и "Link for contact" в английской версии формы создания мероприятия.

![Image](https://github.com/openworld-community/ows-events/assets/33966405/d99f2dc1-5483-4b0d-947f-ec42a4e42068)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

story points: 1

**Comment by KemSummons** [comment]
Исправлено
