### ISSUE TITLE
Как пользователь, я хочу видеть разрешённые форматы картинок для создания ивентов

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#823]
### Описание задачи
Дрбавить на страницу создания ивентов, в разделе "Добавить картинку" информацию о разрешённых форматах и ограничении по весу для загружаемых картинок к ивенту.
1. Подумать и составить текст дизайнеру.
2. Отрисовать его отображение в дизайне для всех наших платформ.
3. Фронтэнду вставить на страницы создания ивентов.

### Критерии приемки
При создании ивента, в разделе  "Создать фото" отображается информация о разрешённых к загрузке форматам и весу картинок для ивента:
- [ ] отображаются разрешенные форматы: jpeg, png, svg, webp
- [ ] отображается ограничение по весу (2 мб)
- [x] -при выборе картинки на компьтере непринимаемые форматы задизейьлены, если браузер не поддерживает то при попытке выбрать файл не того формата появляется ошибка
- [x] принимает только указанные форматы изображений
- [x] не принимает вес картинок больше указанного (2 мб)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by Sinamon-maker** [comment]
разрешенные форматы: jpeg, png, svg, webp

**Comment by Anaisnet** [comment]
А ограничение по весу какое?

**Comment by YakushinSar** [comment]
Комментарий по ошибкам
https://docs.google.com/spreadsheets/d/10ZbVcu3J1OBGzu6mL5t_uQ5wsb929bizIPeEgSW2DYg/edit#gid=1251148435

**Comment by Sinamon-maker** [comment]
Надпись присутствует, есть замечания к ней и пожедания - думаю стоит согласовать текст и создать тогда отдельную задачу иначе все задачи будут висеть, хотя при решистрации например нед подсказки по требованиям к паролю, но задача принята

**Comment by YakushinSar** [comment]
в рамках задачи замечаний нет, текст "форматов и ограничения по весу" будет реализован в отдельной задаче
