### ISSUE TITLE
Я как любой пользователь хочу каждый день видеть информацию об ивенте, который уже начался, но будет идти больше одного дня

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#837]
### Описание задачи
Нужно переделать логику исчезновения ивентов с сайта.
Если указаны дата и время окончания - ориентироваться на них.
Если они не указаны, тогда на дату и время старта.

### Критерии приемки
Обычно ивенты имеют 2-е даты: старт и окончание.
- [ ] Когда ивент, имеющий дату и время окончания, заканчивается - он исчезает с главной страницы сайта.
- [ ] Если ивент по каким-то причинам не имеет даты окончания, ивент будет исчезать после прохождения даты и времени старта.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by i-salimzhanov** [comment]
Согласовано.
