### ISSUE TITLE
Фронтенд: добавить фильтр по тегам с выбором одного варианта для фильтрации

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#843]
### Задача
#826 
Добавить фильтр по тегам

### Имеющиеся данные

1. Эндпоинт для запроса списка используемых тегов (https://api-test.afisha.peredelano.com/api/docs/static/index.html)
2. Дополнительное поле для запроса на фильтрацию на бэке
3. Макет в фигме https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-76272&mode=design&t=q0B7DMe2p7SgQN1H-4
4. Компонент common/ui/Filter.vue

### Порядок выполнения задачи

1. Добавить запрос на получение списка используемых тегов
2. Запрашивать их при загрузке страницы
3. Добавить еще один фильтр в поле фильтров
4. Добавить фильтр по тегам в filter.store

### Критерии готовности
- **Критерии готовности задачи**  

- [ ] при загрузке страницы приходит перечень использованных ключей (список ключей, которые присутствуют в мероприятиях) - их можно посмотреть в devTools и при нажатии на фильтр по тегам
- [x] можно выбрать один фильтр
- [x] при выборе фильтра происходит сортировка мероприятий - приходят мероприятия, у которых есть этот тег

- **Критерии готовности кода**  
получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
6. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
7. Выполнить задачу по секции "Порядок выполнения задачи"
8. Создать пуллреквест в ветку <b><em>main</em></b>
9. Запросить код ревью от лида команды
10. Дождаться аппрува от лида команды
11. Смержить пуллреквест в ветку <b><em>main</em></b>
12. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
13. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by KemSummons** [comment]
1. **при загрузке страницы приходит перечень использованных ключей (список ключей, которые присутствуют в мероприятиях) - их можно посмотреть в devTools и при нажатии на фильтр по тегам** - Очень сложно понять, о чем речь. Если я верно понял, то мы выбираем какой-либо из доступных тегов в поле ввода (Тема) с открытой вкладкой нетворка, после чего можно глянуть ответ запроса, и там в джейсоне будет массив с тегами, по типу такого
        "tags": [
            "exhibition",
            "masterclass",
            "conference",
            "adult"
        ],
Если все так как я описал - то работает. Но формулировка критерия тяжкая)
2. **можно выбрать один фильтр** - я бы добавил, что можно выбрать _только_ один фильтр, конкретно для этой таски
3. **при выборе фильтра происходит сортировка мероприятий - приходят мероприятия, у которых есть этот тег** - предлагаю поменять слово "приходят" на "отображаются", так как при слове "приходят" сразу думаешь о каком-то сообщении или чем-то подобном.

**Comment by bigKingPenguin** [comment]
@KemSummons Да, ты все правильно описал. Если все работает корректно, можно закрывать таск.
