### ISSUE TITLE
Отрисовать кнопки и ссылки

### ISSUE THREAD

**Issue by bigKingPenguin** [openworld-community/ows-events#885]
### Задача
Добавить стили кнопок в компонент Button
Отрисовать в десктопной версии страницу пользователя в соответствии с макетом
Поменять стили кнопок в соответствии с макетами

### Имеющиеся данные

**Макеты кнопок**
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1771-61298&mode=design&t=pdu0bT3TB8TEVfn5-4

**Макеты в фигме (страница пользователя)**
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1348-47072&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9669&mode=design&t=pdu0bT3TB8TEVfn5-4

**Макеты других кнопок:**
1. Страница мероприятия (кнопка для связи и кнопки в модале удаления мероприятий)
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1-17057&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1-17122&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-79551&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-79795&mode=design&t=pdu0bT3TB8TEVfn5-4

2. Страница создания/редактирования мероприятия (кнопки отмены и сохранения)
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=20-10383&mode=design&t=pdu0bT3TB8TEVfn5-4

3. Фильтры на главной странице mobile (кнопки "применить" и "сбросить")
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1-16611&mode=design&t=pdu0bT3TB8TEVfn5-4

4. Страница пользователя (кнопки "новое мероприятие", "внести вклад")
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9669&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1353-60394&mode=design&t=pdu0bT3TB8TEVfn5-4

5. Редактирование профиля на странице пользователя (кнопки отмены и сохранения)
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=189-35252&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1353-48819&mode=design&t=pdu0bT3TB8TEVfn5-4

6. Страница "Мои мероприятия" (кнопка "новое мероприятие")
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9830&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1353-60394&mode=design&t=pdu0bT3TB8TEVfn5-4

7. Хэдер desktop (кнопка "войти"/"пользователь")
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-79073&mode=design&t=pdu0bT3TB8TEVfn5-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-78430&mode=design&t=pdu0bT3TB8TEVfn5-4

### Порядок выполнения задачи
Добавить новую верстку кнопок в компонент Button

### Критерии готовности
- **Критерии готовности задачи**  

- [ ] На десктопе и мобилке на странице пользователя кнопки и ссылки ("редактировать профиль", "мои мероприятия", "избранное", "выйти") соответствуют макету
- Стили кнопок на страницах соответствуют макетам
- [ ] Страница мероприятия (кнопка для связи и кнопки в модале удаления мероприятий)
- [ ] Страница создания/редактирования мероприятия (кнопки отмены и сохранения)
- [ ] Фильтры на главной странице mobile (кнопки "применить" и "сбросить")
- [ ] Страница пользователя (кнопки "новое мероприятие", "внести вклад")
- [ ] Редактирование профиля на странице пользователя (кнопки отмены и сохранения)
- [ ] Страница "Мои мероприятия" (кнопка "новое мероприятие")
- [ ] Хэдер desktop (кнопка "войти"/"пользователь")

- **Критерии готовности кода**  
Получен approve от ревьюера

<details><summary><h3>Порядок работы с git</h3>  

<b>Пожалуйста, при работе в репозитории следуйте процессу, описанному в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb). Особое внимание обратите на именование веток.</b>
</summary> 

1. В интерфейсе задачи, справа от описания, в графе <em>Assignees</em> нажать на ссылку <em>assign yourself</em>
2. Отбранчеваться (создать ветку) от ветки <b><em>main</em></b>.
3. Выполнить задачу по секции "Порядок выполнения задачи"
4. Создать пуллреквест в ветку <b><em>main</em></b>
5. Запросить код ревью от лида команды
6. Дождаться аппрува от лида команды
7. Смержить пуллреквест в ветку <b><em>main</em></b>
8. Закрыть задачу
    1. Если тестировщик нашел проблемы - поправить их в отдельной ветке (назовите её как указано в [этом документе](https://www.notion.so/afisha-06e7b5c3ca0d4fd08631f30f2b42b2fb)), которую нужно создать от самой свежей версии ветки main
    2. Влить данную ветку в ветку, с которой вы работали изначально
    3. Создать пуллреквест в ветку **<em>main</em>**
    4. Дождаться аппрува от лида команды
9. Принять благодарность от лида команды и всей команды Afisha Peredelano
</details>

**Comment by AlexeyPQA** [comment]
Задача проверена, замечаний нет.
