### ISSUE TITLE
Я, как пользователь, хочу находить онлайн мероприятия в поиске и на главной странице, чтобы участвовать в них не выходя их дома.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#894]
### Описание задачи
Я, как пользователь, хочу находить онлайн мероприятия в поиске и на главной странице, чтобы участвовать в них не выходя их дома

### Критерии приемки
Проверить на мобилке и десктопе

- [ ] Онлайн-ивенты отображаются независимо от выбранных страны/города, но к ним применяется поиск по тегам и по строке 
- [ ] Отображается тэг "Онлайн"
- [ ] Там где у оффлайн мероприятий отображаются поля город/страна отображается надпись "Онлайн"
- [ ] Карточка/страница мероприятия соответствуют дизайну:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2841-26605&mode=design&t=AoGoD3OxU8QTd2sX-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1-17087&mode=design&t=AoGoD3OxU8QTd2sX-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=399-28085&mode=design&t=AoGoD3OxU8QTd2sX-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=399-26682&mode=design&t=AoGoD3OxU8QTd2sX-4
- [ ] Карточки мероприятий "Мои мероприятия" и "Избранное" соответсвуют дизайну 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9830&mode=design&t=AoGoD3OxU8QTd2sX-4
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1366-60538&mode=design&t=AoGoD3OxU8QTd2sX-4
- [ ] Время в онлайн-мероприятиях отображается корректно в часовом поясе пользователя
- [ ] Время оффлайн-мероприятия отображается корректно в часовом поясе страны/города проведения мероприятия (перепроверить)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено.
