### ISSUE TITLE
Создать тег "Онлайн"

### ISSUE THREAD

**Issue by Egor-ScrumMaster** [openworld-community/ows-events#895]
Описание:
Добавить тег "онлайн" в базу данных тегов.

**Comment by KemSummons** [comment]
За уточнением критериев приемки надо обратиться к Игорю беку

**Comment by il12** [comment]
Критерии приёмки
-[ ] У онлайн-ивентов отображается тэг "Онлайн"
-[ ] В фильтре по тэгам на главной странице можно выбрать тэг "Онлайн" (он отображается в списке, если есть хотя бы один онлайн-ивент)

**Comment by YakushinSar** [comment]
Проверено, у онлайн-ивентов  тэг "Онлайн" по размеру шире чем указано в фигме, https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=2382-9830&mode=design&t=nCIc0G4PITdCxLPt-4
Больше замечаний нет.
