### ISSUE TITLE
Выпилить уникальность ссылки - до обновления прода!

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#913]
### Описание задачи
Разрешить вставлять создателю ивента вставлять одинаковые ссылки.

_**ВАЖНО!**_
Пока эта задача не будет завершена и залита на Демо, мы не должны заливать Демо на Прод.
Иначе создатели онлайн-ивентов не смогут создать свои мероприятия. Модерация не будет их пропускать.

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
Создателю ивента разрешено вставлять вставлять одинаковые ссылки в разные мероприятия.
