### ISSUE TITLE
Цель спринта: Дать пользователю возможность регистрироваться/авторизовываться с помощью пары логин/пароль и с помощью сервиса google oauth. Добавить внутренние проверки данных при создании ивентов для информирования пользователя о его ошибках.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#915]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
выполено. спринт закрыт.
