### ISSUE TITLE
Я, как посетитель сайта, хочу регистроваться/авторизовываться через пару логин/пароль, для того чтобы создавать мероприятия.

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#916]
### Описание задачи
Пользователю даётся возможность регистрации и авторизации на сайте через пару логин/пароль.

### Критерии приемки
- [ ] Пользователь имеет возможность зарегистрироваться через логин/пароль нажав на кнопку - Зарегистрироваться/Войти.
- [ ] Пользователь должен ввести свой логин и придумать пароль для сайта Афиши.
- [ ] Логин должен быть уникальным для пользователя
- [ ] Для восстановления пароля добавить ссылку "связаться с саппортом"
- [ ] При вводе пароля мы устанавливаем сложность пароля и по-умолчанию не показываем вводимый пароль (а только звездочки), но даём возможность пользователю его увидеть отдельной кнопкой.
- [ ] Пользователю даётся 2-а поля для ввода пароля. Если пароли были идентичны и соответствовали условиям, данные пользователя сохраняются.
- [x] Пользователь может войти в Личный Кабинет после успешной регистрации через пару логин/пароль.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by helloitsme9112** [comment]
макет десктоп: 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=399-37373&mode=design&t=YwauZkALgGExIvov-0
макет мобилка: 
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1-12336&mode=design&t=sZrqy1QvjprxgAxK-0

**Comment by AlexeyPQA** [comment]
проверено
