### ISSUE TITLE
Для ивентов Переделано сделать автоматом время: 15:00 по местному.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#917]
### Описание задачи
Для всех распарсенных ивентов ПеределаноКонф сделать автоматом время начало ивента в 15:00 по местному времени ивента, чтобы не вбивать ручками.

### Критерии приемки
- [ ] Отображение начала ивента в часах по локальному времени

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Выполнено. Проверка осуществлялась на мероприятиях: Бангкок, Лиссабон, Анталия, Ванкувер. После подтягивания на тестовый сервер данных ивентов - время начала проведения отобразилось 15:00.
