### ISSUE TITLE
Поправить рамки у карточек на главной странице 

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#929]
### Описание задачи
Вероятно нужно поправить верстку, т.к. при изменении разрешения экрана меняется отображение рамки у карточек на главной странице Афиши.
Если в макетах дизайна (в Фигме) это не обозначено, Елене нужно тоже дорисовать там.
![Image](https://github.com/openworld-community/ows-events/assets/33966405/c6c5c1d5-a447-422f-a902-b94d2ea09a43)
![Image](https://github.com/openworld-community/ows-events/assets/33966405/179cd8d2-1c6c-47cc-84e6-0cfde6814f1b)
![Image](https://github.com/openworld-community/ows-events/assets/33966405/652b6adc-d85d-4348-ab1e-4e76f0d2eac7)
![Image](https://github.com/openworld-community/ows-events/assets/33966405/7d21df39-6768-443b-befc-68fbf12e50d7)

### Критерии приемки
Рамки должны отображаться со всех сторон карточки, т.к. часто бывают картинки с белым фоном.
- [ ] Рамка отображается со всех сторон карточки, даже если у картинки белый фон.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
проверено
