### ISSUE TITLE
Провести воркшоп/презентацию по работе с проектами в гитхабе

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#945]
- [ ] Подготовить презентацию/воркшоп/демонстрацию работы с проектами в гитхабе.
- [ ] Договориться о времени проведения
- [ ] Провести презентацию/воркшоп/демонстрацию работы

**Comment by toprogramm** [comment]
Добавить ссылку на Ютуб или что то такое.

**Comment by toprogramm** [comment]
Ссылка вот https://www.youtube.com/watch?v=T2PJw1A508s
Добавлю сейчас ссылку на вики
