### ISSUE TITLE
Я, как пользователь, хочу иметь возможность искать мероприятия по датам

### ISSUE THREAD

**Issue by il12** [openworld-community/ows-events#950]
### Описание задачи
Дать пользователю возможность фильтровать мероприятия по датам.

В поиске по фильтру сделать допраздел - поиск по дате. При нажатии на кнопку выпадает календарь с датами и краткими наименованиями дней недели.
Нужно связаться с дизайнером и посмотреть что уже готово для этой задачи в Фигме.
Дизайн:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=3053-127008&mode=design&t=suzdyATztNM9ES5T-0

### Критерии приемки
- [ ] Любой пользователь на главной странице может выбрать один день и увидеть мероприятия проходящие только в этот день. (логика сортировки сложная, подправить ее под этот критерий тяжело, все подробности в директ Дане/Игорю)
- [ ] Любой пользователь может выбрать непрерывный диапазон дат (от и до) и увидеть мероприятия проходящие только в этот диапазон дат.
- [ ] Остальные фильтры применяются вместе с фильтром по дате
- [ ] Нельзя выбрать прошедшие дни

### Предполагаемая сложность
Оцените предполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by helloitsme9112** [comment]
десктоп
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=1293-70531&mode=design&t=AEl1w34Sb1VYVu1K-0
мобилка
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=3638-59103&mode=design&t=AEl1w34Sb1VYVu1K-4
таблета в фигме нет

**Comment by il12** [comment]
Схема как должна работть фильтрация по дате (зелёные ивенты - попадают в выборку, красные - нет)
![Untitled Diagram drawio](https://github.com/openworld-community/ows-events/assets/19169013/33bc7e2e-63ad-4ff7-8fc3-14e12c1fae81)

**Comment by AlexeyPQA** [comment]
Проверено
