### ISSUE TITLE
Внедрить валидацию на страницу создания/редактирования ивентов

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#953]
### Описание задачи
Создать страницу создания/редактирования мероприятия с учетом созданной ранее валидации:
- [ ] Учесть недочеты валидации
- [ ] Не должна быть нарушена логика создания/редактирования мероприятия (все должно работать как и раньше но с проверкой теперь)

Связанная задача https://github.com/openworld-community/ows-events/issues/556

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] На страницу создания/редактирования ивентов можно попасть по кнопкам сайта 'сохранить/редактировать'
- [ ] Можно создавать/редактировать как и раньше, но при sumbit появяться ошибки если пользователь допустил при заполнении формы, при нажатии кнопки браузера назад также появляется модальное окно с предложением закрыть/сохранить

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
проверено
