### ISSUE TITLE
Поправить баг с отображением скролинга в фильтрах поиска в разных версиях браузера.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#958]
### Описание задачи
Поправить баг с отображением скролинга в фильтрах поиска в разных версиях браузера:
полоса прокрутки или очень узкая или почти не видна - в разных версиях браузеров.
Как на десктопной, так и на мобильной версии.

prod Arc:
![Image](https://github.com/openworld-community/ows-events/assets/33966405/1dcdd230-8cb6-467d-b439-7e2758d0a261)

![Image](https://github.com/openworld-community/ows-events/assets/33966405/c65ae323-fe93-4dfe-8431-48e47cb8a981)

Тестовый Хром:
![Image](https://github.com/openworld-community/ows-events/assets/33966405/89c5ef10-9e0f-4971-87bc-a52dfd3f9cf0)

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] В разных версиях браузеров скролинк отображается в соответствии с дизайн-макетом.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by toprogramm** [comment]
пофикшено заменен элемент scroll 
остался  баг на mozilla при выборе Темы мероприятия 

![Image](https://github.com/openworld-community/ows-events/assets/74075594/26c6714a-1d19-4cb9-8895-317455a0635f)

**Comment by toprogramm** [comment]
закрывается по причине того что мы убрираем вкладку тема(перенос на теги), баги скролла пофикшены, задача не акутальна.
