### ISSUE TITLE
Создать посты в соцсетях и выложить ссылку на них в Дискорде

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#959]
Нужно сделать посты в наших соцсетях и в данном разделе, после моего поста выложить ссылку:
https://discord.com/channels/1117875108787273838/1153709404496068691/1204080705093505115

**Comment by toprogramm** [comment]
Запланировано на завтра В 12-00 по GMT+6

**Comment by i-salimzhanov** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7166567340489318400/
Linkedin - английский язык
