### ISSUE TITLE
Изменить дизайн кнопки авторизации Telegram

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#964]
### Описание задачи
Улучшить взаимодействие пользователя посредством единого дизайна кнопок авторизации

Есть готовая кнопка авторизации но она не соответствует общему дизайну. Изменить дизайн кнопки для уже готовой iframe кнопки.
Свзаться с дизайнером после точной увернности что все работает и может исполняться, для согласования дизайна.

Дизайн:
https://www.figma.com/file/13t1lYLJS4Oe7ZQWEfqqlx/Afisha-Backup?type=design&node-id=3148%3A16109&mode=design&t=I9ZIwQRww0DU6h10-1

### Критерии приемки
Страница авторизации/регистрации, кнопка телеграмм

- [ ] Возможность авторизации / регистрации (сохранение функционала)
- [ ] Соответсвие дизайну (мы добавим чуть более круглые края позже, это не важный критерий)
- [ ] Активность кнопки (пока кнопка телеграм не активна она серая, как на нее можно нажать - становится голубой), если есть какаие то нарушения - сообщаем.

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи (1, 2, 3, 5, 8, 13)
- Сложность 5
- Объём 5 
- Риски 5

**Comment by YakushinSar** [comment]
проверено
