### ISSUE TITLE
Написать общие правила валидации для формы создать ивент

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#967]
### Описание задачи
Для всех полей ввода нужны общие правила валидации.
Далее поместим их в Вики, чтобы все могли пользоваться, в т.ч. и тестировщики.

### Критерии приемки

- [x] Поле 'онлайн' - не обязательное, чекбокс, значения true (выбран) или false (не выбран)
- [x] Поле 'таймзона' строка,обязательное, выбор производится из предложенного списка (для города будут изменения - необъодимо решить вопрос с тем чтобы юзер не менял ее - это вводит в заблуэжение так как конкретный город имеет конкретную таймзону)
- [x] Поле 'страна' - строка,обязательное если 'онлайн' false, выбор производится из предложенного списка
- [x] Поле 'город' - строка,обязательное если 'онлайн' false, выбор производится из предложенного списка
- [x] Поле 'адрес' - строка, обязательное если 'онлайн' false, вводится пользователем, максимальное количество символов - 255
- [x] Поле 'название' - строка, обязательное, вводится пользователем, минимальное, максимальное количество символов - 255
- [x] Поле 'описание' - строка, обязательное, вводится пользователем, максимальное количество символов - 255
- [x] Поле 'организатор' - строка, не обязательное, вводится пользователем, минимальное, максимальное количество символов - 255
- [x] Поле 'теги' - массив строк, не обязательное  максимальное количество - 6, выбор производится из предложенного списка
- [x] Поле 'бесплатно' - не обязательное, чекбокс, значения true (выбран) или false (не выбран)
- [x] Поле 'валюта - строка, обязательное если 'бесплатно' false, выбор производится из предложенного списка
- [x] Поле 'цена':
### только число, обязательное (если 'бесплатное', тогда равно false), число должно быть целым, положительным, максимальное значение (пока нет, но должно быть. p.s. by Assa: Утверждено с Бэком) - 999999 (6 символов).
- [ ] Поле 'ссылка' для связи - строка, обязательное, вида - https://fjhjh.ru/blog/?name=struct-url&topic=expl#h1 (протокол/домен/путь/квери-параметры/якорь(конкретный абзац):
### проверяется каждая часть на соответствие регулярному выражению), разрешенные символы - a-z(латинские буквы в нижнем регистре), A-Z( латинские буквы в верхнем регистре - добавлено 19.03.2024), \d (цыфры). Для части /blog -  дополнительно разрешены символы:  '%','_', '.', '~', '+', для query вида ?name=struct-url&topic=expl - '%','_', '.', '~', '+', '=', '-', а также '?'  в начале, для части указания на абзац на странице #h1 - '_', начинается с '#'.   Максимальная длина ссылки - 255 символов.
- [x] Поле 'картинка':
### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
предлагаю  текст требования к весу и форматам изображений к кнопке 'добавить фото'  реализовать так как во вложенном файле
![2024-02-15_14h44_48](https://github.com/openworld-community/ows-events/assets/130306556/447e2e24-98ab-4404-9ca0-580603f66b99)

**Comment by YakushinSar** [comment]
Поле 'цена' - число, обязательное если 'бесплатно' false, число должно быть целым, положительным, максимальное значение ? данное поле не удаляет автоматически символы "+" и "-" по аналогии с буквами, спецсимволами, пробелами. Но в созданном мероприятии "+" и "-"  не отображаются, возможно ли сделать запрет на удаление "+" и "-" при их вводе в поле "Цена". Для поля  "Цена" нет граничных значений числа, при попытке ввести большое число , цена в ивенте 
![2024-02-15_15h01_09](https://github.com/openworld-community/ows-events/assets/130306556/df62441e-b064-4bf6-b397-db734fd14333)
отображается следующим образом:

**Comment by Sinamon-maker** [comment]
Предлагайте граничную цену, мы не можем запретить хоть миллион поставить но совсем неадекватное число стоит запретить.  Отображение в ивенте - тоже не к валидации, отдельная задача- но тоже чтоит расписать,с какого числа начинается такая 'красота', убрать знаки из инпута- это не к валидации, это отдельная задача - можно создать,

**Comment by il12** [comment]
Предлагаю максимальную цену - 999999 любой валюты

**Comment by YakushinSar** [comment]
"Поле 'ссылка' для связи - строка, обязательное, вида - https://fjhjh.ru/blog/?name=struct-url&topic=expl#h1 (протокол/домен/путь/квери-параметры/якорь(конкретный абзац) - проверяется каждая часть на соответствие регулярному выражению),  максимальная длина - ?"
предлагаю так как формально, длина  не ограничена, но все же поставить не длину не более 2048 символов, чтобы была возможность тестирования данного значения при необходимости.

**Comment by toprogramm** [comment]
частично добавлено в вики, нужно дообсудить пару элементов.

**Comment by toprogramm** [comment]
Проверить на соответсвие критериям:

- [ ] Поле 'адрес' - строка, обязательное если 'онлайн' false, вводится пользователем, максимальное количество символов - 255
- [ ] Поле 'название' - строка, обязательное, вводится пользователем, минимальное, максимальное количество символов - 255
- [ ] Поле 'описание' - строка, обязательное, вводится пользователем, максимальное количество символов - 255
- [ ] Поле 'организатор' - строка, не обязательное, вводится пользователем, минимальное, максимальное количество символов - 255
- [ ] Ссылка проверяется каждая часть на соответствие регулярному выражению), разрешенные символы - a-z(латинские буквы в нижнем регистре), A-Z( латинские буквы в верхнем регистре - добавлено 19.03.2024), \d (цыфры). Для части /blog -  дополнительно разрешены символы:  '%','_', '.', '~', '+', для query вида ?name=struct-url&topic=expl - '%','_', '.', '~', '+', '=', '-', а также '?'  в начале, для части указания на абзац на странице #h1 - '_', начинается с '#'.

**Comment by unomat20b** [comment]
Поле цена - сейчас возможно только целое  число, но 3,5$ это возможная цена.
Поле время - уменьшить числа для выбора отличного от 12:00 
Поле ссылка - при вводе короткой ссылки мы бы могли сами подставлять htths://
Поле название - минимальное число символов 2
Поле описание - минимальное число символов 20

**Comment by AlexeyPQA** [comment]
Проверено. В поле "Емейл" можно ввести невалидный емейл следующего вида: http://www.ya/ru [https://drive.google.com/file/d/1gGzAEVXr6sfwOvkBChmLJzTr234jYDMg/view?usp=drive_link](url)
