### ISSUE TITLE
Оптимизировать фон бэкграунда для страницы Авторизация

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#981]
### Описание задачи
Сейчас фон бэкграунда - это целая картинка, имеет очень большой вес.
![Image](https://github.com/openworld-community/ows-events/assets/33966405/ab14d576-c01d-400b-ac18-5535fc06ec6b)
https://afisha.peredelano.com/_nuxt/unauthorized-background_1x.cfdfc617.png

Нужно её переделать т.обр., чтобы она весила (хотя бы) не более 400 kb.
Дизайнеру обсудить с Ваном разные варианты решения и принять в работу.
Проверить все макеты и также оптимизировать для них фон, если требуется.

### Критерии приемки

- [ ] Фон Бэкграунд (картинка) для страницы Авторизация не должен весить более 20 kb
- [ ] Бэкграунд грузится быстро даже на скорости fast 3G

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность 1
- Объём 1
- Риски 1

**Comment by YakushinSar** [comment]
Проверено
