### ISSUE TITLE
Нет отображения картинки из ивентов в соцсетях (Твиттер точно) при посте линка на ивент.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#986]
### Описание задачи
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [x] В fasebook должна появиться возможность выкладывать  пост - вообще ничего не отображалось
- [ ] сайты должны показывать canonical url без api (https://debug.iframely.com/?uri= ,  https://developers.facebook.com/tools/debug/ ) -  fasebook должен показать картинку как и twitter - этот в любослучае показывает
- [x] В fasebook должна появиться возможность выкладывать  пост - вообще ничего не отображалось
- [x] в twitter возможно исчезнет задержка при репосте с пояалением картинки
- [x] linkedin если есть возмлжность проверить, там проблем не было, но...

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
в линкедин выкладывается без замечаний информация о ивенте
в Твиттер - картинка отображается не сразу
в фейсбуке отображается только ссылка
ссылка на таблицу с проверками и багами
https://docs.google.com/spreadsheets/d/1_q4VJT0x9oYbaoBDqpg03jxNdrT-0I61F0OuEVJPRvo/edit?usp=sharing

**Comment by toprogramm** [comment]
Перенести с тестового на демо и прод .

**Comment by AlexeyPQA** [comment]
в твиттере были проверены ивенты с прода - отображение в соц сети корректно

**Comment by AlexeyPQA** [comment]
проверено
