### ISSUE TITLE
Добавить блюр для прошедших событий

### ISSUE THREAD

**Issue by orby-tech** [openworld-community/ows-events#99]

**Comment by valentinudovik** [comment]
Это временное решение? Мы могли бы сделать так, чтобы на главной появился подраздел "Прошедшие события", а кнопка "Связаться" была бы неактивной. С Андреем обсудили этот момент.

**Comment by lebedandrei** [comment]
Если всё-же их просто блюрить, то может изменить дизайн карточек прошедших событий? Может, чтобы две карточки в ряд помещались на экране, а не одна большая? Или на данном этапе это долго?
