### ISSUE TITLE
Fix Разрешить добавлять картинки в ВЕРХНЕМ регистре

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#993]
### Разрешить добавлять картинки в ВЕРХНЕМ регистре на добавлении/измении ивента
Опишите задачу здесь

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ] Конкретный критерий приёмки

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
проверено
