### ISSUE TITLE
Личный кабинет - Сделать статичным боковое меню личного кабинета

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#994]
### Описание задачи
Сделать статичным боковое меню личного кабинета (она всегда видимая)
А разделы динамическими ( они изменяются)

![Image](https://github.com/openworld-community/ows-events/assets/74075594/b453ea5d-a81a-4090-85b6-3c553fb3a953)

![Image](https://github.com/openworld-community/ows-events/assets/74075594/a5dd05a4-f292-4994-b495-dc6e87ebf45c)

### Критерии приемки
Добавьте критерии приёмки здесь
Сохраняйте нижепреведенный формат
- [ ]  Боковое меню личного кабинета всегда находится слева при изменении раздела (на десктопе)
- [ ] Разделы выглядят нормально, ничего не перекосилось
- [ ] в меню подсвечивается в каком разделе находишься
- [ ] редактирование профиля не в модалке а также отнесено к разделу и выглядит нормально
- [ ] авторизация по отдельному url /auth и функуионирует нормально
- [ ] logout также отрабатывает

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
проверено, ошибка во вложении
https://docs.google.com/spreadsheets/d/10ZbVcu3J1OBGzu6mL5t_uQ5wsb929bizIPeEgSW2DYg/edit#gid=160463841

**Comment by YakushinSar** [comment]
в рамках критериев приемки к задаче замечаний нет
