### ISSUE TITLE
RADIX Select Заменить компоненты на Radix Vue элементы

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#995]
### Описание задачи
Заменить компоненты на Radix Vue элементы

### Критерии приемки
- [ ] на странице создать/редактировать ивент заменены: страна, город,  валюта - работают без нареканий
- [ ] они же - скролл хорошо виден если он есть
- [ ] работают с клавиатуры реагируют на 'tab', открыть 'enter',  стрелочками можно выбрать элемент, очистить (enter)
- [ ] на главной заменен дропдаун страна (на дксктопк 0 от 768px) - работает также без нареканий, на 1440 сепараторы между фильтрами при фокусе исчезают

Компоненты к проверке
- [ ] Страна(edit page)
- [ ] Город(edit page)
- [ ] Валюты (edit page)
- [ ] Страна(main page desctop версия)

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено.
