### ISSUE TITLE
RADIX ComboBox Заменить компоненты на Radix Vue элементы

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#996]
### Описание задачи
Заменить компоненты на Radix Vue элементы - RADIX ComboBox

### Критерии приемки
- [ ] Ничего не сломалось
- [ ] Навигация по айтемам при раскрытом списке стрелочками
- [ ] tab отрабатывает корректно
- [ ] Не появляются лишние бордеры при навигации клавиатурой
- [ ] Автокомплит при введении работает корректно

Компоненты к проверке
- [ ] выбор таймзоны на создании ивента

NOTE BENE 
в текущий момент есть проблемы с производительностью (596 часовых поясов), подниму вопрос на демо
Игорь бек в курсе, решение разрабатывается

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by YakushinSar** [comment]
проверено, комментарии во вложении https://docs.google.com/spreadsheets/d/10ZbVcu3J1OBGzu6mL5t_uQ5wsb929bizIPeEgSW2DYg/edit#gid=713119272
