### ISSUE TITLE
Как пользователь, я хочу видеть всплывающее окно с сообщением "Вы действительно хотите выйти из аккаунта?", чтобы подтвердить своё намерение выйти из аккаунта и избежать случайного выхода.

### ISSUE THREAD

**Issue by toprogramm** [openworld-community/ows-events#997]
### Критерии приемки
- [ ] Появляется всплывающее окно  с заголовком "Выйти из аккаунта",  описанием "Вы уверены, что хотите выйти из аккаунта?", Кнопкой "Да"(выйти), кнопкой "Отмена" которая закрывает окно, и кнопкой закрыть окно (крестик в правом верхнем углу) и все работает нативно и понятно. (далее подробнее)
- [ ] Когда я нажимаю "Выйти из аккаунта" в личном кабинете, я хочу увидеть окно содержащее
    - [ ] Заголовок "Выйти из аккаунта"
    - [ ] Текст "Вы уверены, что хотите выйти из аккаунта?"
    - [ ] Кнопка "Да"
    - [ ] Кнопка  "Отмена".
    - [ ] "Крестик" в правом верхнем углу чтобы закрыть

- [ ] Я хочу, чтобы это окно работало в мобильной версии сайта.
- [ ] При нажатии на кнопку:
    - [ ] При нажатии "Да" я ожидаю, что действительно выйду из аккаунта.
    - [ ] При нажатии "Отмена" я ожидаю, что окно диалога закроется.
    - [ ] При нажатии "Крестика" я ожидаю, что окно диалога закроется.
- [ ] Я хочу иметь возможность выбрать язык: русский или английский. (работает и переведено на оба языка)
    - [ ] Русский
    - [ ] Английский

```
# Сноска для программистов
Добавлено всплывающее окно как компонент из библиотеки radix (это не проверяем), RADIX Dialog Заменить компоненты на Radix Vue элементы
```
### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи
- Сложность
- Объём
- Риски

**Comment by AlexeyPQA** [comment]
Проверено
